### ISSUE TITLE
Modifier within layers

### ISSUE THREAD

**Issue by kooskaspers** [rvaiya/keyd#103]
Since upgrading to V2, I find my config not to work properly anymore. It obviously has to do with the new way how modifiers are applied (by making use of their own layer), but I can't get my head around it.

This is the config:

```
[main]
control = layer(alt)
meta = layer(control)
alt = layer(meta)
rightmeta = layer(control)

capslock = layer(vim)

[vim]
k = up
j = down
h = left
l = right
i = home
o = end
p = pagedown
u = pageup
backspace = delete
shift = layer(shift)
meta = layer(control)
```
Now the goal is, that whenever I'm within the VIM layer (by holding capslock), I'm able to select text when I'm also pressing shift + arrow keys (h,j,k,l). This worked fine in prev version of Keyd, and was a killer feature for me. How would you solve this one in the new version of Keyd? Same applies for holding control (to easily step through words, when combined with left (h) / right (l) keys.

**Comment by rvaiya** [comment]
One of the reasons for this design change is that it allows the user to do nested mapping without worrying about interference from active modifiers. It is also arguably more intuitive (WYSIWYG).

E.G

```
[alt]
control = layer(nav)

[nav]
h = left
```

produces `left` under the new rules instead of `A-left` which would previously have been impossible to achieve. As you've noticed this is directly contrary to what you want in this instance.

Fortunately it is still possible to simulate the old behaviour with some additional effort by defining nested layers that  send the appropriate sequences.

E.G

```
[shift]

capslock = layer(vim_shift)

[vim]

shift = layer(vim_shift)

[vim_shift]

k = S-up
j = S-up
...
```

It's a little uglier than the older method but allows for a larger number of configurations.

Personally I would recommend keeping as much functionality as possible within your capslock layer. For example,  you might consider binding 'S-<left/up/down/right>` to `uiop` directly instead of requiring an additional chord (`capslock+shift`). I do something similar and find it to be more pleasant than chording.

**Comment by kooskaspers** [comment]
Wonderful. It's indeed a bit more configuration, but you are absoutelely right, it makes it indeed way more WYSIWYG.
Grateful for the help!
