### ISSUE TITLE
Why must keyd have only one instance?

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#105]
This might be just a question for curiosity's sake, but I realized from discussion at #104 that I don't know why it's important for `keyd` to have only one process (daemon) running.

Is it perhaps because the conf files directory is not configurable, and so any two instances will have the same configuration? Or is it because it would be inefficient, maybe?

It seems on the surface that if you could configure one `keyd` instance to remap one keyboard, it would be ok to have another `keyd` instance remapping another keyboard. Theoretically :)

**Comment by rvaiya** [comment]
The main reason is because only process can control an input device at a given time. When you combine this with the fact that it is not a good idea t give normal users direct access to /dev/input/* and there there is no way for the disparate processes to communicate, the problem naturally lends itself to a single system service. Finally keyd was originally designed to feel like QMK which works everywhere and is baked into the keyboard. Though this last reason is less important than it used to be.  You may want to read #70. 

> It seems on the surface that if you could configure one keyd instance to remap one keyboard, it would be ok to have another keyd instance remapping another keyboard. Theoretically :)

This is true, but I can't think of any reason why this would be preferable to the current approach.

**Comment by canadaduane** [comment]
> This is true, but I can't think of any reason why this would be preferable to the current approach.

Agreed, and thanks for the explanation. I'll close this now.
