### ISSUE TITLE
The right control is remapped to `leftcontrol` for any configuration

### ISSUE THREAD

**Issue by alefbragin** [rvaiya/keyd#114]
The right control is remapped to `leftcontrol` for any configuration, even for a minimal config like it:

```ini
[ids]
*
[main]
```

When I hit the right control key I get:

```
> sudo keyd -m
keyd virtual keyboard	0fac:0ade	leftcontrol down
keyd virtual keyboard	0fac:0ade	leftcontrol up
```

When I stop the `keyd` I get:

```
> sudo systemctl stop keyd && sudo keyd -m
Microsoft Microsoft Ergonomic Keyboard	045e:082c	rightcontrol down
Microsoft Microsoft Ergonomic Keyboard	045e:082c	rightcontrol up
```

My system:

```
> inxi -Sz
System:
  Kernel: 5.13.19-2-MANJARO x86_64 bits: 64 Desktop: GNOME 41.2
    Distro: Manjaro Linux
> keyd --version
keyd version: 2.2.3-beta (1f0f2babd5c2e44b89d1fd8233f217483da65bcc)
```

**Comment by rvaiya** [comment]
This is by design. It shouldn't matter in practice since most software uses the display server to obtain active modifier information which doesn't encode any information about the key.

**Comment by alefbragin** [comment]
> This is by design. It shouldn't matter in practice ...

I also don't have use cases to dedicated right control key. I thought I just faced up to a bug.

**Comment by Louis-dM** [comment]
> This is by design. It shouldn't matter in practice since most software uses the display server to obtain active modifier information which doesn't encode any information about the key.

I'm just curious, why have you designed it like this? I see you've said "The key logic can be deceptively simple and contains a few subtleties that need to be managed properly", is it one of these subtleties?

I'm asking because I'd love to be able to map that key differently to my leftcontrol, but I'm sure you know better than me why this might be a bad idea!

**Comment by rvaiya** [comment]
> is it one of these subtleties?

Sort of. There is no technical reason the codes can't be distinguished, but for implementation and conceptual reasons it is better to just treat everything as a special kind of layer. A consequence of this is that anything bound to `layer(control)`, including `rightcontrol` by default, will emit `leftcontrol` since layer modifiers emit their left control codes by design.

Most of the time applications deal with `'modifier masks' (usually provided by the display server) and don't care which modifier code is actually depressed. That is, the application sees both `rightcontrol+c` and `leftcontrol+c` as 'control modifier + c`. In theory it is possible for a program to distinguish between different modifier codes using something like xinput (I'm not sure if this is possible on wayland), but this would break right hand modifiers for the user and I'm not aware of any programs that behave like this in practice.

I have yet to encounter anyone for whom this poses a real issue (though it seems to be a common source of confusion), but I am not opposed to changing the behaviour if such a need arises. 

It is worth reiterating that you can still *reassign* `rightcontrol` (it is a valid left hand value) you just cant assign *to* `rightcontrol`. In general you are encouraged to think about modifiers in the abstract rather than caring about the actual keycodes which get emitted.

**Comment by Louis-dM** [comment]
Well, I'm on Wayland so I guess it doesn't matter if it's a problem for me, if it can't be fixed! And besides, my issues were only small, if the update would be anything non-trivial then it's probably not worth it.

The only real inconvenience was with a game that uses left and right Shift for different purposes. keyd maps them both to `leftshift`. The game offers no way to remap the controls, so I've just opted to disabling keyd while playing, which is easily done.

**Comment by rvaiya** [comment]
> The only real inconvenience was with a game that uses left and right Shift for different purposes. 

`rightshift = rightshift` is legal in the latest commit, but the warning has been kept to avoid potential issues.

**Comment by SaadiSave** [comment]
> It is worth reiterating that you can still _reassign_ `rightcontrol` (it is a valid left hand value) you just cant assign a key _to_ `rightcontrol`. In general you are encouraged to think about modifiers in the abstract rather than caring about the actual keycodes which get emitted.

@rvaiya Is this still true?

On my machine:

```conf
[ids]

*

[main]
leftmeta+f23+leftshift = rightcontrol
```

Correctly remaps the copilot key to right control

**Comment by voidzero** [comment]
Right control is very much needed, because of compose:rctrl. Using keyd, I can no longer use that.

**Comment by voidzero** [comment]
Ok, found my workaround. In default.conf:
`rightcontrol = compose`
and then
`setxkbmap -option compose:menu`

if you specify `rightcontrol = menu` this translates to `XF86MenuKB`, but `compose` translates to `Menu`. Confusing but maybe this may help someone else. The proper fix is to just remain able to use Control_R, imho.

**Comment by anonghuser** [comment]
fwiw virtualbox uses rightcontrol as host key by default too
