### ISSUE TITLE
cannot override  hybrid modifiers layers like [A-S] or [A-C]

### ISSUE THREAD

**Issue by mattuylee** [rvaiya/keyd#115]
Hi all! Thanks to the amazing tool, I have mapped `Alt hjkl` to the arrow keys. While when `Ctrl-Alt-L` is pressed,  I want `Ctrl-right` but get `Ctrl-Alt-L`. I tried this:
```ini
[ids]
*
[main]
leftalt = layer(alt_layer)

[alt_layer]
l = right
control = leftcontrol
```

and this:
```ini
[ids]
*
[alt]
l = right
[A-C]
l = C-right
```
But it doesn't work. I have tried to replace `[A-C]` with `[C-A]`、`[control-alt]`、`[alt-control]`, no effect as well.
Since I can override the `[alt]` layer, can I override `[alt-control]` and others?

Admittedly, the following config works:
```ini
[ids]
*
[alt]
l = right
leftcontrol = layer(alt_control_layer)

[alt_control_layer]
l = C-right
```
But it's a little too complex since I have to map many other keys like this such as `Shift-Alt-L`、`Ctrl-Shift-Alt-L`.

Is there a simpler and more graceful solution? Any help is appreciated!

**Comment by rvaiya** [comment]
> While when Ctrl-Alt-L is pressed, I want Ctrl-right but get Ctrl-Alt-L. I tried this:
> 
> 	[ids]
> 	*
> 	[main]
> 	leftalt = layer(alt_layer)
> 	
> 	[alt_layer]
> 	l = right
> 	control = leftcontrol


> Since I can override the [alt] layer, can I override [alt-control] and others?`

Unfortunately not, this is because of the way layers with modifiers work. Combining two or more of them doesn't actually activate a third layer, it just combines the modifiers of the currently active layers. The reason `[alt]` works is because the default config looks something like this

```
[main]

rightalt = layer(alt)
leftalt = layer(alt)
rightcontrol = layer(control)
leftcontrol = layer(control)

[alt:A]
[control:C]
```

Adding bindings directly to `[control]` or `[alt]` is just a convenient way of doing simple modifier overrides under the stock bindings.  When you press `leftcontrol+leftalt` you are actually activating two layers named `alt` and `control`. The modifiers of these layers combine to produce the active modifier set `A-C`.

> Admittedly, the following config works:
> 
>	[ids]
>	*
>	[alt]
>	l = right
>	leftcontrol = layer(alt_control_layer)
>	
>	[alt_control_layer]
>	l = C-right

This is indeed the correct approach. It is a little more cumbersome but it gives you a little more flexibility since things inside `[alt_control_layer]` don't have to have a control prefix. This allows you to do things like:

	[ids]
	*

	[control]
	alt = layer(alt_control_layer)

	[alt]
	l = right
	control = layer(alt_control_layer)
	
	[alt_control_layer]
	l = C-right
	a = pagedown
	b = M-left


without having `leftalt+leftcontrol+b` emit `C-M-left`. See also #103.

> But it's a little too complex since I have to map many other keys like this such as Shift-Alt-L、Ctrl-Shift-Alt-L.

My advice would be to take full advantage of layers and try not to nest too many things. Why map `control+capslock+h` to `control+left` when you can shift your fingers down one row and use `capslock+n`? There may be occasions when you want to do nesting because you run out of space in your main layer, but in general they should be the exception rather than the rule. 

Once you become accustomed to 'flatter' layouts you will come to appreciate how much strain the additional chording puts on your fingers. The sort of finger gymanstics required to activate things like `control+alt+shift+q` are generally undesirable and anti patterns which probably emerged for a variety of historical reasons (one of the things macos gets right is to eschew these patterns). You may want to take a look at the new application specific logic, so you can make more effective use of your limited real estate. Having said all that, you are free to replicate the traditional approach in keyd if you really want :P.
