### ISSUE TITLE
Alternate layout modifier support

### ISSUE THREAD

**Issue by Kommynct** [rvaiya/keyd#119]
See https://github.com/rvaiya/keyd/issues/13

My justification: "So, yeah, i've been banging my head against this for a while, and was really hoping that wasn't the solution because what about instances with multiple modifiers? if I was to hit shift, THEN control and hit a modifier, it would just not work... as it would've switched to the shift layout instead of the ctrl+shift layout, correct? This seems... extremely inelegant compared to the previous way of handling things. Am I missing something?

It's going to be a separate layer for control, for control+alt, for control+alt+shift, for alt+shift, and so on... that seems kinda... silly.

edit: and then to REALLY make it work for all circumstances, you'd have to create separate layers for every single possible ORDER of modifiers, too.

edit2: and furthermore that doesn't even include modifiers+punctuation which are used heavily in my sway config as ',. are located in qwe

So, yeah, i'm gonna beg for that feature hahaha."

This change alone QUADROUPLES the size of my config, WITHOUT adding all possible combinations and just sticking to the main 3 that are important (ctrl, alt, and super)

Worse yet is all possible starting combinations, so, if I was to hit shift BEFORE ctrl, i'd have to create a whole additional layer to makeup for that, or my keybind just wouldn't work.

**Comment by Kommynct** [comment]
Perhaps a better solution would be to make the default behavior to make the various layers by default assume the original layout, unmodified, and able to be defined separately, as though it was a brand new layer with no assumptions?

**Comment by rvaiya** [comment]
> This seems... extremely inelegant compared to the previous way of handling things. Am I missing something?

No, we are in agreement on this point. If your objective is to remap every single modified combination then I can't contest that having a dedicated modifier keymap is a superior solution. My issue is with the premise that this is generally desirable.

> edit: and then to REALLY make it work for all circumstances, you'd have to create separate layers for every single possible ORDER of modifiers, too.

Not necessarily, you could reuse defined layers since modifiers are not order dependent (and order would be preserved anyway by virtue of the activation path).

E.G

	[shift]
	alt = layer(alt_shift)

	[alt]
	shift = layer(alt_shift)

	[alt_shift]
	A-S-c
	A-S-d
	A-S-e
	...

This technique has been successfully used to define custom shift layers for nested layouts (e.g #33). 

> and furthermore that doesn't even include modifiers+punctuation which are used heavily in my sway config as ',. are located in qwe

	for c in {a..z} , . - \; [ ]; do echo "$c = C-$c"; done

:P

> This change alone QUADROUPLES the size of my config.

Just pretend you are American ;).

> Worse yet is all possible starting combinations, so, if I was to hit shift BEFORE ctrl, i'd have to create a whole additional layer to makeup for that, or my keybind just wouldn't work.

This wouldn't be necessary since, `A-S-c` is the same thing as `S-A-c`. 

The set of all modifier combinations is effectively the [power set](https://en.wikipedia.org/wiki/Power_set) of all modifiers minus the empty set, so there are (2^4-1 =) 15 possibilities.
Having said that, I agree that this is inferior to the old solution and probably not something you would want to do by hand.


---


I feared this decision might elicit an impassioned response from the two people who use the feature when I decided to give it the axe :P. Since you've put me on the back foot, I will provide my rationale (as the user of an alt layout myself):

 - The user that wishes to preserve qwerty bindings is probably trying to tap into established muscle memory for certain bindings, these shortcuts are finite, and small enough in number to explicitly remap.

  - Most of the time application shortcuts are designed to be mnemonic and have no relation to where keys are physically located on the board. Since you already know your layout, it isn't any additional effort to figure out where new (unremapped) shortcuts are.
   
 - Most other remapping tools don't allow you to do this (probably a bad reason)

 - The vast majority of shortcuts are one modifier deep (e.g `control` or `alt`) and can be covered with a modest number of additional bindings

 - Layers let you do whatever you want, why confine yourself to qwerty? :P

 - Explicit is better than implicit: Yes, it is a python meme, but it is also (occasionally) sage wisdom

 - Implementation related reasons: there were a few of these (potential conflicts with other features) but I am having trouble conjuring them from memory now.

I generally like to avoid being too prescriptive, but I would ask you to pause and consider whether not you really *need* this feature as much as you think you do. If you meditate upon it hard enough I suspect you may find that you do not.

As a parting gift, here is a python script to generate the config that makes baby jesus cry:

	#!/usr/bin/python3

	# Don't use this :P

	from itertools import combinations

	mods = ['meta', 'alt', 'shift', 'control']

	# Yo dawg, I heard you like layers...
	for i in range(len(mods)):
		for modset in combinations(mods, i+1):
			modset = sorted(modset)

			layer_name = '_'.join(modset)
			mod_tags = '-'.join([{ 'meta': 'M', 'alt': 'A', 'shift': 'S', 'control': 'C', }[m] for m in modset])

			print(f'[{layer_name}:{mod_tags}]')

			for next_mod in mods:
				if next_mod not in modset:
					next_layer = '_'.join(sorted(list(modset)+[next_mod]))

					print(f'\t{next_mod} = layer({next_layer})')

			# Paydirt, modify to taste
			for c in "abcdefghijklmnopqrstuvwxyz0123456789,.;/[]\\-=`'":
				print(f'\t{c} = {mod_tags}-{c}')


[Here](https://gist.github.com/03c2bdd850dddad05dd9460f9b3944ad) is the output.

**Comment by Kommynct** [comment]
OKAY, YOU COMPLETELY WIN THIS ONE, thanks for all the help you have been truly awesome. The biggest thing there that changed my mind was the ordering of the activation not mattering anymore, this is still annoying for my weird usecase (obviously) but it's totally fair.

I have two small remaining issues left, with the way I have it setup, dvorak is an alternate layer, is there no longer a way to make it automatically startup as the alternate layer, rather than main? I don't see a clear way to do this in the manual.

I also want to make ctrl+alt+shift+tab switch between dvorak and qwerty, I think i'm missing something obvious here, but I really don't see it.

https://pastebin.com/qmx4i21f

**Comment by rvaiya** [comment]
> is there no longer a way to make it automatically startup as the alternate layer, rather than main? 

The way to do this is to define your default layout in `[main]` and create an empty layout for 'qwerty' (the stock bindings).

E.G

	[main]
	s = o
	d = e
	...

	[qwerty:layout]

> I also want to make ctrl+alt+shift+tab switch between dvorak and qwerty.

It is possible to achieve this using nested layers with the appropriate modifiers.

E.G

	[main]
	control = layer(dvorak_control)

	# dvorak bindings..

	s = o
	d = e
	...

	[qwerty:layout]

	# qwerty control path...

	[control]
	alt = layer(control_alt)

	[control_alt:C-A]
	shift = layer(control_alt_shift)

	[control_alt_shift:C-A-S]
	tab = layout(main)


	# dvorak control path...

	[dvorak_control:C]
	alt = layer(dvorak_control_alt)

	[dvorak_control_alt:C-A]
	shift = layer(dvorak_control_alt_shift)

	[dvorak_control_alt_shift:C-A-S]
	tab = layout(qwerty)

Note that the above config is order dependent (you must hit `control+alt+shift+tab` in sequence). It is possible to make it order agnostic with some additional effort.

in general I would advise you to avoid this kind of nesting and do something like

	capslock = overload(capslock, capslock)

	[capslock]

	q = layout(qwerty)
	w = layout(main)

instead.

**Comment by Kommynct** [comment]
https://pastebin.com/BtL3ezP5

Incase anyone is trying to replicate this, here's the finalized config, bam, perfect, thank you so much.

**Comment by rvaiya** [comment]
The new modifier behaviour makes this a lot cleaner. You can just redefine each key within its modifier layer and they should combine as expected. See the changelog and man page for details.

E.G

```
	[alt]
	a = A-a
	s = A-o
	...

	[meta]
	a = M-a
	s = M-o
	...
```

**Comment by Kommynct** [comment]
I have updated the config incase anyone wants it here

https://pastebin.com/raw/121bmJ9h
