### ISSUE TITLE
Overload(meta, esc) still sends meta on key tap

### ISSUE THREAD

**Issue by humanplayer2** [rvaiya/keyd#121]
I experienced the title issue in v1  and have therefore updated to v2, where I see it, too. With config

```
[ids]

*

[main]

capslock = overload(meta, esc)
```
CapsLock crreclty behaves as Meta when held, but when pressed alone, it does not correctly behave only as Esc, but also sends a Meta signal:

```
humanplayer2@popos2110:~$ keyd -m
keyd virtual keyboard	0fac:0ade	leftmeta down
keyd virtual keyboard	0fac:0ade	leftmeta up
keyd virtual keyboard	0fac:0ade	esc down
keyd virtual keyboard	0fac:0ade	esc up
```
In my config I overload to a custom layer that makes CapsLock behave as Ctrl on part of the keyboard, e.g. including `f = C-f`. After `CapsLock + f`, a `leftmeta` signal is also send.

I'm on Pop!_OS 21.10 running GNOME 40, currently under Xorg.

**Comment by rvaiya** [comment]
> CapsLock crreclty behaves as Meta when held, but when pressed alone, it does not correctly behave only as Esc, but also sends a Meta signal:

This is expected behaviour. As soon as you press `capslock` the corresponding layer is activated which causes meta to be sent (since meta is a layer with modifiers). Upon release the layer is deactivated and the desired keyboard (`esc`) is sent. This allows you to do things like `meta`+click. If you want to prevent meta from being activated then you need to define a custom layer which doesn't include meta as a modifier but sends the appropriate meta keycodes

E.G

```
overload(mymeta, esc)
[mymeta]

a = M-a
b = M-b
# etc...
```

You can also add a timeout to overload so it doesn't activate the layer unless a certain amount of time in miliseconds has elapsed, (e.g `overload(meta, esc, 200)`). Note that the timeout syntax is currently experimental and subject to change.

> In my config I overload to a custom layer that makes CapsLock behave as Ctrl on part of the keyboard, e.g. including f = C-f. After CapsLock + f, a leftmeta signal is also send.

I'm not sure what you mean by this. In the config above you've remapped capslock to `meta`, not `control`. Can you post the full config and specify the problematic key sequence?

**Comment by humanplayer2** [comment]
Ah, sorry, I had not understood that I saw the intended behaviour. I thought the the tap signal would be send only on release, so the it would be known whether another key was pressed too or not. I also see why that would exclude other use cases, though.

Thank you for both of your suggestions. I've tried the timeout, and that seems to relieve my issue (that the GNOME overview would pop up when I tapped for escape).

As for the second part, then I apologize: I hadn't thought the issue through.
