### ISSUE TITLE
transparent layers?

### ISSUE THREAD

**Issue by kkga** [rvaiya/keyd#123]
Sorry if this a duplicate or if misunderstand the configuration.

I have the following config where holding <kbd>f</kbd> activates the `extend` layer with navigation keys on the homerow. The problem is that none of the other keys work when the `extend` layer is active and I'm unable to use modifiers combined with the arrow keys.

Guess I can copy the needed modifiers to `extend` layer as well, but I just wanted to confirm if this is the expected behavior first or if I'm missing some other config options. Thank you!

```
[ids]

0001:0001

[main]

leftalt = layer(meta)
leftmeta = layer(alt)
capslock = overload(C, esc)
f = overload(extend, f)

[extend]

h = left
j = down
k = up
l = right
y = home
u = pagedown
i = pageup
o = end
m = enter
; = backspace
```

**Comment by rvaiya** [comment]
Sorry if this a duplicate or if misunderstand the configuration.

> The problem is that none of the other keys work when the extend layer is active 

This is by design. See #103 if you are interested in the reasoning. I am toying with the idea of making some kind of opt-in transparent layer, but I am not yet convinced this is a good idea. Feedback is always appreciated.

> and I'm unable to use modifiers combined with the arrow keys.

You need to define a nested layer which explcitly specifies the modifiers of interest. Since this seem to be a common use case I have added an [example](https://github.com/rvaiya/keyd/blob/master/examples/nav-layer.conf) to examples/.

> f = overload(extend, f)

This is probably a bad idea without a timeout. You will end up with a lot of accidental layer activations. You probably want something like `overload(extend, f, 200)`, but I would advise against even this. If you are interested in overloading your homerow keys then I would advise you to read through #34 (and perhaps reconsider ;)).

**Comment by rvaiya** [comment]
I eventually came to my senses and made this the default behaviour. See the man page for details :).
