### ISSUE TITLE
External keyboard

### ISSUE THREAD

**Issue by bommbo** [rvaiya/keyd#127]
When I use external keyboard, My Layouts can't be changed back.
My configuration is like that:
[ids]
*
[main]
rightalt = layer(rightalt)
[dvorak:layout]
u = volumedown
i = volumeup
o = mute
j = brightnessdown
k = brightnessup
l = play
m = nextsong
, = previoussong
...
[rightalt]
u = layout(main)
i = layout(dvorak, main)
o = layout(dvorak)

When I press rightalt & o ,  The layout is change; But when I press rightalt & u, The  behaviors of laptop' keyboard and  external keyboard are different. The layout of extenral keyboard not change back.

**Comment by rvaiya** [comment]
This is by design. Each keyboard has its own active configuration, changing one of them has no effect on the other. If you activate a key sequence which changes the layout it will only apply to the current keyboard.

**Comment by bommbo** [comment]
How to configre different keyboard? I can activate a key sequence by external keyboard,but can't be changed back by this keyboard?

**Comment by rvaiya** [comment]
I'm not sure what you mean. It should be possible to change each keyboard's layout by using the appropriate key sequence on the board of interest. That is `board a` cannot change the layout of `board b` and `board b` cannot change the layout of `board a`.

**Comment by bommbo** [comment]
My Bluetooth keyboard is not like that. It can change the layout of my laptop keyboard. But can't change back.

**Comment by rvaiya** [comment]
> My Bluetooth keyboard is not like that. It can change the layout of my laptop keyboard. But can't change back.

You don't have a way to access the rightalt layer from your dvorak layout, so your config does not actually define a way to switch layouts. You probably want something like:

```
[main]
rightalt = layer(rightalt)

[dvorak:layout]
rightalt = layer(rightalt)

[rightalt]

```

> When I press rightalt & o , The layout is change; But when I press rightalt & u, The behaviors of laptop' keyboard and external keyboard are different.

This is expected behaviour unless you also press `rightalt+o` on the internal board. As mentioned above, each keyboard has its own state, so changes to one should not affect the other.

>  The layout of extenral keyboard not change back.

This is probably because your config doesn't do what you think it does. My suspicion is that fixing your config will solve your problem.

**Comment by bommbo** [comment]
think you!!!!
