### ISSUE TITLE
How would you go about making a modifier key switch layers while still being held down? 

### ISSUE THREAD

**Issue by Kommynct** [rvaiya/keyd#13]
I am using keyd to turn my Dvorak into qwerty when ctrl is held, so far I've been doing it by manually making, for example

A=C-a

But there has to be some way to make left Ctrl be left Ctrl AND switch the layers so I can just hold leftctrl and have that switch to qwerty while held. 

Thanks for any help!

**Comment by rvaiya** [comment]
If I understand you correctly, what you have described is the best way to
achieve what you want. E.G

    echo "[qwertycontrol]" >> /etc/keyd/default.cfg for c in {a..z}; do
echo "$c =

    C-$c"; done >> /etc/keyd/default.cfg

I'm not sure having a dedicated option to both switch layers and activate
control makes sense since you have to explicitly define layouts anyway.

Having said that, there are some issues with this approach. Namely the layer
key doesn't emit control when held (which makes control clicking
impossible).
This is a common shortcoming of most remapping tools by virtue of the way
layers work (only emitting the modifiers after a key has been activated to
allow for different modifiers within a layer).  I intend to address with the
concept of 'modifier layers' in an upcoming patch but it doesn't directly
affect your use case. The best way to achieve what you want will still be to
explicitly remap the alphabetic keys as above.

**Comment by rvaiya** [comment]
If I understand you correctly, what you have described is the best way to achieve what you want. E.G

    echo "[qwertycontrol]" >> /etc/keyd/default.cfg 
    for c in {a..z}; do echo "$c = C-$c"; done >> /etc/keyd/default.cfg

I'm not sure having a dedicated option to both switch layers and activate control makes sense since you have to explicitly define layouts anyway.

Having said that, there are some issues with this approach. Namely the layer key doesn't emit control when held (which makes control clicking impossible).  This is a common shortcoming of most remapping tools by virtue of the way layers work (only emitting the modifiers after a key has been activated to allow for different modifiers within a layer).  I intend to address with the concept of 'modifier layers' in an upcoming patch but it doesn't directly affect your use case. The best way to achieve what you want will still be to explicitly remap the alphabetic keys as above.

**Comment by Kommynct** [comment]
Hmm, yeah, I need it to be control while held unfortunately, for that to work properly.

Excited for the modifier layers feature! thanks!

**Comment by rvaiya** [comment]
I thought about this a bit more and decided it warranted a dedicated feature. Give the latest version a try.

**Comment by rvaiya** [comment]
Did this address your problem? What you want should be achievable by including `layout(dvorak, main)` at the top of your config file.

**Comment by Kommynct** [comment]
So sorry missed the last notification. I'll be checking this tonight, you're awesome thanks!

**Comment by rvaiya** [comment]
No worries. Let me know how it goes.

Thanks

**Comment by rvaiya** [comment]
Closed due to inactivity.

**Comment by Kommynct** [comment]
Okay, it took me forever to get back to you as the laptop I was using to test this wasn't in my possession, I think I'm doing something wrong. 

Right now, I have the default set to convert qwerty buttons into Dvorak,

So it starts with q = apostrophe and so on

So, I assumed you assumed qwerty was the first mode, and made leftCtrl = layout(main, qwerty)

Do I have this wrong? Am I missing something?

https://pastebin.com/gyxdVx78

Default.cfg here

**Comment by rvaiya** [comment]
The config format has changed substantially. See the changelog and manpage for details. It is best to forget everything you know. There are several problems with your config, I believe what you want is something like [this](https://gist.githubusercontent.com/rvaiya/5c17cc6026e860260904ee610ffa18c0/raw/90bd23abc42ae7e521ee8fadd26bf154cbe4d6da/default.cfg), assuming I have interpreted your intentions properly. See the man page for more details. If you feel something is missing or poorly documented please let me know.

**Comment by Kommynct** [comment]
Okay, having tested out your config it works perfectly thank you so much for the hard work I really appreciate it!

There's one minor thing left I wanted to tweak, in my window manager, all my keybinds are setup for dvorak, which means when in qwerty mode, i'd like the alt and super keys to always give the dvorak bindings, is that doable ontop of this? I've read the man pages and don't see an obvious method, that would completely perfect my config and i'd really appreciate it

**Comment by rvaiya** [comment]
>  when in qwerty mode, i'd like the alt and super keys to always give the dvorak bindings

The layout function accepts the modifier layout as the second parameter. If you want to make dvorak the modifier layout and qwerty the second simply use `layout(main, dvorak)` instead of `layout(dvorak, main)`.

If you want this only to apply to the alt and super keys you will have to explicitly define the layers. 

E.G

```
[myalt]
s = A-o
```

The modifier layout applies to all modifiers. It is implemented this way to avoid ambiguity in the case of modifier combos (e.g should `A-C-s` be `A-C-o` or `A-C-s`?).

**Comment by LilithhhBlackkk** [comment]
This feature is broken in the V2, I have the same configuration as him, is there any other way to do it? Thank you so much. 
I've enclosed the previous configuration.[](https://pastebin.com/AUgLd7Mx)

**Comment by LilithhhBlackkk** [comment]
This feature is broken in the V2, I have the same configuration as him, is there any other way to do it? 

As it currently stands I would have to setup a layer and define every single possible modifier combination, is there no simpler way?

Thank you so much.[](https://pastebin.com/AUgLd7Mx)

**Comment by rvaiya** [comment]
Unfortunately this has been removed from v2 in favour of explicit remapping. My advice would be to take better advantage of the flexibility afforded to you by layers. 

If you are going to invest in learning an alternate layout you may as well invest some time in developing a custom set of shortcuts.  Each modifier needn't apply to a single key so you can do things like map `capslock+i` to `C-S-M-i`.  You can also take advantage of application specific remapping to maximize using of your realestate (e.g `capslock+i` is `C-S-i` in chrome and `C-tab` in your terminal).

Having said that, it should be fairly easy to programmatically generate dvorak bindings. Here is one liner that generates control keys for dvorak. Most applications only bother with `[control]` and `[alt]` anyway so the additional bindings shouldn't add that much overhead to your config.

E.G

	echo "[control]"
	for f in {a..z}; do echo "$c = C-$c"; done
	echo "[alt]"
	for f in {a..z}; do echo "$c = A-$c"; done
	# etc...

If you still feel strongly about the removal of this feature, feel free to create another issue and I will consider its reintroduction if you can provide a persuasive case.

**Comment by Kommynct** [comment]
So, yeah, i've been banging my head against this for a while, and was really hoping that wasn't the solution because what about instances with multiple modifiers? if I was to hit shift, THEN control and hit a modifier, it would just not work... as it would've switched to the shift layout instead of the ctrl+shift layout, correct? This seems... extremely inelegant compared to the previous way of handling things. Am I missing something?
