### ISSUE TITLE
Switch to other layout only while certain key is pressed

### ISSUE THREAD

**Issue by motorailgun** [rvaiya/keyd#137]
First thanks for this tool! This's working very well.

Currently I'm using config like this:

```
[ids]
*

[main]
henkan = overload(navs, henkan)

[navs]
i = up
j = left
k = down
l = right
p = backspace
u = home
o = end
semicolon = enter
h = pageup
n = pagedown
```

This works well. But with this config, Shift-Henkan-J or Henkan-Shift-J doesn't do anything. Yes it is possible to do this by adding like this:
```
leftshift = layer(shift-nav)

[shift-nav]
i = S-up
j = S-left
....
```
But the problem is that I want to use Ctrl-, Ctrl-Shift-, Shift-, and Alt- key combinations with this. I guess, in this case layouts rather than layers are suitable. So I'd love to see if we can have some functions which switches layout only during the key is held.

Sorry for my bad English...

Best Regards,

**Comment by rvaiya** [comment]
> Yes it is possible to do this by adding like this:
> [navs]
> i = up

This is indeed the currently recommended approach. I would argue it's not too much additional effort in this case.  See #103 for a related issue and the rationale behind the current design decision.

> But the problem is that I want to use Ctrl-, Ctrl-Shift-, Shift-, and Alt- key combinations with this.

Do you really need `Ctrl-Shift-pagedown`? If you think about the number of key combinations you actually use you will probably find it is much smaller than you originally anticipated. Remember that you can do whatever you want in your `shift-nav` layer, so you are free to do `C-pagedown` instead of `S-pagedown` if you need it. In general I've found it is better to think in terms of useful bindings than worry about trying to replicate every possible modifier combination. Having said that, it should still be possible to do this if you really want by defining the appropriate layers (see #119 for an extreme example of this).


> Sorry for my bad English...

No need to apologize, you are perfectly intelligible :).

**Comment by motorailgun** [comment]
Thanks for a quick reply!
While I think what you say is right(yup I think I don't need `Ctrl-Shift-PGDN`), there were many key combinations with Meta- and Meta-Alt- + Arrow keys.
But I think I was misunderstanding the problem: it is possible to map ctrl to leftctrl! So I solved the problem like this:
```
[navs]

leftcontrol = leftcontrol
leftshift = leftshift
leftmeta = leftmeta
leftalt = leftalt
i = up
j = left
k = down
l = right
p = backspace
u = home
o = end
semicolon = enter
h = pageup
n = pagedown
```
This doesn't look good but works so well! Again, thank you for this great tool!
Closing as solved, have a good day :D

**Comment by rvaiya** [comment]
> It is possible to map ctrl to leftctrl! So I solved the problem like this:
> ...


The problem with this approach is that it is order dependent (you must always press `henkan` before control). If you want to achieve something that is order indepdent then you need to do something like this:

```
[control]
henkan = layer(control_henkan)

[henkan]

control = layer(control_henkan)

[control_henkan]
j = C-left
k = C-down
```

Which brings you back to where you started. If order doesn't matter to you then your config is fine.
