### ISSUE TITLE
Multi-language window title

### ISSUE THREAD

**Issue by shungo27** [rvaiya/keyd#144]
![ss](https://user-images.githubusercontent.com/7065076/155869649-f27b198d-2335-435b-a79f-3dee6d9b5007.png)
Currently, Application support's window title only support alphabets. I'm not a programmer, so I think it's incomplete, but I thought of a multi-language version. in addition regular expressions to make the match more flexible.

line 53
```
- a = line[1:-1].split('|')
+ a = line[1:-1].split('|', 1)
```

line 342
```
- if fnmatch(cls, cexp) and fnmatch(title, texp):
+ if fnmatch(cls, cexp) and re.match(texp, title):
```

line 351
```
- return re.sub('[^A-Za-z0-9@:/?.]+', '-', s).strip('-').lower()
+ return re.sub('[^[:ascii:]A-Za-z0-9@:/?.]+', '-', s).strip('-').lower()
```

keyd 2.2.6-beta

**Comment by rvaiya** [comment]
Thanks. I believe this should be fixed in the latest commit.

**Comment by shungo27** [comment]
Why use fnmatch instead of re.match for window titles?

re.match is more flexibility.

example: Layer that matches filechooser
```
[*|(save-as|open|all-files|import|export)]
```

**Comment by rvaiya** [comment]
Mainly because it makes parsing more difficult (`[`, `|` and `]` are all valid regex characters) and also because I didn't think it would be useful in most cases. The end result also looks a bit cleaner (though this is subjective).

I can see the utility of it in the example you have listed, though if the number of bindings is small enough I would just create a separate section for each title. If it bothers you enough or you frequently run into this problem I might consider adding some kind of hybrid to allow for alternation.

**Comment by shungo27** [comment]
Ok. Create a section for each title.

**Comment by rvaiya** [comment]
To clarify, I am not proposing a modification. I simply meant that you should define a dedicated section for each set of bindings. If you have a lot of bindings like this then I am willing to consider adding an alternation character.
