### ISSUE TITLE
Support for modifying timings?

### ISSUE THREAD

**Issue by NickSeagull** [rvaiya/keyd#15]
Hello, first of all, thanks for the project, it steps up the usability and automation scene in Linux a lot!

I was wondering if it would be possible to add support to configure the timings that `keyd` uses in order to consider when a key is held or not.

There's a similar tool for MacOS called Karabiner, and it let's you configure the following parameters:

```edn
:alone   80 ; hold for .. ms to register single tap
:held    50 ; If it has been held for this time and no other simultaneous key has been pressed, it considers this as a tap 
:delay   0  ; time after which the key press is delayed
:sim     30 ; keys need to be pressed within this threshold to be considered simultaneous
```

I'm trying to migrate my MacOS workflow to my Linux machine, but currently I'm having trouble due to this, as I use regular keys to enable layers. 

For example: holding `space` enables the symbols layer, so I can press `space + t` and it will act as the `=` key, but with the current timings of `keyd` it makes very difficult to type, as I have to pause in order to type words, as space is constantly triggering the hold if I type too fast.

I'd really love to get this into `keyd` and of course, I'm volunteering to try implementing it myself, I just would need some guidelines on where to start.

Thanks again!

**Comment by rvaiya** [comment]
> :alone   80 ; hold for .. ms to register single tap
> :held    50 ; If it has been held for this time and no other simultaneous key has been pressed, it considers this as a tap 

It is not clear what the difference between these is.

> :delay   0 ; time after which the key press is delayed

Can you clarify what this means?

:sim     30 ; keys need to be pressed within this threshold to be considered simultaneous

By which I assume you mean to say that if the overloaded key is struck and another key is struck within a period of 30ms then the secondary function of the first key (e.g activating control) is not activated and it instead behaves as though it were tapped (e.g space).

> I'd really love to get this into keyd and of course, I'm volunteering to try implementing it myself, I just would need some guidelines on where to start.

It's not so much the implementation that is the problem as the maintenance.  Adding these sort of configurable timeouts introduces a lot of additional state and needs to be carefully implemented so that it doesn't interfere with the core logic. It can also produce non intuitive behaviour (e.g if I hold my capslock key too long and then release it, it doesn't behave as escape), so it would have to complement rather than replace the existing sequence based tap detection.

For what it is worth the first iteration of keyd had similar timeouts in service of achieving usable home row modifiers. I even tried combining timeouts with a sequence based approach to improve usability (e.g distinguishing between `<key1 down> <key2 down> <key2 up> <key1 up>` and `<key1 down> <key2 down> <key1 up> <key2 up>` to try and divine the user's intent). While I was able to improve performance I ultimately concluded that it was impossible to achieve an implementation which completely eliminates accidental keystrokes without negatively affecting typing speed.

Having said that, overloading the space key was one of my more successful experiments. I suspect it has something to do with the frequency and speed at which the spacebar is struck. I had similar success with the backspace key.  This was some years ago, so I don't remember the precise details, but my experiments made it clear that different tap detection mechanisms were desirable depending on the usage pattern of the key.

I'm still unconvinced that supporting a multitude of timeouts is worth the effort given the complexity and limited utility, but if you can furnish your own experience with overloading the space key in particular and the kind of detection that works best, then I am open to considering adding such a feature. 

I should note that I am about to release a fairly major patch and would prefer to implement any such functionality after that has achieved stabliity.  You may also want to try kmonad in the meantime.

**Comment by NickSeagull** [comment]
> :alone 80 ; hold for less than .. ms to register single tap
> :held 50 ; If it has been held for this time and no other simultaneous key has been pressed, it considers this as a tap

These two define the following:
* alone: If I press the key for less than 80ms, it will be a tap, if more, it is a hold
* held: If I didn't perform a chord in 50ms, it will go back to tap. E.g. I press space for more than 130ms, it will register as a space tap

> :delay 0

This is a config to allow giving the keypress some delay after it has been registered. E.g. I configure this to 1000ms, and the "virtual press" performed by the program will be done 1 second after the keypress has been registered.

---

Anyways, thanks for the pointers and your concerns, I'll wait for the patch you're mentioning, and in the meantime I'll try kmonad

**Comment by rvaiya** [comment]
> alone: If I press the key for less than 80ms, it will be a tap, if more, it is a hold
> held: If I didn't perform a chord in 50ms, it will go back to tap. E.g. I press space for more than 130ms, it will register as a space tap

Thanks for the clarification. Do you find one more useful than the other? The first one looks like it would introduce undesirable visual latency and the second looks like it would cause a lot of misfires.

> :delay 0
> 
> This is a config to allow giving the keypress some delay after it has been registered. E.g. I configure this to 1000ms, and the "virtual press" performed by the program will be done 1 second after the keypress has been registered.

Can you explain the utility of this?

> Anyways, thanks for the pointers and your concerns, I'll wait for the patch you're mentioning, and in the meantime I'll try kmonad

I just release 0.1.0 which introduces some major changes, though it doesn't involve any timeout logic.

**Comment by rvaiya** [comment]
If you are still interested, the latest commit adds some limited support for timeouts.

**Comment by rvaiya** [comment]
I'm closing this for now, but feel free to chime in on #34.
