### ISSUE TITLE
Some gnome programs ignore certain key sequences

### ISSUE THREAD

**Issue by flynx** [rvaiya/keyd#150]
The following two specifications behave differently for short key press:

    sysrq = S-f10

and

    sysrq = overload(somelayer, S-f10)
  
  
The first case works as expected (shows context menu in GNOME) while the later does not.

Running via `sudo keyd -m` in both cases yields the same results, but it appears that the timings are a bit different, the first case prints the four lines visibly sequentially while the second instantly.

### Expected behavior:

Short presses should be identical in both cases.

**Comment by rvaiya** [comment]
Looks like a weird race condition in Gnome. You can reproduce it if you hit `shift+f10` fast enough without keyd. `macro(leftshift+f10)` seems to work consistently, presumably because it releases `shift` before sending the `f10` up event. In either case you should probably file a bug there.

**Comment by flynx** [comment]
On one hand I agree, this is an odd corner-case that is mishandled in Gnome, on the other hand, this is an _inconsistency in keyd_, the same key specification should produce the same output regardless of context -- POLS.


---

P.S. As a _workaround_ `compose` seems to work (on Wayland).

P.P.S. can't seem to reproduce this outside of _keyd_ in Gnome under Wayland, and I confirm that firefox an other non-clutter apps seem to handle things correctly in both cases.

**Comment by flynx** [comment]
Simple, I expect the following two lines to behave in an identical manner for a short key press...

    sysrq = S-f10

and

    sysrq = overload(somelayer, S-f10)

If the issue wound have been exclusively with Gnome then both lines would either work, not work, or a more common symptom for _races_ they both would intermittently work or break....

As I see the situation now, the first line _always_ works while the second _never_ works, and this is an inconsistency... and as a result this inconsistency affects how Gnome handles input.

...since in both cases the output is `S-f10` this means that there is some other difference and most likely it is in either how the sequence is outputted or something on the borders of this output (less likely).... I didn't dive into the source yet but if I had to guess I'd say that the reason here is in that either the output is generated/triggered in two different ways/places or the context is different affecting the output configuration, timings or sequence.

**Comment by rvaiya** [comment]
> Simple, I expect the following two lines to behave in an identical manner for a short key press...

From the perspective of non broken software they *do* behave identically. If Gnome is doing something pathological by requiring additional timeouts between key strokes then that is a bug in Gnome.

> From If the issue wound have been exclusively with Gnome then both lines would either work, not work, or a more common symptom for races they both would intermittently work or

No. If Gnome has a race condition then the two will not necessarily produce the same end result (though they _will_ produce identical output sequences, these are not necessarily the same thing). keyd makes no guarantee to the user about timing between keystrokes (unless they are explicitly specified in a macro).  If the race happens to win because of some processing in keyd which happens to take additional microseconds in one case, it is still a bug in Gnome.

> As I see the situation now, the first line always works while the second never works, and this is an inconsistency... and as a result this inconsistency affects how Gnome handles input.

Correct. Because Gnome is broken.

> ...since in both cases the output is S-f10 this means that there is some other difference and most likely it is in either how the sequence is outputted or something on the borders of this output (less likely).

This is not the case as evidenced by the output of `keyd -m`. The output sequences are indeed identical.

> didn't dive into the source yet but if I had to guess I'd say that the reason here is in that either the output is generated/triggered in two different ways/places or the context is different affecting the output configuration, timings or sequence.

They are two different code paths because they are two different features. There is no sense in plumbing the depths of keyd to figure out why some paths involve additional microseconds of processing to account for a race condition in Gnome. The output is identical if you tap the assigned key (assuming the supplied layer has no attached modifiers). 

It would probably be possible to 'fix' this by adding artificial timeouts to sequences, but I am loath to do this just to accomodate Gnome's buggy behaviour. Users can use the workaround suggested in my earlier post and lobby for Gnome to be fixed in the meantime (though my understanding is that the underlying toolkit has been retired).

**Comment by flynx** [comment]
I see you _like_ Gnome -- it some regards I would 100% agree, in others, lets just say that so far it's the _least bad_ option I've found, so far =)

I'm not defending Gnome, as soon as I figure out a way to reproduce this effect preferably on a script level and without _keyd_ or other external dependencies I'll put together a bug report...
BTW if you have a workable way to reproduce this effect outside of keyd this would speed things up as I'm not setup right now for HID development, I'm just trying to standardize the keyboard layout across all the operating systems I'm using right now.

> They are two different code paths because they are two different features. There is no sense in plumbing the depths of keyd to figure out why some paths involve additional microseconds of processing to account for a race condition in Gnome. The output is identical if you tap the assigned key (assuming the supplied layer has no attached modifiers).

It's more a question of architecture, I tend to design software in a way where each action is done in one place and in in one place only, be it a normal function an inline or a macro, this saves me or the team allot of work keeping the code in sync, removes a whole category of potential bugs, and keeps the secondary side effects to the absolute minimum.... and that's what I'm pushing towards here =)

> It would probably be possible to 'fix' this by adding artificial timeouts to sequences, but I am loath to do this just to accomodate Gnome's buggy behaviour. Users can use the workaround suggested in my earlier post and lobby for Gnome to be fixed in the meantime (though my understanding is that the underlying toolkit has been retired).

Since the original code path works quite nicely I'd simplify things and just call that, I'm still talking without taking a look at the code though and things could be a bit more complicated in reality... I am getting more and more curious, but so far I've still been keeping myself out, as usually me diving into someone else's code leads to some side-effects of its own... but if I have not convinced you, I think that keyd is a good enough project to invest some time into))))

**Comment by rvaiya** [comment]
> I'm not defending Gnome, as soon as I figure out a way to reproduce this effect
> preferably on a script level and without keyd or other external dependencies
> I'll put together a bug report...

It might be worth reading this first:

https://blogs.gnome.org/clutter/

> BTW if you have a workable way to reproduce this effect outside of keyd this would speed things up as I'm not setup right now for HID development, I'm just trying to standardize the keyboard layout across all the operating systems I'm using right now.

It should be enough to observe that this problem does not occur in non-clutter based programs like firefox. If you don't trust the output of `keyd -m` for some reason (it just reads the input devices directly) you can observe the same event sequence higher up the input stack using `xev`.

E.G

	xev|awk -F '[,)]' '/Press/{p++};/code/{print $3 " " (p ? "up" : "down");p=0}'

It shouldn't be too hard to clobber together a minimal example to reproduce the issue, though I don't have the time at the moment.

> It's more a question of architecture, I tend to design software in a way where
> each action is done in one place and in in one place only, be it a normal
> function an inline or a macro, this saves me or the team allot of work keeping
> the code in sync, removes a whole category of potential bugs, and keeps the
> secondary side effects to the absolute minimum.... and that's what I'm pushing
> towards here =)

I generally agree with this philosophy, and it is indeed one of the design goals of keyd. However that has to be balanced against accomodating quirks in every piece of broken software.  I am not opposed to adding timeouts to sequences in order avoid similar bugs if they are sufficiently prevalent, or affect a large number of users, but I generally hold the view that things like this should be fixed upstream in the appropriate project.

> Since the original code path works quite nicely I'd simplify things and just call that.

The fact that that this works at all on your system (on mine the results are identical) is incidental. Trying to fix a race condition in a Gnome toolkit by modifying keyd's internal logic to shave off microseconds (on your system) would be akin to preventing your toddler from sticking his hand in the electrical socket by chopping off his fingers.

> I'm still talking without taking a look at the code though and things could be a bit more complicated in reality.

The fix for this is trivial, the implementation is not the issue.

**Comment by flynx** [comment]
> but I generally hold the view that things like this should be fixed upstream in the appropriate project.

We are looking at this from two different perspectives, I understand your point of view but mine differs a bit in the details, I see this as two separate issues, one a slight inconsistency in keyd and the other is a buggy behavior in Gnome and both should be addressed...
I might be a bit overly pedantic here but working both as an author and consulting on other projects I almost fanatically (given there are no larger issues) try to fight anything that can lead to identical inputs producing _slightly_ different outputs, especially if such an issue actually surfaced, mainly because after such inconsistencies get built upon and covered by a layer or two they become extremely difficult to track down and fix without the whole chain falling apart and the more subtle they (issues) are the harder they are to track down and fix later....

> ... adding timeouts

This _feels_ a bit too hacky, unless the timeouts are added consistently to all cases, I think the solution here is simpler, but I've just finished the first read through the code, still need to experiment a bit, so this opinion might still change....


---

BTW, here's the first of the _"diving into someone else's code leads to some side-effects of its own"_, a general _theory of operation/architecture_ and a _source map_ would greatly benefit onboarding, keyd is small enough for this not to be a big issue, but still its spending 10 minutes reading the docs vs 50 minutes orienting one's self scanning the source....

BTW №2 as to the new title, I did not say that Gnome _ignores_ the key sequence, it's a funnier than that,  Gnome actually misinterprets the sequence, it appears that the app actually gets some escape-sequence-ish thing, but I did not investigate the issue further as that was higher up the level -- If we were talking about a hardware-level implementation I'd guess that it's a timing issue and two HID packets got treated as one (a-la packet/buffer overflow), but this should be higher level than that  =)

**Comment by rvaiya** [comment]
> one a slight inconsistency in keyd and the other is a buggy behavior in Gnome.

I'm not sure what the 'inconsistency' in keyd would be given that the problem is a consequence of a race condition which causes Gnome to ignore event order.

> I try to fight anything that can lead to identical inputs producing slightly different outputs

The inputs _are_ identical, unless you consider time on the order of microseconds an input. No sane piece of software should change the meaning of `<shift down> <f10 down> <f10 up> <shift up>` based on time.

> ... adding timeouts
> 
> This feels a bit too hacky, unless the timeouts are added consistently to all cases, I think the solution here is simpler, but I've just finished the first read through the code, still need to experiment a bit, so this opinion might still change....

The problem is inextricably linked to time. I agree that adding artificial timeouts to fix broken clutter's broken input procesing is 'hacky', but that is precisely what you are (indirectly) proposing. If you have a 'simpler solution' that doesn't involve timeouts (implicitly or otherwise) I would very much like to hear what it is.

**Comment by flynx** [comment]
Yes, time is key here)

> unless you consider time on the order of microseconds

That is exactly what I'm talking about, but not directly, my gripe is with the inconsistency and not with it's size, if one piece of software is slow enough to miss or misread an event then by definition this timings inconsistency is significant (regardless of the quality of that software).... this is exactly the reason why debounce logic exists (both software and hardware), why there is a "minimum" length requirement on some cables, trace lengths are matched on PCBs, ...etc.


> The problem is inextricably linked to time. I agree that adding artificial timeouts to fix broken clutter's broken input procesing is 'hacky', but that is precisely what you are (indirectly) proposing. If you have a 'simpler solution' that doesn't involve timeouts (implicitly or otherwise) I would very much like to hear what it is.

The goal was to first look at local architecture and if everything on that level is in order to look at lower levels, but I'm not going into specifics yet, still need to test the idea(s)....

The problem with microseconds that are not based on specific timer events is that on some hardware they can be below the event timer resolution and on some turn into milliseconds or even longer, and even worse, mixing up microseconds in non-realtime timeouts with consecutive execution is .... different levels of race condition hell. This is exactly the reason why I'm against trying to compensate for different code path execution time with timers, it should be either consistent execution times for all code paths within a margin (on the scale of keyd this _should_ not be an issue) or timers driving execution, and in a case where the protocol requires or expects specific timings, or there could be fussy/slow clients that can't keep up or get easily confused, it may be necessary to compensate and here one can't avoid explicit timeouts...

So, to reiterate, my problem is with the inconsistency and potentially with why it exists and not with the actual timeouts, if _fixing_ this issue results in a _twisted in confusion Gnome_ in all the cases, I'm for it, it's Gnome's problem, I would then advocate for a build-configurable output timer, but that would be a different issue and discussion for the future that I'm hoping to avoid....


> Before you 'dive into the code' it might be prudent to develop a better understanding of what the problem is.

A bit too late here =)


---

P.S.

> ... that doesn't involve timeouts (implicitly or otherwise) 

Good trap!! =)

P.P.S. as a side note, this is a potential pitfall: keyd is emulating an input (HID) device, so when the key mapping is 1:1 then keyd by definition can not output faster than the actual keyboard (i.e. no faster than COM/LPT/USB(HID) packet timings) but when a key maps to a sequence it is at least 1:2 (plus delays) or more, including all the timings, and here, in the current implementation, how close the actual output rate to the _expected_ rate depends on the code path....
...on the other hand, we could also argue about problems of translating 1:2+ events like overlapping keyd output over actual key input, but humans in general are both not that fast (with a proper debounced keyboard) and do not have high enough _internal clock resolution_ to notice a key queue delay (gamers not withstanding)....

P.P.P.S. _if I'm seeing things correctly the issue with keyd is not the difference in code path execution times, it's in that one code path involves a timer and the rest are strictly consecutive... (still thinking/testing)_

**Comment by rvaiya** [comment]
> I have a suspicion that the root cause here is in that one code path indirectly includes a timeout and the rest do not...

This is patently false, as I've explained to you several times.

> Yes, time is key here.

Indeed. Here is a one line patch which solves the problem:

```
index 05e8b8e..b37f868 100644
--- a/src/keyboard.c
+++ b/src/keyboard.c
@@ -351,6 +351,7 @@ static void kbd_end_sequence(struct keyboard *kbd, const struct key_sequence *se
        uint8_t active_mods = kbd_compute_mods(kbd);

        send_key(sequence->code, 0);
+       usleep(50000);
        send_mods(sequence->mods, 0);
        send_mods(active_mods, 1);
 }
```

I do not want to apply it for reasons I have already stated.

> That is exactly what I'm talking about, but not directly.
>
> my gripe is with the inconsistency and not with it's size, if one piece of
> software is slow enough to miss or misread an event then by definition this
> timings inconsistency is significant (regardless of the quality of that

The problem is a consequence of a bug in clutter's input processing, which I've already addressed at length. Correct programs do not ignore event order on the basis of time. Modifying keyd to accommodate this would be the equivalent of underclocking your CPU to fix a race condition in your text editor.

> this is exactly the reason why debounce logic exists (both
> software and hardware), why there is a "minimum" length requirement on some
> cables, trace lengths are matched on PCBs, ...etc.

Debounce logic has nothing to do with this issue. 

> The goal was to first look at local architecture and if everything on that
> level is in order to look at lower levels, but I'm not going into specifics
> yet, still need to test the idea(s)....

This is unnecessary. I admire your enthusiasm, but it is presumptuous to assume that the code needs to be rearchitected with your assistance to fix a bug that you still do not seem to understand.

> The problem with microseconds that are not based on specific timer events is that on some hardware.

Yes, this is a classic problem with race conditions and why trying to modify keyd to fix an obscure bug in Gnome makes little sense.

> they can be below the event timer resolution and on some turn into milliseconds or even longer.

This is an exaggeration.

> and even worse, mixing up microseconds in non-realtime timeouts with consecutive execution is .... different levels of race condition hell. 

There are no timeouts involved in the default overload code path (unless you supply one).

> This is exactly the reason why I'm against trying to compensate for different
> code path execution time with timers, it should be either consistent
> execution times for all code paths within a margin (on the scale of keyd this
> should not be an issue)...  or timers driving execution, and in a case where
> the protocol requires or expects specific timings, or there could be
> fussy/slow clients that can't keep up or get easily confused, it may be
> necessary to compensate and here one can't avoid explicit timeouts...

You have not grasped the problem.

> ... that doesn't involve timeouts (implicitly or otherwise)
>
> Good trap!! =)

It wasn't a trap, I was trying to explain the problem to you since you keep making baseless assertions about the code without understanding it, and your claims would suggest you still have misapprehensions about the nature of the issue.

> P.P.S. as a side note, this is a potential pitfall: keyd is emulating an input
> (HID) device, so when the key mapping is 1:1 then keyd by definition can not
> output faster than the actual keyboard (i.e. no faster than COM/LPT/USB(HID)
> packet timings) but when a key maps to a sequence it is at least 1:2 (plus
> delays) or more, including all the timings, and here, in the current
> implementation, how close the actual output rate to the expected rate depends
> on the code path....  ...on the other hand, we could also argue about problems
> of translating 1:2+ events like overlapping keyd output over actual key input,
> but humans in general are both not that fast (with a proper debounced keyboard)
> and do not have high enough internal clock resolution to notice a key queue
> delay (gamers not withstanding)....

I do not need a sermon on input processing, given that I have written and benchmarked keyd. Most of this is self evident and has nothing to do with the problem you are trying to solve.

> P.P.P.S. if I'm seeing things correctly the issue with keyd is not the
> difference in code path execution times, it's in that one code path involves a
> timer and the rest are strictly consecutive... (still thinking/testing)

No.

I am going to close this, since it no longer seems to be productive and the issue was solved several posts ago.
