### ISSUE TITLE
Slow key repeat on mappings with modifiers

### ISSUE THREAD

**Issue by Compile-Time** [rvaiya/keyd#164]
When keys are re-mapped with modifiers the key repeat rate is effected.

This can be observed with a simple config like this:

```
[main]

a = S-a
```
![slow-key-repeat](https://user-images.githubusercontent.com/18414241/160252621-8596f1d5-2868-4337-91eb-3c46adb0ccf7.gif)

In my case I use a typematic delay of 250ms and typematic rate of 30Hz (If that matters).

**Comment by Compile-Time** [comment]
This happens since the commit `f87d356`.

**Comment by Compile-Time** [comment]
In my case this is quite an inconvenience because I re-mapped my 'ö' and 'ä' keys to be '{' and '}' 
which I did by mapping them like this:
```
# Output '{' on 'ö'
; = G-7
# Output '}' on 'ä'
' = G-0
```

Therefore, when I navigate files in a Vi-like editor it effects the speed at which I can go through 
files.

**Comment by rvaiya** [comment]
This is a consequence of the fact that key sequences are now just syntactic sugar for macros, which have an internal repeat interval. A solution to this would be to extend the config syntax to make this configurable.

**Comment by Compile-Time** [comment]
I see, I think it would be more intuitive if such "basic" mappings have a timeout of zero (aka none).

Because this feels like unexpected behavior for simply wanting a key to output a key behind a modifier.

However, I don't mind the there being an option in the config file to set the default timeout value.

**Comment by rvaiya** [comment]
> Because this feels like unexpected behavior for simply wanting a key to output a key behind a modifier.

For consistency, you would have to set a repeat interval for macros (which also applies to unicode input) anyway, since the display server doesn't know how to repeat these things on its own. The old approach was to treat key sequences as distinct from macros, but doing that adds a bit more complexity to the code for little gain (I am open to persuasion on this point).

> However, I don't mind having an option in the config file to set the default timeout value.

I've just made macro timeouts configurable (see the man page). Let me know if this solves your problem.

P.S

If you haven't already, I would recommend trying out the new unicode functionality.  It allows you assign directly to international characters, so you don't have to memorize the compose/altgr sequences:

E.G

```
u = ß
```
