### ISSUE TITLE
[ help ] keyd-application-mapper

### ISSUE THREAD

**Issue by diegodario88** [rvaiya/keyd#174]
Hi, thanks for the awesome work done here. I found it really useful. I did make my remapping and it works just fine but now I want to explore the `keyd-application-mapper`. 

What I what to achieve is (idk if it's possible) trigger different keys when I'm on my terminal emulator so when a text editor is opened inside it, it will no longer active shortcuts from the emulator.

Like, `tilix` (terminal emulator) is awake of alt+up for alter terminal windows but in my `micro` (terminal text editor) I want to use that shortcut to do something else. Could you point me on the right direction?

**Comment by rvaiya** [comment]
`keyd-application-mapper` can be used to change the active keymap depending on the current window. It is only useful for graphical applications. If I understand you correctly, you want `alt+up` to behave differently in some terminal programs, but still affect tilix when you are in a pane in which those programs are not running. 

In order to achieve this you will need some way to determine when the terminal program is running, as well some way to detect which pane you are in. The former can be achieved with a simple hook or wrapper script which calls `keyd -e`, but the latter will probably require you to write some tilix specific detection code. Personally, I would just have a dedicated layer for common GUI tasks since overloading your terminal navigation key with your text editor seems like a bad idea. Having said that, you could probably more easily achieve this using tmux (even without keyd.

**Comment by diegodario88** [comment]
Got it!
Thank you
