### ISSUE TITLE
Assistance upgrading alternate layout modifier config to 2.3.0

### ISSUE THREAD

**Issue by Kommynct** [rvaiya/keyd#179]
I've been on it for a few hours now and i'm not sure what changes i'm missing, it's saying I can only have up to 64 macros?

https://pastebin.com/hEByzD0w

I hate to ask for help again but I am just completely stuck, i've been trying to modernize this: https://pastebin.com/LX1Ca7BR

I've removed seemingly all of the old things, replaced layout with toggle, I can't make it switch to qwerty, and the control layer doesn't work at all, I just have no idea what i'm doing wrong at this point

**Comment by rvaiya** [comment]
> it's saying I can only have up to 64 macros?

Sorry, this was my fault :P. This is happening because key sequences (e.g `C-a`) are now internally treated as macros. I was a bit stingy with the original limit since I was trying to conserve memory, but increasing it makes sense given that they are now used for both sequences and unicode input.

>  I can't make it switch to qwerty

Layers are now much simpler than they used to be. `2.3.0-rc` was a major release. It is best to forget everything you knew about the beta and reread the manpage (see also the changelog). Conceptually layers are just stackable keymaps, so if you want to define what used to be called a `layout` you put it in a layer and then activate it.

E.G

```
[main]
rightshift = toggle(dvorak)

[dvorak]
s = o
..
```

Will cause rightshift to toggle between qwerty and dvorak. Note that here we are relying on the default behaviour of `main` in which each key is assigned to itself. 

A consequence of this is that iff you want to make the default layout dvorak then you will need to define it in `[main]` and create a dedicated qwerty layer in which each key is assigned to itself.

E.G

```
[main]
rightshift = toggle(qwerty)
s = o
...

[qwerty]
a = a
b = b
```

**Comment by Kommynct** [comment]
Thank you so much for the breakdown, finalized config here incase anyone wants it

https://pastebin.com/raw/0uaGd3Hq
