### ISSUE TITLE
setxkbmap and xset are resetting after restarting keyd

### ISSUE THREAD

**Issue by sarmong** [rvaiya/keyd#183]
I have the following configuration set:

```
## Sets keyboard layout
setxkbmap "us,ru"

## Increases key repeat rate
xset r rate 250 45
```

After I run `systemctl restart keyd`, both settings get reset and I need to rerun these commands again.

Keyd version `v2.3.1-rc (8f0727c)`

**Comment by rvaiya** [comment]
This is a consequence of the fact that X utils don't account for hotplugging. Restarting the daemon is the equivalent of unplugging and replugging the . My advice would be to do all your remapping in keyd using the new unicode support

E.G

```
[russian]
q=й
w=ц

[shift+russian]
q = Д
```
and then set `macro_repeat_timeout`

**Comment by sarmong** [comment]
Are there any benefits to this setup? Or potential problems with using setxkbmap?

Currently I have basically oneliner to set Russian layout and a command to switch it. Writing every single key seems a bit tedious and overcomplicated;) 
Besides, I have to rerun my keyboard script after restarting keyd anyway, to get the `xset` setting

**Comment by rvaiya** [comment]
> Are there any benefits to this setup?

It provides a centralized place to define all your bindings and allows you to more easily customize your layout. Using X utils in conjunction with keyd is generally not recommended, with the possible exception of your keymap. Unicode support is still fairly 

> Writing every single key seems a bit tedious and overcomplicated;)

Someone had to do it for X too ;).

> Besides, I have to rerun my keyboard script after restarting keyd anyway to get the xset setting

This is true for non-macro/unicode keys, but you will have to modify `macro_timeout` anyway if you want your repeat intervals to match, since the display server doesn't know how to handle macros.

**Comment by sarmong** [comment]
@rvaiya Is it no longer the issue? I don't need to restart setxkbmap and xset?

**Comment by rvaiya** [comment]
Unless something has changed on the X/xkb side, I believe this is still an issue. The only way to solve this issue is to implement some kind of hot reloading which doesn't recreate the virtual device, but I'm not convinced this is worth the additional effort.

It is worth noting that `keyd -e` can be used for experimentation without requiring a restart, but once you find something you are happy with and add your changes to the config file you will have to rerun `setxkbmap`. Alternatively you should be able to change these settings in your X config, which I believe will make them persistent.

**Comment by rvaiya** [comment]
> Can then language layouts be defined inside keyd? I can contribute for Russian and Ukrainian layouts.

I've added support for file inclusion to the config format and shipped keyd with some includeable layout files. I generated them from the corresponding xkb layout files so there may be some warts. I would appreciate any feedback/corrections.
