### ISSUE TITLE
Ignore additional modifiers if they not in config

### ISSUE THREAD

**Issue by antontkv** [rvaiya/keyd#186]
I have this config for example:
```bash
[alt]
h = left
l = right
j = down
k = up
```
When pressing alt+h it will produce left key and so on. But when I use control+alt+h it will also produce control+left key. How can I make it do control+alt+h and not control+left? It was working before, but after updating to latest commit, it's not.

**Comment by antontkv** [comment]
As I read more I understand that this is by design in 2.3.0.

> Modifiers now apply to all bindings with the exception of modifiers associated with the active layer.
>
> The end result is more intuitive and in conjunction with transparency allows modifiers to be paired with layer entries without having to use layer nesting.

But for me as a user this is not intuitive and brought some confusion. You see I expect the config only do what I asked it to do.

If I want alt+hjkl to behave like motion keys and any other combination of alt+key to behave normally I will use this config:

```
[main]

[alt]
h = left
l = right
j = down
k = up
```
And I expect it to change only the alt layer, because I told it to do only that. I expect any other combination of modifiers(alt+control, alt+shift) to behave normally. Again, because I didn't asked keyd to change them, only the alt layer.

Then if I want also to change behavior of alt+shift, I will use this config:

```
[main]

[alt]
h = left
l = right
j = down
k = up

[alt+shift]
# Select left right up down
h = S-left
l = S-right
j = S-down
k = S-up
```

And again I expect keyd to change only this layer and don't touch any other combination (alt+shift+control, etc), because I didn't asked it to do it.

It brought confusion, because now it interference with some programs hotkeys and with system hotkeys. For example, I have this in my config:

```
[alt]
# Direction keys with alt pressed.
w = A-up
s = A-down
d = A-right
a = A-left
``` 

And I set up control+alt+d and control+alt+a hotkeys in my system to open curtain programs. Now this hotkeys won't work because I'm not pressing control+alt+(d|a), I'm pressing control+alt+(left|right). To mitigate that now I have to add this to my config:

```
[alt+control]
d = A-C-d
a = A-C-a
```

As a heavy user of AHK on Windows, it's confusing and not intuitive to me. Mainly because AHK is programing (scripting) language, and as from any programing language I expect it to do only what I asked it to do.

I ask you to reconsider this behavior of keyd and also treat it's configuration files as programming language, that it only should do things that user asked it to do.

**Comment by slakkenhuis** [comment]
I disagree that this is less intuitive behaviour --- in fact, it is far more intuitive to me. 'Remap when this modifier is pressed, but undo it if another modifier is also pressed' should require more effort than 'apply when this modifier is pressed', no? Having to explicitly specify that (as you have done) seems reasonable

**Comment by antontkv** [comment]
Yes, I understand that it's may be different for other people. It's just that this behavior broke my system hotkeys, and I didn't ask keyd to change any other layer except alt and alt+shift. More broad approach for this may be to include option in `[global]` to disable transparent layers.

**Comment by rvaiya** [comment]
Thanks for the detailed feedback. I appreciate that you took the time to read and engage with the rationale for the changes.

> If I want alt+hjkl to behave like motion keys and any other combination of
> alt+key to behave normally I will use this config:

> And I expect it to change only the alt layer, because I told it to do only
> I expect any other combination of modifiers(alt+control, alt+shift) to
> behave normally. Again, because I didn't asked keyd to change them, only the
> alt layer.

This is one way to look at it, but the approach taken by keyd is that `alt` itself just another layer. Its intrinsic meaning is altered when you redefine a key within it. This applies to all modifiers. 

More instructively:

```
[shift]

/ = \
```

will change the *meaning* of `S-/` from `?` to '/'.  If you regard `shift` itself as a layer, then a natural consequence of this is that `C-S-/` becomes 'C-\', rather than 'C-?'.

Conceptual coherence aside, there are also practical reasons for the change.  The number of people who implicitly made the opposite assumption (that modifiers *should* apply to layer bindings) seems to greatly exceed those who assumed layers are hermetically sealed, as evidenced by the number of issues pertaining to modifier nesting after the release of the v2 beta.

A consequence of the change is that the second group will now have to make their intentions more explicit than the first.

> And I set up control+alt+d and control+alt+a hotkeys in my system to open
> curtain programs. Now this hotkeys won't work because I'm not pressing
> control+alt+(d|a), I'm pressing control+alt+(left|right). To mitigate that now
> I have to add this to my config:

One could also argue that you are actually pressing `C-left` since `A-a = left`.

> I ask you to reconsider this behavior of keyd and also treat it's configuration
> files as programming language, that it only should do things that user asked it
> to do.

keyd is intentionally *not* a programming language, it is a domain specific configuration language which tries to balance expressive power with the user's intuition about the problem domain. This is more art than science, since no two user's share the same set of assumptions. Having said that, I would contest that it doesn't do what the user 'asked it to do', since this is contingent on the user's mental model (I believe the technical term for this is PEBKAC :P).

Admittedly, in the process of hammering out the design some minds (my own included) may have been warped by bad initial design decisions. Though to be fair, I did mark the last few releases as beta.

**Comment by rvaiya** [comment]
> And with an option to disable transparent layers, it can look like this:

The problem with this is that it isn't obvious what the modifiers should apply to.  The old behaviour was afforded by a combination of different assumptions which no longer hold.  Notably, the old scheme had the notion of a dedicated 'layout' type, to which modifiers would apply in the absence of any bindings in the active layer.  Under the present scheme, all layers are equal and form a stack. When you combine this with the subtle ways these different behaviours interact with other features it quickly increases the maintenance burden (and creates competing conceptual models).

I would ask you to pause for a moment and consider whether or not you really want to do what you have described. 

First, do you really need access to `<mods>-h` for all combinations of `<mods>` *except* `A`?  What happens if you need to press `A-h`? Presumably you have this bound within another alt layer.  Wouldn't it make more sense to combine other modifiers with this binding, instead of the one which remaps `h` as `left`? 

Additionally, how often do you really use `A-S-M-h`?

In most software `A-h` will be used long before `A-S-h`, and in the event you need both, the incongruity between `A-h` yielding `left` and`A-S-h` yielding `A-S-h` will probably cause more confusion.

I suspect part of the reason you want to do this is to make use of the default vi-like bindings of your window manager. My suggestion would simply be to change these bindings at the level of your window manager config.  The advantage of this approach is that also allows you to make use of common text bindings like `C-left`.
