### ISSUE TITLE
How do I remap left mouse click?

### ISSUE THREAD

**Issue by 1ncend1ary** [rvaiya/keyd#190]
Hey! I want to remap `mod+left mouse click` to `ctrl+left mouse click`. How do I do that? Relevant part of config that is not working (I still get `mod+leftmouse`):
```
[ids]
*
[main]
leftmeta = layer(mycontrol)

[mycontrol:M]
leftmouse = C-leftmouse
```

Version:
```
$ keyd -v
keyd v2.3.1-rc (9325bf3)
```

I tried it with internal trackpad and with external mouse.

**Comment by rvaiya** [comment]
Unfortuantely remapping mouse buttons is unsupported (see #162).

**Comment by 1ncend1ary** [comment]
I thought I was missing something in the documentations. Thank you very much for your hard work!

**Comment by rvaiya** [comment]
No worries, I should probably make this more explicit. I have been meaning to write a FAQ at some point :P.

I also have a less polished project called moused, which I originally wrote for personal use (mainly to turn my trackball wheel into a scroll toggle for the ball), but it doesn't support remapping to arbitrary keys. I may end up fleshing it out a bit more or integrating it into keyd at some point, since there seems to be some external interest.

I'm closing this for now, but feel free to reopen it if you feel strongly about the issue.
