### ISSUE TITLE
The X that wasn't (can has command execution?)

### ISSUE THREAD

**Issue by jcorbin** [rvaiya/keyd#192]
Cheers on having a well written readme, that very quickly told me:

> ## What keyd isn't:
> A tool for launching arbitrary system commands as root.
> A tool for programming individual key up/down events.

Which was literally the one thing I was trying to find a piece of software to do (goal being to leverage a macropad to take system-level actions).

Any pointers on other software that can?

Or am I out of luck, and need to start rolling my own thing? If so, any pointers on where to start?

**Comment by slakkenhuis** [comment]
I haven't tested these since keyd covers my use case elegantly, but you might be interested in:

- https://github.com/mooz/xkeysnail
- https://github.com/kmonad/kmonad
- https://github.com/snyball/Hawck
- https://github.com/autokey/autokey
- https://github.com/shiro/map2
- https://github.com/wertarbyte/triggerhappy
- https://github.com/lmburns/lxhkd

I don't know whether they can program individual keyup/keydown events but I think these can at least call shell commands (though some are limited to X). There are others that are more limited, adding for posterity:

- https://github.com/39aldo39/klfc
- https://github.com/sezanzeb/key-mapper
- https://github.com/wez/evremap
- https://github.com/acro5piano/wayremap
- https://github.com/k0kubun/xremap
- https://gitlab.com/interception/linux/tools
- https://github.com/unrelentingtech/evscript

**Comment by rvaiya** [comment]
I would recommend just doing this at the level of your window manager (e.g `~/.sway/config`). Almost every window manager provides a mechanism to bind keys to commands, but if you *really* need something system wide I would use something like swhkd (though I haven't used it), which seems to be sxhkd using evdev.

**Comment by jcorbin** [comment]
> I would recommend just doing this at the level of your window manager (e.g `~/.sway/config`). Almost every window manager provides a mechanism to bind keys to commands, but if you _really_ need something system wide I would use something like swhkd (though I haven't used it), which seems to be an sxhkd clone that uses evdev.

Good advice, but in my case I really do need something system level:
- desktop system running a headless hypervisor os on the baremetal (proxmox)
- which boots a primary guest OS with gpu and a bunch of usb devices passed thru
- so I'd like to wire up an unused macropad, and have the host os implement keys like "boot the primary windows guest" and "boot the primary linux guest"
- those are necessarily privileged system level commands on a headless system with no logged in user session, let alone a window manager running ;-)
- doing so will arguably be a tad more secure than the current necessity of logging into an admin account on the host to issue those "boot a guest" commands...

**Comment by rvaiya** [comment]
I see. Adding this to keyd would be trivial, but I have mixed feelings about it. I suppose I could always include a security footnote about usage in the man page, but we all know how often users read those :P.

**Comment by jcorbin** [comment]
No worries, I think that between `wertarbyte/triggerhappy` and `gitlab.com/interception/linux/tools` I should have a solution that doesn't involve writing new software, and I'm especially interested in that "interception" kit as it seems able to provide virtual synthetic input devices... which would have other potential uses in my hypervisor-to-guest oriented scenario anyhow

**Comment by rvaiya** [comment]
I mulled it over and decided to add support for this. The latest release contains a `command()` action

**Comment by rvaiya** [comment]
Closing due to inacitivity. For posterity, the following is now possible:

```
enter = command(rm -rf /)
f12 = command(brightness down)
```
