### ISSUE TITLE
About leftcontrol.

### ISSUE THREAD

**Issue by bommbo** [rvaiya/keyd#214]
My configuration is that:
```
[ids]
*
[main]
space = overload(spacefn,space)
[spacefn]
w = leftmeta
h = left
l = right
```
when I type " space w h " 
keyd -m will show:
```
leftcontrol down
leftmeta up
leftcontrol up
leftmeta down
left down
left up
```
It's right ?

**Comment by bommbo** [comment]
same time.  "space w h" mean leftmeta-left. It's not my full configuration. But I just focus on "leftmeat-left"

**Comment by rvaiya** [comment]
@herrsimon is correct. I assume you want `space+w+h` (all held down) to produce `M-left`. To achieve this you should do `w = layer(meta)` instead of `w = leftmeta`. I will probably make the latter illegal at some point since it conflicts with keyd's internal modifier logic and produces undefined behaviour when paired with other keys. I am closing this for now, but feel free to reopen it if you feel your issue is unresolved.
