### ISSUE TITLE
feature request: add debug option

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#216]
as a followup to #214, it would be useful to add a debug option to keyd, which makes it emit all detected physical key events, the emitted virtual key (or mouse) events, layer change events (including the full layer stack on each such event) etc. With the exception of layer change events, monitoring such events is probably already possible via other tools, at least on linux (by hooking into uinput). If that's the case, a section explaining how to do this should be added to the documentation.

This would enable users to debug config files which result in unexpected behaviour.

**Comment by rvaiya** [comment]
There is already a debug mode which can be activated by setting `$KEYD_DEBUG`, though it is intended for internal use and isn't very verbose. The latest commit adds more verbose logging with `KEYD_DEBUG=2`, but I am loath to add a dedicated flag since users will invariably write fragile scripts around it.
