### ISSUE TITLE
Xorg input freezes

### ISSUE THREAD

**Issue by Archetypic** [rvaiya/keyd#251]
Hello,

When keyd is run, it freezes the Xorg server input, disallowing me from typing. The mouse is still recognized.

* I run keyd as root for testing purposes: `keyd` in another terminal

`/etc/keyd/default.conf`:

```
[ids]

*

[main]

shift = oneshot(shift)
meta = oneshot(alt)
control = oneshot(control)

leftalt = oneshot(meta)
rightalt = oneshot(altgr)

capslock = oneshot(control)
insert = S-insert

```

* `keyd -m` matches keys successfully as root and the normal user.

* I downloaded `keyd` through git, then `make && make install`.

* Kernel module 'uinput` is loaded.

* This input does not freeze in `tty`.

* How do I troubleshoot this?

**Comment by rvaiya** [comment]
Please post the output of the daemon and the output of `sudo keyd -m`. You should ideally be running it from your service manager (e.g `sudo systemctl start keyd`), rather than starting it manually (`sudo keyd`), but the latter is fine for debugging. The output of `xinput list` would also be useful.

**Comment by Archetypic** [comment]
My apologies,

I unwisely killed the device manager in my init script.
Leaving it alive allows `keyd` to work without issue.
