### ISSUE TITLE
Feature request: Oneshot() with timeout

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#277]
I'd like to propose an expiration mechanism for oneshot, say `oneshot2(layer, timeout)` for the sake of discussion, which behaves like oneshot but only if the next key is pressed within `timeout` ms. The naming is suboptimal, as the two at the end usually signals the ability to supply a macro to be executed (and who knows if at some point a use case warranting the introduction of `oneshot2(layer, macro)` will be found), but I couldn't come up with something better except the more cumbersome `layer_timeout`.

Repeated calls to `oneshot2()` with the same layer argument should reset the timer to the last supplied `timeout`, while any other action activating or deactivating a layer with a currently attached timer should remove this timer. Also, from an implementation perspective, it is probably a good idea to only allow a single expiring layer at a time, i.e. calling `oneshot2()` while a layer different from the one given as argument has an active timer would deactivate this other layer.

This would address the following use cases:

1. Self-deactivating (nested) leader keys

The `oneshot2()` action would allow a user to change his mind after pressing the corresponding key. Currently, “cancelling” a oneshot action without visible consequences necessitates an additional keypress (typically some modifier key). 

More concretely, I would like to toggle some layer by tapping shift twice, i.e.

```
[main]
leftshift = overload(shift,oneshot(shift))

[shift]
leftshift = toggle(layerA)

[layerA]

leftshift = toggle(layerA)
```

After testing it for a while, I temporarily removed this functionality as it often happened that I tapped shift because I wanted to start some sentence and then changed my mind. When I then wanted to continue to type and hence pressed shift again, layerA would activate, which was a bit annoying. If `oneshot(shift)` could be replaced with `oneshot2(shift, 500)`, this problem would not occur.

2. Automatically activate an expiring navigation layer while moving a trackpoint or physical mouse (QMK has a similar feature for keyboards with a builtin trackpoint/mouse, which I find very useful)

Usually, after moving the mouse one has to click somewhere. If keyd would be able to activate an expiring navigation layer (typically with the mouse buttons on the home row) while moving a trackpoint or external mouse, one could replace the physical mouse buttons by proper keyboard buttons without the need to use some additional modifier press or explicitly activating a layer.

Of course, for this functionality one would need to enable calling actions via IPC in addition (which is planned to be implemented if I'm not mistaken), so that some script could monitor for mouse move uevents and issue the corresponding `oneshot2()` call.

**Comment by slakkenhuis** [comment]
I have also thought about this, for the same use case. Its absence hasn't caused me so much grief to a feature request but I do like the idea.

>but I couldn't come up with something better

What about not changing the name at all and just have an optional argument?

**Comment by rvaiya** [comment]
How about something like `timeout2(<action>, <time>, <action>)`, where `<time>` corresponds to the time elapsed between the bound key and the next one? 

You could then implement a decaying `oneshot` like so:

`timeout2(noop, 300ms, oneshot(shift))`

It could potentially have other uses like the time based sequence logic described [here](https://github.com/rvaiya/keyd/issues/236#issuecomment-1159246712).

>  Remove all 2-versions of existing actions and instead allow optional arguments.

Optional arguments were implemented at one point before they were abandoned in favour of the current syntax. Aside from making parsing a bit easier, it also provides a visual way to identify more involved actions and makes it easier to search the man page. 

It's also worth noting that some actions (e.g `macro2`) can't be cleanly disambiguated anyway, and that not all actions have a macro variant.

**Comment by slakkenhuis** [comment]
Even better, of course. Should have been my first thought. Nicely symmetrical.

I do think the `...2` naming is a bit unsatisfying. `time_hold`/`hold_timer` for `timeout` and `time_tap`/`tap_timer` for `timeout2` would be more descriptive. But that would deprecate existing syntax, which is undesirable. Maybe there's a better option

**Comment by rvaiya** [comment]
Even better, of course. Should have been my first thought. Nicely symmetrical.

> I do think the ...2 naming is a bit unsatisfying.

Agreed. The [hard part is coming up with a good name](https://martinfowler.com/bliki/TwoHardThings.html#:~:text=cache%20invalidation%20and-,naming%20things,-.).

> time_hold/hold_timer for timeout and time_tap/tap_timer for timeout2 would be more descriptive.

Something like `timeout-hold` makes sense for `timeout` since the timer corresponds to the length of time the key is depressed, but `timeout2`'s timeout corresponds to the time *between* successive keys and probably shouldn't be named `timeout-tap`. I can't think of a good name which concisely captures its behaviour (maybe `timeout-next`?).

> But that would deprecate existing syntax, which is undesirable.

I have no objection to doing this if it improves readability. The old names can be kept for backwards compatibility.

> Implement timeout_tap and timeout_hold which only take two action arguments,
> applying some default hold_timeout and tap_timeout configurable in the global
> section, and then also introducing timeout_tap2 as well as timeout_hold2, both
> taking a timeout as a third argument. The timeout action could remain valid
> (with keyd issuing a deprecation warning) for backward compatibility.

I think this adds a bit too much complexity. Most users won't bother with timeouts, and those that do should probably understand precisely how the timeouts are applied. Forcing them to be as explicit as possible is a good thing.

**Comment by slakkenhuis** [comment]
> Something like `timeout-hold` makes sense for `timeout` since the timer corresponds to the length of time the key is depressed, but `timeout2`'s timeout corresponds to the time _between_ successive keys and probably shouldn't be named `timeout-tap`.

If anything, the 'tap-timeout', to me, makes *more* sense. A timeout feels like something that happens unless something else happens, whereas a 'hold-timeout' (or 'timer') requires the user to continue pressing (...but I realize you can also interpret that as 'nothing else happening'). In any case, how else is the user supposed to interpret a timeout on a tap? But intuitions differ, of course. And I'm not a native speaker, so what do I know :)

>I can't think of a good name which concisely captures its behaviour (maybe `timeout-next` or perhaps `collapse-wave-function`/`schrodinger-key`?).

Ah, `next` reminds me of `kmonad` and I also remember it being not immediately clear what that meant :P Since you mentioned the word "between", you could also do `timeout-hold`/`timeout-between`? I'm going to run this as a background process in my mind today. (`if-held`/`if-tapped`?)

> What also crossed my mind was `ifelse-hold`/`ifelse-next` with the timeout as first argument.

Wait, what would that look like?

**Comment by slakkenhuis** [comment]
I really like `timeout-idle`. It's by far the most intuitive option to me right now.

`if-held` and `if-idle` are also intuitive, but not more or less so than the current `timeout(action1, interval, action2)` syntax. I gather that this further split is mostly to accommodate possible additional timeout mechanisms? I hope your use case for that is more sane than #81 :P Either way it seems to me that having only the dual `timeout-idle`+`timeout-hold` is clearest, with future specializations remaining possible as optional arguments/suffixed names.

**Comment by slakkenhuis** [comment]
Sure, I'll think when I get some time. Be warned that my involvement may backfire, as rvaiya's conservatism on the matter has proved pretty persuasive to me :P

Anyway, apart from these syntax concerns, that issue can be considered wholly separately from this one, right?

**Comment by rvaiya** [comment]
> If anything, the 'tap-timeout', to me, makes more sense. 

The problem with the name is that it doesn't necessarily have anything to do with whether or not the key is tapped. The sequences `<a down> <a up> <100 ms> <b down>`  and `<a down>  <100 ms> <b down> <a up>` would both produce the same output given something like `a = timeout2(c, 100, d)`.

In some ways a neutral name like `timeout2`, which communicates nothing, has an advantage, since it forces the user to consult the man page (and it is generally quite an obscure thing to be doing in the first place).

> Ah, next reminds me of kmonad and I also remember it being not immediately clear what that meant :P

Case in point :P.

> Since you mentioned the word "between", you could also do timeout-between? I'm going to run this as a background process in my mind today. EDIT: timeout-pause?

`timeout-between` is a bit nicer, but it still isn't immediately obvious what it does. Between *what*? In this case between the key being bound and the next keystroke, but one could be forgiven for thinking it might be between the last key and the present one.

> if-held(time, if_action, else_action)

I assume this is the new name for `timeout`. I don't think this is superior to `timeout` since the name doesn't suggest it has anything to do with time (i.e how it is different from `overload`)

> The difference between if-held-uninterrupted and if-held would be that a keypress within time interrupts the timer and executes else_action (equivalent to the current timeout(else_action, time, if_action);

In which case I believe `if-held-uninterrupted` would be a less generic form of `timeout2` (which doesn't care whether or not the key is released). I also think the name is a bit ambiguous. One could be forgiven for thinking that that 'uninterrupted' means 'if the key is not interrupted, do X'. It's not obvious (to me) that the action proactively *blocks* the next key from being processed until the timeout is resolved.

> I really like timeout-idle. It's by far the most intuitive option to me right now.

Can you explain the rationale?

> if-held and if-idle are also intuitive, but not more or less so than the current timeout(action1, interval, action2) syntax.

+1.

> Thinking things through is part of my job, but keyd (and warpd) get me so excited that I regularly throw all good principles over board. The question is, if that's good or bad... At least I have the excuse of not having a cs background.

You needn't be so hard on yourself. Taste is subjective after all ;). My opinions are just that.

**Comment by slakkenhuis** [comment]
> The problem with the name is that it doesn't necessarily have anything to do with whether or not the key is tapped. The sequences `<a down> <a up> <100 ms> <b down>` and `<a down> <100 ms> <b down> <a up>` would both produce the same output given something like `a = timeout2(c, 100, d)`.
> ...
>Between what? In this case between the key being bound and the next keystroke, but one could be forgiven for thinking it might be between the last key and the present one.

I agree, `tap` and `between` are suboptimal --- and while I see your point that you'd rather force users to read the manual, I maintain that either of these are at least easier to commit to memory than `2` :P Even if the semantic connection is tenuous, it makes manual-reading easier.

>The user would still have to have read the man page to properly disambiguate them from other possible interpretations. Given that this is the case, I am still inclined to think more neutral names might be better in the end.

I disagree there: while I might have to read the man page *once* to understand what `timeout-idle` and `timeout-hold` do, I will probably have to read it *every time* to remember which is `timeout` and which is `timeout2`. That might be an issue with my memory but I'm willing to bet that I'm not the only one.

If there was an actively *counterintuitive* interpretation for the suffixes, I'd be more inclined to agree, but while that might have been the case for `tap` and `between`, I don't think it is for `idle` and similar.

>Can you explain the rationale?

- `timeout-hold`is a timeout on the time that, after pressing the relevant key, you subsequently hold it.
- `timeout-idle` is a timeout on the time that, after pressing the relevant key, you subsequently do nothing. (`timeout-wait` would also work)
 
While the user could surely strain themselves to find a different interpretation, I can't think of any that are obvious. And `timeout` by itself is certainly more ambiguous: what are you timing out?

**Comment by slakkenhuis** [comment]
>As timeout-hold would ignore any interrupting key presses, none of the two actions would mirror the current timeout.

While I haven't formed feelings on #278 yet (asap!) I do strongly feel that the current timeout behaviour should be the default for holding, as it is the one that most users want --- or at least should be steered towards. Even if other hold behaviours *might* make sense depending on your level of comfort with the dark arts, interruptable timeouts as they are now are the only ones that can make for a natural typing experience even without conscious fine-tuning and maniacal cackling on the part of the user.

(By the way, it just occurred to me that both timeouts can also be combined: `timeout(action1, hold-timeout, action2[, idle-timeout, action3])`. I'm not necessarily advocating for that yet but it might be easier to reason about and preserves current syntax)

**Comment by rvaiya** [comment]
After some additional thought I decided to add a global `oneshot_timeout` option. Feel free to open another issue if you feel this is insufficient.
