### ISSUE TITLE
Feature request: Fine tuning for overload

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#278]
I started experimenting with home row mods again, this time on QMK using its [fine tuning options](https://github.com/manna-harbour/qmk_firmware/blob/retro-shift/docs/tap_hold.md) and was finally able to get a usable configuration.

The crux for me (as I type rather fast) is to only enable the modifier behaviour if the overloaded key has been held for a certain amount of time (independently of other pressed keys). Unfortunately, I don't think that this is currently possible on keyd using a combination of `overload()` and `timeout()` (please correct me if I'm wrong).

To explain better what I mean, let's assume that the f key should output an f if tapped and act as shift if held while another key is pressed.

The event sequence when I want to input J is then

```
1. f down
2. j down
3. f up
4. j up
```

which is problematic as those precise events are regularly generated as well upon entering fj.

To disambiguate, one would need to examine how long the f key has been held down and then apply the mod if some threshold has been exceeded.

I thought about an `overload2(layer, action, tap_time)` action, which only shifts the layer if the key is held down for at least `tap_time` ms (independently of whether other keys are pressed before the key is released).

An implementation of this could be to waits for `tap_time` ms upon key press, buffering all occuring key events during that time. If at any point a keyup event of the overloaded key is seen, execute `action` and then process the buffered key events on the current layer. If `tap_time` expired without such a keyup event, process the buffered (and all other incoming) key events on `layer` until the keyup event occurs.

For the same reasons as in my other recent feature request, `overload2` might not be the best name for this and a more user friendly way would simply be to allow tap_time as an optional argument (otherwise applying a default which the user could modify in the [globals] section).

**Comment by rvaiya** [comment]
> The crux for me (as I type rather fast) is to only enable the modifier behaviour if the overloaded key has been held for a certain amount of time (independently of other pressed keys).
> [...]
> To disambiguate, one would need to examine how long the f key has been held down and then apply the mod if some threshold has been exceeded.

I suspect I have misunderstood something. `timeout(f, 300ms, layer(shift))` should do precisely that, no? This was `timeout`'s [motivating application](https://github.com/rvaiya/keyd/issues/138#issuecomment-1042079205) (a thread to which you were party)

The above should produce `J` given the sequence:

```
f down
j down
f up
j up
```

**Comment by rvaiya** [comment]
If *you* find it confusing, then I definitely need to document it better. I've been meaning to add some recipes for common tasks.

**Comment by rvaiya** [comment]
> The only difference to the current timeout thus is that another keypress should not interrupt the timer.

Can you provide an example of when this would be useful? It seems odd not to resolve the timeout on the next keypress, as it allows for pathological cases like this:

`f down j down j up <300ms> -> C-j`

**Comment by rvaiya** [comment]
> whereas the overlap in the fj-case only occurs because of the user's typing speed, which causes j to
be pressed while f hasn't been [released].

This is the crux of the problem. Most touch typists don't actually release the first key before striking the second. 

> Regarding the pathological use case: I think this is an unavoidable side effect.

Indeed. This was discussed at length in #81 with @slakkenhuis when timeouts were originally introduced. As outlined in that thread, I remain unconvinced that the inherent ambiguity, latency, and additional complexity make it a worthwhile tradeoff, but I am open to persuasion on the point.

> One could think about only applying the modifier if f is released before j, but then f could no longer serve to apply shift to multiple following keys. 

It's possible I've misunderstood something, but I can't think of a reason anyone would want to do this.

**Comment by slakkenhuis** [comment]
As has been noted before, a lot here is reminiscent of #34 and #81. Back then, I ended up agreeing with rvaiya: the inevitable visual latency and (perhaps less inevitable) misfires due to inconsistent timing make for a hair-pulling typing experience for me personally. There's one very crucial difference here:

> I'm actively using the described feature on a qmk keyboard since a few days (the whole homerow is overloaded) and it's working great so far.

The fact that ZMK/QMK/kmonad provide this behaviour is encouraging, but not decisive because their design is less opinionated, at the expense of simplicity and guidance. I certainly made a lot more unusuable keyboards in kmonad than in keyd. But the fact that you have made it work for you is convincing.

I assume that you do experience some visual latency (ie normal characters don't appear instantaneously but with a delay measuring in some tenths of a second). Are you just not bothered by it?


> I highly doubt one can give a valid argument that one of these behaviours is better than the four others.

Imho it is "better" in the sense that it gives a smooth typing experience with minimal visual latency and no fiddling with personal, millisecond-level sweet spots. That said, that does not mean that the other behaviours have no right to exist :)

So, while I do think your explanation makes intuitive sense, I remain convinced (as in #277) that the current behaviour is what users should be guided towards. Event queues may work for some, but users wishing to visit those depths can be expected to do some digging. That is, your `<interrupt-handling-logic>` would be an optional argument with a default value of `1`.


All that said, I need some more time to digest this. And experimentation.

**Comment by rvaiya** [comment]
Apologies for the belated response, I was putting this off until I had some time to read and respond to it in full. Moving forward it might be better to proceed one use case at a time, to ensure we have a shared understanding of the problem and to create a tighter feedback loop (I myself have a habit of being too verbose at times :P).

> While Keyd already supports timeouts, it forces a specific interrupt logic on the user.

A veritable feature ;).

> which is not optimal in all cases, sometimes even resulting in the overload being unusable.

I maintain that in conjunction with the proposed `timeout2`, the current implementation supports the majority of real world use cases with composition.

> There is hence no universal solution and instead, the other popular “advanced” key remappers I know offer a sufficiently general mechanism to fine tune the behaviour.

I am personally of the opinion that many of these 'solutions' involve undesirable tradeoffs for what is fundamentally an intractable problem, but my views on the subject have already been stated in other threads, and I am not inclined to foist them upon the userbase. 

Here I will contend that most of the use cases you describe are already covered by keyd's composable `timeout` (and the proposed `timeout2`) construct.

> keyd's overload mechanism should be able to decide whether to activate the layer or an action 
> based on the following parameters:
>
>[...]
> Specifically, the following interrupting key logic should be configurable
>[...]

> I) Decide what to do purely on the hold time (ignoring any interrupting key presses)

Addressed with `timeout2(noop, <timeout>, <action>)`

> II) Interrupting key press within timeout triggers layer activation

Currently possible with `timeout(overload(<layer>, <key>), <timeout>, <key>)`

> III) Interrupting key press within timeout triggers action 

Just a more generic form of the above: `timeout(<action>, <timeout>, <key>)`

> IV) Interrupting key press and release within timeout triggers layer activation 

A little more involved, but possible like so:

```
timeout2(layer(stage2), <timeout>, <key>)`

[stage2]
<second key> = toggle(<target-layer>)
```

though I'm not sure why anyone would want to do this.

V) Interrupting key press and release within timeout triggers action

A more general form of IV:

```
timeout2(layer(stage2), <timeout>, <key>)`

[stage2]
<second key> = <action>
```

> Current keyd support and implementation notes If I'm not mistaken, the only case keyd already covers is III

See above :P. It's possible I have misunderstood some of the behaviours you describe. Corrections are welcome.

> so maybe it is a good idea to at least forbid nesting timeouts.

This is already forbidden.

> I read that overload once already had an optional timeout flag and suppose that it was removed after the more general timeout action was introduced.

Indeed. The current design favours composition over having a dedicated action for every conceivable use case. Easy things should be easy, and more involved things should be possible (within reason).

> timeout2(<action1>, <timeout>, <action2>, <interrupt-handling-logic>) in the
> [...]
> An interrupt-handling-logic value of 0 ignores (i.e. just buffers) interrupting key events until <timeout> has expired, a value of 1 and 2 chooses the first and second action, respectively, if an interrupting key press occurs within <timeout> and analogously for 3 and 4, with key press replaced by key press and release.

Can you provide a real world use case that this addresses?

> a prime use case are still overloaded non-modifier keys

As discussed in #277, this is what [timeout2](https://github.com/rvaiya/keyd/issues/277#issuecomment-1211634724) is intended to address.

> The mere fact that QMK, ZMK and Kmonad all offer not only timeout [...]
> does not seem to be pure coincidence and proves that these features are actually useful.

Never underestimate the twin powers of rationalization and group think ;). Just because you *can* do something doesn't mean that you should. My personal views aside, I have yet to encounter a use case not covered by either `timeout` or `timeout2`.

> Apart from that, it seems a bit deliberate that timeout always chooses one of these five possible interrupt handling behaviours.

As demonstrated, the timeout actions are flexible enough to handle the five cases you enumerated. 

Fundamentally there are two intervals of interest: 

 1. The intrakey interval (that is, the time between a key's depression and its release, [covered by `timeout`]).

 and

 2. The *inter*key interval (the time *between* two distinct keys [covered by `timeout2`]).


Taking these as primitives, it should be possible to compositionally realize most interesting applications. This approach differs from the QMK approach of *implement all the things*, but should have comparable expressive power.

> Finally, I did some quick measurements and confirmed that when typing regular words, I'm basically never tapping letters in isolation.
> [...]

Indeed! I pointed this out [here](https://github.com/rvaiya/keyd/issues/81#issuecomment-1003790533). It is the main impetus for timeout based solutions, but as I outlined in that post I think it is misguided.

> So in my case, which I strongly believe to not being that uncommon, the ability to specify interrupt handling logic would enable overloading letter keys (and the space key) without any loss in typing speed.

I encourage you to actually try this (if you haven't already). I maintain that it will either force you to change your typing habits (lowering your speed ceiling), or give you modifier PTSD.  Having said that, it should be facilitated by `timeout2` as outlined above.

**Comment by rvaiya** [comment]
Sorry, I omitted the crucial bit of `I`, namely `(ignoring any interrupting key presses)`.

Barring nesting (which I agree is ugly) this would necessitate the addition of the third timeout (tentatively called `timeout3`), as you proposed.

To summarize, the goal would be for:

`<a down> <b down> <b up> <200ms> <a up>`

and

`<a down> <b down> <b up> <100ms> <a up>`

to produce `C-b` and `ab` respectively given `a = timeout3(a, 200, layer(control))`. 

The proposed `timeout2` (among other things) allows for distinguishing between:

`<a down> <100ms> <b down> <b up> <a up>`

and

`<a down> <200ms> <b down> <b up> <a up>`

The idea being that the pause before the second key is struck is more indicative of the user's intention to use the first key as a modifier than the total amount of time `<a>` is held. 
This method involves less visual latency than the first, but is presumably not as effective given the latter's ubiquity (though I still think neither is a worthwhile tradeoff).

**Comment by rvaiya** [comment]
> The following cases are relevant for the discussion:
> 
> f_down j_down j_up f_up (nested tap)
> f_down j_down f_up j_up (key roll) 
> 
> What I would like to have is the following behaviour:
>
> [...]  
> [...] all of the following should output J:
> 
> f_down j_down j_up f_up <T>
> f_down j_down j_up <T> f_up

It's not clear what role the timeout is serving in this example. Under which conditions involving a 'nested tap' is `fj` produced? 

Your wording would suggest that if the timeout has not elapsed by `<T>` then `fj` is produced, which would imply that all of:

 1. `<f down> <j down> <j up> <100ms> <f up>`
 2. `<f down> <j down> <100ms> <j up> <f up>`
 3. `<f down> <100ms>  <j down> <j up> <f up>`

yield tap behaviour (assuming a timeout of `200ms`).

in which case it's not clear what the difference between:

> f_down j_down j_up f_up <T>

and

> f_down j_down j_up <T> f_up

is. 

If my understanding is correct, then the behaviour you describe is identical to the proposed `timeout3` (an 'uninterrupted timeout' disambiguating intention upon expiry (or key up)).

Having said that, it's not clear to me that this is the optimal approach.

For example, it's not obvious that:

`<f down> <200ms>  <j down> <j up> <f up>`

should necessarily be treated the same as:

`<f down> <j down> <j up> <200ms> <f up>`

since the location of the pause potentially correlates with intention.

`timeout2` can be used to specifically deal with the timeout between $$k1_down$$ and $$k2_down$$ (the interkey interval) without conflating it with cases 1 and 2. Given that QMK seems to favour `timeout3` (which I believe is its default behaviour), I assume this is probably not an issue in practice (or no one has bothered to measure the alternatives).

> Therefore, the sequences
> 
> ```
> f_down <T> j_down f_up j_up
> f_down j_down <T> >f_up j_up
> f_down j_down <f_up> <T> j_up
> ````
>
> should result in J, J and fj, respectively.

I believe this should already be a byproduct of `timeout3` ('resolve on timeout or $$k1_up$$').

> While QMK fully supports point 2, I haven't found a way to get 1, which is why I will probably order some nice!nanos so that I can try the setup on ZMK (where it is called “balanced mode”).

Interesting. Are you suggesting QMK does not interpret:

```
<f down> <200ms> <j down>
```

as `J` (for `timeout = 100ms`)? This would seem like a deliberate exception. It has been a few years since I have experimented with QMK timeouts, so I am not familiar with their current behaviour.

> Like I already replied to @slakkenhuis: I think that there should at least be a way to select the second action on interrupt. 
> [...]
> I think that it is completely arbitrary to select the first (unless one has a very specific use case in mind).

I don't agree with this. The rationale behind interpreting the `timeout` interrupt ([$$k1_down$$, $$k2_down$$]) as a 'tap action' by default, is that holding a key is a deliberate action that the user should have to consciously pause to achieve.

That is given `space=timeout(space, 500, layer(control))`, you almost always want:

`<space down> <400 ms> <j down> <space up>`

to resolve as:

`<space down> <j>` 

rather than:

`C-j` 

The reverse only becomes desirable if you introduce more sophisticated timeouts in conjunction with event queuing (`timeout3`) to try and guess the user's intent, which introduces the host of issues previously discussed (visual latency, misfires, etc).

> That last sentence is the thin straw of hope that drives my replies, in the hope that you have mercy with those users who yet have to find their holy grail.

You've persuaded me that my former obstinacy was unwarranted. Though I still think 'home row mods' are the domain of the swivel eyed loon ;).

> I think that we misunderstood each other regarding the desired functionality, mostly because I was not clear enough.

No, it was my fault. I should have read your examples more clearly. The first one you provided clearly necessitates the addition of a third action. I was previously opposed to it because of my instinctive aversion to event queuing, but since there seems to be a fair amount demand for it, I will acquiesce.

> IV) Interrupting key press and release within timeout triggers layer activation
> Again we apparently misunderstood each other. What I actually meant is that upon key press and release within timeout, the first key should act as a modifier (activate the layer). I think for this, an action akin to the planned timeout2 would be needed, which listens for a complete tap within the timeout, not just a key press.

In that case, how does this differ from `timeout(overload(layer, key), 300ms, layer)`?

> instead of writing timeout(overload(<layer>, <key>), <timeout>, <layer>), the user could just state overload(<layer>, <key>, <timeout>, 1), and all other cases could simply be achieved by varying the last argument as described.

I am more inclined to favour the existing composition approach. If a real world use case can't be achieved using the existing (or proposed) actions, feel free to file a separate issue.

>> The _intra_key interval
>> [...]
>> The _inter_key interval
>> [...]
>
> If I'm not mistaken, out of the five cases, this allows to cover two, and I still think that all five cases are useful.

I think this is solved by distinguishing between the 'interrupted intrakey interval' ([$$k1_down$$,  $$first(k1_up, k2_down)$$] (i.e `timeout`)) and the 'uninterrupted intrakey interval' ([$$k1_down$$,$$k1_up$$] `timeout3`). The second can probably properly be called the 'intrakey interval', though the first probably deserves a better name, since it doesn't strictly deal with the time between key down and key up.

> I think so, but to be on the safe side, let's be very verbose: Disambiguation should be done purely based on the hold time of the a key,

+1. This is the key bit. I think we are in agreement on this point.

> the other one acting like timeout2, but listening for key taps instead of key presses within the timeout

I'm not entirely sure how this is different from the proposal outlined in #277, but this is probably not the place to discuss it.  


I still think we are discussing too many things at once. I've created a dedicated issue for `timeout3` (#309) and will shortly create one for `timout2`. If you think something remains uncovered feel free to post in those threads.

I'm closing this for now.
