### ISSUE TITLE
How to make FN become super

### ISSUE THREAD

**Issue by Leiyi548** [rvaiya/keyd#299]
I am using this project, which brings great convenience to my life. Thank you very much. I am an I3 user. I often use super. I want to change the FN key to super

**Comment by slakkenhuis** [comment]
You can use `keyd -m` and press the key that you want to remap to and from to find out their internal names. If by 'the FN key' you mean F1 et al, and by 'change to super' you mean simply swap it with the OS key, it's probably as easy as:

    f1 = leftmeta

Although it is recommended to map to layers rather than directly to modifier keys:

    f1 = layer(meta)

If you instead meant the FN key that is often present on laptops to expose function keys: I think they usually don't send an actual keycode, so they can't be handled by `keyd`. But check `keyd -m` to be sure.
