### ISSUE TITLE
meta: use GitHub releases, for notifications

### ISSUE THREAD

**Issue by eNV25** [rvaiya/keyd#301]
Currently, releases are done with tags. But these are not used to create a GitHub release, and it doesn't display the same way as other projects hosted here.

The problem is that, when only tagging a release but not using GitHub, it is not possible to get a notification for new releases. I use those as reminders to update AUR packages.

Making releases using GitHub would be more convenient for me. For creating releases, there are GitHub CLI tools that make it easier, no need for the website.

This is not a big issue, but with this I could make releases quicker. I don't know any alternatives.

**Comment by rvaiya** [comment]
Do you mean email notifications? I am generally loath to use any proprietary github features since they are largely superfluous and just encourage vendor lock-in.  

I would encourage you to just pull the changes (the diffs are small) and use standard git facilities (`e.g git tag`) to find the latest release. If you really want to avoid this, it should be possible to get the latest version using something like:

`curl https://api.github.com/repos/rvaiya/keyd/tags|jq -r '.[]|.name'|grep '^v[0-9]'|sort -V|tail -n1`

Though you will probably want to make it more robust.

**Comment by eNV25** [comment]
Yea, the problem is email notifications. I have no problem using tags.

**Comment by rvaiya** [comment]
It was trivial enough to just generate them from the tag, so I've done so. I will try and remember to do this moving forward, though they won't contain any additional metadata.

**Comment by eNV25** [comment]
Thanks.
