### ISSUE TITLE
international characters

### ISSUE THREAD

**Issue by budRich** [rvaiya/keyd#31]
Hello!, or as we say in Sweden hallå!

I have been using a very hackish method for years to make a custom layout with setxkb. It has worked fine, but you know only in x. The gist of the layout is that i can use the "extra" key on nordic QWERTY keyboards to act as a modifier for a special layer, and without it i am completely lost.

It seems like i can get all functionality i had before with this keyd except remapping keys to swedish characters. I want this to work:  

```
# Turns capslock into an escape key when pressed and a control key when held.
capslock = overload(C, esc)

# Remaps the escape key to capslock
esc = grave

102nd = layer(bud)

[bud]

h = left
j = down
k = up
l = right

[ = macro(å)
' = macro(ä)
; = macro(ö)
```

(i also tried without using macro `[ = å`, but that didn't work either.
When i press f.i å (with normal swedish layout active) when `keyd -m` is running it just prints `[`.

I haven't looked that closely at the source. And I imagine this gets tricky since supporting every single foreign character might make the keys.h gigantic? But for me it would be acceptable if macro made a Unicode translation of the chars added and printed that.

Anyways, thanks for a very cool program.

**Comment by mefromthepast** [comment]
You should be able to do it with unicode:

`[ = macro(C-S-u 00e5 space)`

**Comment by budRich** [comment]
cool. I found another way. I enabled the default keyboard layout se(us) , which have this functionality except swedish characters are enabled through layer3/AltGr modifier. But i just realized there doesn't exist an equivalent for the virtual console, so maybe i will use the macro thing anyways. thanks!

**Comment by budRich** [comment]
just tried, it didn't work, it just printed the string "00e5"

**Comment by rvaiya** [comment]
keyd is just used to generate keycodes, translating them into symbols is handled higher up the input stack. If you want to produce non-english glyphs you will have to configure your display server to use the appropriate layout so it generates the intended symbols (or 'keysyms' in X) when the keycode is generated.

For example, if your display server is configured to generate  `ü` when `altgr + u` is pressed and you define `u = G-u` in keyd then  it will generate `ü` when struck. However, if you change your X keymap to qwerty then `u` will be treated as `alt + u` instead even though keyd is generating the same keycodes.

> You should be able to do it with unicode:

Using a unicode keysequence macro is a bit of a kludge since unicode input is handled even higher up the input stack at the application level and consequently will not work with many programs. 

The correct solution is to remap at the level of your display server/virtual console (e.g loadkeys, setxkbmap) and then use keyd to add things like layers and oneshot modifiers should you desire them. If you happen to be using an English layout then it might make more sense to define the layout in keyd since the default layout for both the virtual console and display server in most English distros is qwerty and remapping in keyd has the advantage of applying the layout universally.

**Comment by rvaiya** [comment]
I toyed with this a little bit and think the best solution is to use compose key macros since it requires minimal configuration on the X side and doesn't depend on the layout. See #33.

**Comment by rvaiya** [comment]
There is now first class support for this, so you can just do `u = Ü` directly in the config file. It works by automatically generating the appropriate XKB macro sequence, so you still need to have `compose:menu` set. See the man page for details.

**Comment by diegodario88** [comment]
> 

Hey rvaiya, for some reason, just in google chrome, i'm getting the character code instead of the character itself.

Do you have any idea what it could be? 00103 instead of ç

I symlinked compose and currently my default.conf looks like this

```
[main]
capslock = overload(capslock, esc)
esc = capslock
pause = ç
```

**Comment by rvaiya** [comment]
@diegodario88 Please open a dedicated and include your OS, chrome version, and desktop environment.

**Comment by rvaiya** [comment]
@diegodario88 I'm assuming you are using wayland. I've created #273, feel free to comment there.
