### ISSUE TITLE
Feature request: overload with interrupt on tap

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#310]
EDIT: clarified the meaning of `<timeout>`.

As already mentioned in #309, I'm vouching for yet another overload action, referenced as `overload_tap` here (purely to avoid confusion with the already used `overload2`, `overload3` etc.).

### Functionality

The action should be of the form `overload_tap(<layer>, <action>, <timeout>` and have the following functionality:

The layer `<layer>` is activated, if the bound key is held for at least `<timeout>`ms (activation takes place as soon as `<timeout>`ms have passed) and remains active until the key is released.
In addition, if another key is tapped (pressed and released) before the timeout while the bound key is held, the layer is activated as soon as this other key is released and again remains active until the bound key is released. This additional activation distinguishes `overload_tap` from the planned `overload2`.

### Use case

This action is useful when overloading letter keys with a modifier, say when the `a` key should also act as shift. Let's assume this is implemented by `a = overload2(shift, a, 200)`, using the proposed `overload2` action described in #309. Summarizing what follows, while `overload2` works great during input of text (when key rolls are produced), there are issues when entering isolated symbols (done through nested taps).

For a touch typist, two typical cases arise:

#### 1. Using the modifier behaviour while typing words.
Here, key rolls are produced. For example when typing “Level”, the sequence begins with
```
<a_down> <l_down> <timeout> <a_up> <l_up>,
```
where, here and in the following, `<timeout>` denotes the moment in time, where `<timeout>` ms have passed since the first event (`<a_down>`).

Given the timeout is fine tuned to the user's typing speed, `overload2` works perfectly, with the capital L appearing at the timeout. The delay detween `<l_down>` and `<timeout>` is unavoidable in order to distinguish an intended input of “also”, which is produced by
```
<a_down> <l_down> <a_up> <timeout> <l_up>
```
In this latter sequence, the output “al” appears at `<a_up>`, again with an unavoidable delay.

#### 2. Using the modifier behaviour while typing isolated symbols

In contrast to case 1, this is typically done (at least for me) in the form of nested taps.

__a) Inner tap is completed before the timeout__
For example, when trying to type a capital `H` in isolation (as done in vim to go to the first line of the file), the sequence would be
```
<a_down> <h_down> <h_up> <timeout> <a_up>
```
With `overload2`, the capital H would be emitted at `<timeout>`, so there is again a delay between `<h_down>` until `<timeout>`. But assuming that the user *always* intends to use the modifier behavior when inputting nested taps (for me this is the case), this delay can be shortened: With `overload_tap`, H would be emitted at `<h_up>` already, because here it is clear that a nested tap will be produced. In my case, the time increment between `<h_up>` and `<timeout>` is noticeable and the only issue I have when using homerow modifiers in QMK.

__b) Outer tap is completed before the timeout__
There is another case where `overload_tap` is advantageous to plain `overload2`: Some users input nested taps very fast, so that the resulting sequence is
```
<a_down> <h_down> <h_up> <a_up> <timeout>
```
Here, `overload2` would always produce “ah” instead of the intended “H”. This would be addressed by `overload_tap` as well, which would produce “H” on `<h_up>`.

### References

The proposed functionality is available in ZMK, where it is known as [“balanced flavor”](https://zmk.dev/docs/behaviors/hold-tap). QMK has the [`PERMISSIVE_HOLD`](https://github.com/qmk/qmk_firmware/blob/master/docs/tap_hold.md#permissive-hold)  option, which only adresses case 2b but leaves 2a open.

### Necessity of a separate `overload2`

As already mentioned elsewhere, `overload_tap` would *not* make `overload2` obsolete. The issues described in case 2 above do not arise for all users and crucially depend on individual typing behaviour. While `overload_tap` will most likely solve all my personal home row modifier worries, it might be another user's obstruction on the way to input nirvana.

**Comment by slakkenhuis** [comment]
I like this one!

There's been a lot of messages across the threads and I apologize if I'm missing something that's been laid out already. Then again, my missing something also indicates that documenting all this might become difficult, which is how I'm going to justify my questions... I'm going to focus first on:

> Necessity of a separate overload2

It occurs to me that all recent timeout-based suggestions so far could be boiled down to just three general mechanisms, with a nice duality between each. Keep in mind that I'm basing this on use cases in the most abstract sense: I'm aware that fundamentally different *mechanisms* have been proposed (eg `overload2`), but I'm quite fond of the config's ability to be understandable at a glance, and I believe that pre-emptive catering to other 'possible' use cases can be a trap --- especially if it results in a proliferation of variants of `overload`s and `timeout`s. Specifically, I contest claims like:

> case 1 should still be supported as it certainly will be optimal for somebody else. (...) whether the additional logic for nested taps which case 4 would provide is a benefit or not heavily depends on the user and use case in my opinion. ([source](https://github.com/rvaiya/keyd/issues/309#issuecomment-1229542119))

Surely, someone *might* find a use for it, but I think that would need to be defended specifically. Otherwise, simplicity comes first. As it is, I can definitely see the added benefit of `overload_tap` over `overload2`, but not vice versa. ... except if it turns out that accidental `a_down b_down b_up a_up` actuations often happen when typing `ab`, which I find much more unlikely than `a_down b_down a_up b_up`, but admittedly haven't got the data to back up. Is that possibility what you're basing your advocacy of both on, or am I overlooking something?

**Comment by slakkenhuis** [comment]
Okay, that convinces me. The first point not as much (I think you're underestimating what a niche we occupy, but again, not backed by data). The second, certainly. An added bonus (for me) is that it's another argument in favour of seeing it in terms of a general timeout rather than a specific overload.

(I also realize I should have made my comment in #309. My bad.)

**Comment by rvaiya** [comment]
From what I understand, this is effectively a micro-optimization of `overload2` which avoids unnecessary visual latency. It is predicated on the assumption that `<a down> <b down> <b up>` can unambiguously be resolved as a tap.

I don't know whether or not this assumption holds in practice, but assuming it does, it may make sense to just make it the default behaviour of the newly proposed action (whatever the name may be).

Most of the recent proposals are fundamentally about trying to mitigate the side effects of the same use case, namely the ability to overload a key that is commonly tapped before another.

The existence of different implementations strikes me more as an artifact of QMK/ZMK development history than a thing necessitated by the problem itself.

While I'm not necessarily opposed to leaving granular control up to the user (it doesn't add much additional implementation complexity), I am not yet convinced that the existence of multiple (minutely varied) behaviours adds any value or warrants the additional cognitive overhead.

My instinct is that one of these solutions is objectively superior, and it probably makes sense to just steer the user in that direction.

> But assuming that the user always intends to use the modifier behavior when inputting nested taps (for me this is the case), this delay can be shortened: 

I suppose this is the key consideration. 

> As already mentioned elsewhere, overload_tap would not make overload2 obsolete. The issues described in case 2 above do not arise for all users and crucially depend on individual typing behaviour. 

Are you aware of any evidence which supports this?

-----

Edit: I just read slakkenhuis' response, his views largely accord with my own.

> Surely, someone might find a use for it, but I think that would need to be defended specifically. Otherwise, simplicity comes first.

+1

> The ones I have read over the last years attribute their share to anything between 3% and 30%, 

Intriguing, I didn't realize touch typing was such a rare talent.

> However, the remaining 70-97% type in a “non-standard” way, frequently need visual contact to the keyboard, at least partially apply a “hunt-and-peck” technique

It seems to me that the hunt and peck crowd would be *less* likely to produce nested taps. I might even go further and posit that most of them can get away with sequence based overloading (`overload`),but I am open to evidence which suggests otherwise.

> depending on the sample, and as there is a likely overrepresentation of “power users” in the keyd user base, 

+1

> There is in fact a valid use cases for overload2 that just came to my mind on the way home: You could use it to implement a usable auto-shift feature [...]

Putting aside the usability of this (about which you can probably guess my views :P), it's not obvious that this would alter the tap/hold sequences produced by the user. I am inclined to believe those would be invariant.

I've written a small script which detects the presence of nested taps. They were surprising sparse in my tests, though there were some notable exceptions. I found  digraphs `na` and `am` (in qwerty) particularly problematic in my case (try typing mammal or stamina 10 times in a row).

You can find the script [here](https://gist.githubusercontent.com/rvaiya/28d8a828af978dd6eb0ad73425982259/raw/6f747fe3e5b34151b27ac5ea11ec211cfe8e1c01/nester-tap-detector.sh). For best results, build keyd from the latest commit (I made some tweaks to `monitor`).
