### ISSUE TITLE
Proposal: Make `overload` a special case of yet another new timeout action

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#312]
This is yet another suggestion towards integrating the features proposed in #277, #309 and #310 with the existing `overload` and `timeout` actions. To better understand the following, some knowledge of the three cited threads is needed.

Here I propose a `timeout-hold-preferred(<action1>, <timeout>, <action2>)` action (the actual name has to be discussed), which acts like `timeout`, but with the sole difference that on an interrupting key press the second action is chosen.

As already observed, in the special case where `<action2>` is `layer(<layer>)`, one has the equivalence
```
timeout-hold-preferred(<action>, <timeout>, layer(<layer>)) = timeout(overload(<layer>, <action>), <timeout>, layer(<layer>))
```
which until now was an argument against implementing `timeout-hold-preferred`. However, I think that @slakkenhuis`s reasoning in #310 implies that the functionality should be available for generic actions. There are two ways to support this:

1. Implement `timeout-hold-preferred`.
2. Implement a variant of `overload`, say `overload_generic` for the sake of discussion, which accepts an arbitrary action as a first argument. When combined with `timeout`, this would then yield the desired equivalence:
```
timeout-hold-preferred(<action1>, <timeout>, <action2>) = timeout(overload_generic(<action2>, <action1>), <timeout>, <action2>)
```
I propose to follow the first route (in line with slakkenhuis's argumentation) and in addition to apply some internal changes to overload:

### Proposal

- Implement `timeout-hold-preferred` (with a better name)
- Introduce a `MAX_TIMEOUT` value (either purely internal, or exposed as a user-definable option). Timeouts given as arguments to any of the timeout actions are not allowed to exceed this value.
- make `overload(<layer>, <action>)` an alias for `timeout_hold_preferred(<action>, MAX_TIMEOUT, layer(<layer>))` and mention this in the manual.

### Rationale
To repeat @slakkenhuis's arguments and add some more:

The current `timeout` and the proposed other timeout-based actions accept generic actions, while `overload` is associated to the specific case of layer change. This distinction is a very useful guide for the user. Introducing a variant of `overload` which accepts two generic actions would violate this principle and might therefore cause confusion.

Most importantly, together with the proposed timeout-actions in the threads cited above, having a dedicated `timeout-hold-preferred` would result in a nicely symmetrical end user interface with a clear hierarchy: At the most abstract level there are five timeout actions, four of them of hold-tap type (interrupt is ignored, interrupting press selects first action, interrupting press selects second action and interrupting tap selects first action) and in addition `timeout-idle` (with a possibly different name). For ease of use, `overload` (and possibly other such actions) exist as syntactic sugar. This follows an easy to understand logic. On the other hand, promoting a generic `overload` to be at the top level by not directly exposing `timeout-hold-preferred` but instead replicating it by nesting `timeout` and `overload` results in no hierarchy at all, breaks the symmetry (`overload_generic` has little in common with the timeout actions) and also artificially makes one of the four hold-tap types artifically stand out (three have direct actions, one can only be achieved by nesting). This is harder to grasp in my opinion.

The fact that the functionality of `overload` would slightly change (`<action>` is no longer executed if held longer than `MAX_TIMEOUT` in isolation) is not a disadvantage in my opinion. I can't imagine any user who wants to execute some action by holding an overloaded key for a very long time (and if so, this is still possible by adjusting `MAX_TIMEOUT`). In addition, the existence of a maximal timeout is probably necessary anyway in order to deal with swallowed key up events (unplugging the keyboard or suspending to ram while holding a key etc.).

**Comment by rvaiya** [comment]
It's still not clear what use case this addresses.

> However, I think that @slakkenhuis`s reasoning in #310 implies that the functionality should be available for generic actions.

I reviewed the thread, but couldn't find the mentioned use case. Can you provide an example of an action that would be desirable to execute on interrupt that is *not* a layer activation?
I stand by the remarks I made [here](https://github.com/rvaiya/keyd/issues/278#:~:text=I%20don%27t%20agree%20with%20this.%20The%20rationale%20behind%20interpreting%20the%20timeout%20interrupt%20(%5B%24k1_%7Bdown%7D%24%2C%20%24k2_%7Bdown%7D%24%5D)%20as%20a%20%27tap%20action%27).

> There are two ways to support this:
>[...]
> At the most abstract level there are five timeout actions, four of them of hold-tap type (interrupt is ignored, interrupting press selects first action, interrupting press selects second action and interrupting tap selects first action)

I'm still not sold on the full `interrupt x timeout` matrix, since it isn't clear that all combinations are actually useful. While the symmetry might please the mathematician in you, just think of the poor user ;).

> This follows an easy to understand logic.

It makes it easier to reason about event sequences, but the user ideally shouldn't have to think at that level. The question should be: 'How can I achieve X?'. It seems that the main use for timeouts (of any kind) is to facilitate overloading, so having a dedicated action which implements the best version of that makes more sense than simply exposing all possible primitives. It may turn out that the problem is sufficiently complex that this is unavoidable, but I am yet to be persuaded of that.

> On the other hand, promoting a generic overload to be at the top level by not directly exposing timeout-hold-preferred but instead replicating it by nesting timeout and overload results in no hierarchy at all,

I think it makes more sense to see it from the perspective of utility. There are fundamentally two desirable forms of overload:

	1. Overloading keys which are normally struck by themselves.
	2. Overloading keys which are normally struck in succession.

1. is best achieved using a purely sequence based approach (`overload`) since it doesn't introduce any additional latency 
2. is the subject of #310 and #309 and will likely be named accordingly (`overload*`).

These should not be seen in relation to any existing (or proposed) `timeout*` actions, since the optimal solutions to them are quite involved and don't necessarily generalize.

> breaks the symmetry (overload_generic has little in common with the timeout
> actions) and also artificially makes one of the four hold-tap types artifically
> stand out (three have direct actions, one can only be achieved by nesting).
> This is harder to grasp in my opinion.

Symmetry is a double edged sword since the user has to figure out which actions (and in what combination they) are actually useful.
