### ISSUE TITLE
How to filter key interrupts in timeouts?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#313]
I just encountered the need to filter key interrupts when using `timeout`. I did not want to open this can of worms, but haven't found a simpler solution.

Here is my use case:

Today I started playing around with combo mods, with the idea of using them on the homerow in order to obtain access to more layers (the general intent is to make minimal split keyboards such as the 36 key corne usable). By combo mods I mean that pressing down two keys (approximately) simultaneously activates some layer (either via `layer` or `oneshot`). To get more specific, such layers would be used to input mathematics, most importantly Greek letters, but also accented letters, German umlauts etc. frequently used during text typing (at high typing speeds).

For example, if pressing the f and g keys should activate such a combo, I started with a config of the form

```
[main]
#li stands for left index finger, analogously for the other layer
f = timeout(layer(li), 25, f)
g = timeout(layer(lm), 25, g)

[li]
g = oneshot(lang)

[lm]
f = oneshot(lang)

[lang]
a = ä
```

As the keys from one combo lie directly beside each other, it never happens that I input “fg” in such rapid succession that a layer is activated. However, when inputting letters with different hands, such as “fj”, I reach low enough time differences (such as `<f_down> <20ms> <j_down>`) so that the layer action of the first key fires, swallowing the intended letter output. For simplicity, I used QWERTY in the example, yielding the very rare letter sequence “fj”. In practive I use dvorak, which produces sequences that actually occur very frequently.

I tested this extensively today and in fact the problem only occurs when the two involved keys are pressed using different hands. Therefore, the problem could be solved if `timeout` would only consider interrupts of specific keys. The idea of disambiguating based on the next key already appeared when I was reading about homerow mods (where some people only activate the modifier if the overloaded key is held long enough *and* the next pressed key is on the other side of the keyboard, hence pressed with a finger on the other hand), and it could potentially also be useful in other situations. However, so far I thought that this disambiguation could be done using keyd's elegant layer mechanism, adding the swallowed letter in hindsight on the activated layer, i.e.

```
[main]
f = timeout(layer(li), 25, f)
g = timeout(layer(lm), 25, g)

[li]
g = oneshot(lang)
a = fa
b = fb
c = fc
...

[lm]
f = oneshot(lang)
a = ga
b = gb
c = gc
...

[lang]
a = ä
```

This works fine, until another combo is added:

```
[main]
#li stands for left index finger, analogously for the other layers
f = timeout(layer(li), 25, f)
g = timeout(layer(lm), 25, g)

j = timeout(layer(ri), 25, j)
k = timeout(layer(rm), 25, k)

[li]
g = oneshot(lang)

a = fa
b = fb
c = fc
...

#lm, ri and rm letters analogously

[lang]
a = ä
```

Now there is a problem when pressing letters from different combos in rapid succession, for example `<f_down> <20ms> <j_down> <10ms> <k_down> <5ms> <f_up>`, with the intention of first inputting the letter f, and then activating a combo by simultaneously pressing the j and k keys. Here, the f is added, but the combo is not activated. To fix this, one would need to output the swallowed letter and then execute the timeout, for example defining the j key on the li layer in the form

```
[li]
j = sequence(macro(f), timeout(layer(ri), 25, j))
```
and adding an analogous statement for k on that layer. Here, `sequence(<macro>, <action>)` would first execute the macro (spewing the swallowed f) and then the action. Other solutions would be to implement `layer2(<layer>, <macro>)`, where macro is only executed if the next pressed key has no explicit definition on `<layer>`. A third one is to implement `timeout-filtered(<action1>, <timeout>, <action2>, <key_group>)`, where only the keys from `<key_group>` are allowed to interrupt and key groups can be defined in some form in the configuration file (if there is no better solution, there should probably just be the two groups `left` and `right`).

However, all of these solutions don't feel right to me, am I overlooking something simple using existing or already planned means?

**Comment by rvaiya** [comment]
I've only had time to skim your post (I will review it later), but my initial impression is that this is just the problem of overloading in a different form. The end goal is to establish whether or not the user intended to hold the involved key(s).

A solution involving the proposed overload2 action might look something like this:

```
a = overload2(a, a, 50)
b = overload2(b, b, 50)

[a]
b = layer(b)

[b]
a = layer(a)

[a+b]
a = λ
```

> Here, sequence(<macro>, <action>) would first execute the macro

I've considered this and rejected it for the same reason as not wanting to allow for configurable interrupts (the goal of the config language is to make things simple, not to be turing complete).

**Comment by rvaiya** [comment]
> Here is my use case:

+1

> Therefore, the problem could be solved if timeout would only consider interrupts of specific keys.

Or simply by implementing dedicated logic for compound keys. It's not clear that key-specific interrupt logic would have any other use, or make sense as a primitive (this would need to be justified separately).

The question is whether or not support for combo keys should be added.

> The idea of disambiguating based on the next key already appeared when I was reading about homerow mods 
> and it could potentially also be useful in other situations.

I'm not convinced of this.

> (where some people only activate the modifier if the overloaded key is held long enough and the next pressed key is on the other side of the keyboard, hence pressed with a finger on the other hand)

This is an interesting potential optimization for `overload2`. It might be worth breaking out into its own (small) thread for consideration.

> However, so far I thought that this disambiguation could be done using keyd's elegant layer mechanism adding the swallowed letter in hindsight on the activated layer, i.e.
> [...]
> To fix this, one would need to output the swallowed letter and then execute the timeout, for example defining the j key on the li layer in the form
> [li] 
> j = sequence(macro(f), timeout(layer(ri), 25, j))

For a combo timeout of `25ms` where both `f+j` and `j+k` have meaning, the sequence `<f_down> <20ms> <j_down> <10ms> <k_down> <5ms> <f_up>` is inherently ambiguous.  I'm not clear on how your solution addresses this, but I've probably misunderstood something.

I don't think this is a problem in practice given that the sequence is unlikely to occur unless the user simultaneously depresses all three keys (since the chording interval is lower than the normal interkey interval).

In any event, this all seems a bit convoluted and would require the addition of actions which don't necessarily serve any other purpose. If support for this is to be added, it makes more sense to make it first class

E.G:

`a+b = c`

instead of polluting the pool of primitives and requiring obese configs.

> However, all of these solutions don't feel right to me

Agreed.

> I thought about this some more and it appears to me that the described sequence action [...] A combination with layer or oneshot could potentially be useful as well.

If they are actually useful, I would be more inclined to introduce `overload2` and `layer2`. This would need to be discussed in another thread.

> dot = timeout(dot, 200, prepend(dot space, layer(shift)))

If I understand your proposal correctly, this would emit '. ' and then cause `.` to behave like `shift` for the duration of its depression (which doesn't seem particularly useful).

> The crucial point here is that the nearly simultaneous pressing of the keys should activate the layer

That would be the optimal solution, but a fairly close approximation of the desired behaviour can probably be achieved just using overload2.

>  Your proposed solution would apply the same logic as for homerow modifiers, including the restriction that the typing speed has to be within a certain tolerance.

True, but it is not clear that the optimal solution is significantly better. If the user has to hold two keys down, it is hard not to exceed the overload timeout for a single key.

> By the way: Thanks for implementing the helpful -t option.

+1

**Comment by rvaiya** [comment]
Closing in favour of #320.
