### ISSUE TITLE
Feature request: Optionally print raw input events when monitoring

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#321]
When using `keyd monitor`, it would be useful to optionally print the relevant raw input events (key up/down) received from physical keyboards as well, so that one can understand precisely what keyd receives and how this input is processed. As far as I understand, this can not be done by external tools as keyd grabs these keyboards. Alternatively, one could monitor raw inputs by introducing another virtual keyboard (which is then grabbed by keyd), but then it is very cumbersome to merge with the events of the virtual keyd keyboard.

**Comment by rvaiya** [comment]
This is non trivial to implement and only useful for debugging purposes. For debugging configs the current functionality should suffice.

**Comment by rvaiya** [comment]
> Can't this be achieved by just adding some print statements to device_read_event() in device.c

No, since the client can't see events of devices grabbed the by daemon. It would require additional IPC logic. If you just want some additional log output for the daemon (of the kind that used to exist), I will reintroduce them shortly.

> I was interested in the latency added by keyd when writing this request, but probably it is so small that measuring it would require to move to a finer scale than milliseconds.

This should be on the order of microseconds. I've already benchmarked it.
