### ISSUE TITLE
Feature request: optionally deactivate oneshot layers on key up of trigger key

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/keyd#328]
I just learned about a nice feature which makes oneshots usable for emacs users, who regularly hold down a modifier key while pressing multiple other keys: Instead of deactivating the layer on key press of the resolving key, keep it active until that key is released. This way, assuming `control = oneshot(control)`, one could enter C-x C-s by the sequence `<leftcontrol_down> <leftcontrol_up> <x_down> <s_down>`, followed by `<x_up>` and `<s_up>` in arbitrary order. The point here is that the control layer is kept active until `<x_up>` is seen.

Because of the key rolls produced by many fast typists, this is probably only useful for non-shift modifiers, so instead of (or in addition to) a global oneshot mode toggle option, a dedicated oneshot action would be needed.

There is some potential overlap with #280 though, because depending on the planned action you describe there, one could probably achieve almost the same effect by activating the layer until idle for some small amount of time, where idle here not only means that no further input is received, but also that all keys have been released.

**Comment by rvaiya** [comment]
```
[control]

x = overload(control, C-x)
```

**Comment by rvaiya** [comment]
> Already with your solution, as one typically would like to support this behaviour for all letter keys, this would result in 26^2 + 26 = 702 lines in the configuration file, 

The user isn't expected to this for all keys, only a handful of them. This only really makes sense in the context of emacs convoluted stock bindings. In general, the user is unlikely to simultaneously hold down more than one key which needs to be modified.

> However, instead of trying to mix oneshot with hold behaviour, it might in fact be better to solve this problem using a pure oneshot approach like so:
> [...]

Before proposing more actions to solve novel problems, it would be better to ensure that the problems they are intended to address actually exist.

**Comment by rvaiya** [comment]
> I was proposing that only the first non-modifier key has to be held down. So for example after triggering a oneshot(control) (say by tapping a home row key or a combo), the control layer would be kept active as long as the next letter key is held.

That was also my understanding. My point is that this does not seem like generally useful behaviour because most of the time the user does not enter sequences like

`<control down> <control up> <a down> <b down> <a up> <b up>`

for arbitrary `a` and `b`, since sequential modifier activations are relatively rare. Even when they do occur (the goal actually is to type `C-x C-s` in something like emacs), they are usually not close
enough to produce the ambiguous event seqeunce above. For the small number of sequences which actually do meet this criteria, I don't think it is unreasonable to require the user to explicitly define them within a layer.

> In my case, I'm an intensive user of orgmode, where relevant sequences occur regularly. I also regularly use the C-c C-k block for keyboard macros. If I could start over again, I would probably simply remap those bindings, but after decades of use they are so deeply ingrained in my memory that the effort would simply be too high.

I see. 

> I agree that one could go down your proposed route, and also that implementing a fully universal solution is technically not needed here, but as a consequence one would have to make a list of all used keybindings and then later, whenever a new keysequence is encountered, edit the configuration file again.

This is true, but I would regard this as a sufficiently niche use case that first class support is probably unwarranted.

> I wouldn't call this user friendly.

But still possible with a bit of elbow grease.

If you really want this to apply to all keys, it can be achieved with the layer2 action (in the pipeline) which accepts a macro:

```
capslock = oneshot(capslock)

[capslock:C]

a = layer2(capslock, C-a)
b = layer2(capslock, C-b)
```

which has the advantage of not requiring a dedicated layer for each key.

> In contrast to this, the additional actions (which besides are trivial to implement) 

The implementation is not the issue. Each new action adds additional complexity and should be justified by more than a single use case.

>  I don't see why the current use case does not serve as justification.

Because you are the first person to ask about such a feature and it can already be achieved with the existing set of primitives.

> If end user convenience doesn't count, one could also remove oneshot for the sake of minimalism

Oneshot is used ubiquitously and there is no other (non trivial) way to achieve the same effect using other actions. The two are not analogous.

> Apparently our views of the issue differ, which is fine.

Indeed. Ultimately it is a matter of taste.
