### ISSUE TITLE
Question about generating custom keysims

### ISSUE THREAD

**Issue by foolnotion** [rvaiya/keyd#33]
Hi,

I have the following settings in my `xkbmap`:
```
clear mod1
keycode 108 = Mode_switch
keycode 64 = Super_L
keysym e = e E EuroSign
keysym c = c C cent
keysym w = w W adiaeresis Adiaeresis
keysym o = o O odiaeresis Odiaeresis
keysym u = u U udiaeresis Udiaeresis
keysym r = r R ssharp
keysym q = q Q acircumflex Acircumflex
keysym a = a A abreve Abreve
keysym s = s S U0219 U0218
keysym t = t T U021B U021A
keysym i = i I U00EE U00CE
```
and I've tried using keyd to generate the same:
```
rightalt = layer(dia)

[dia]
r = ß
u = ü
o = ö
e = €
...etc...
```

As I understand I cannot use `r = G-r` and so on because `keyd` resets all the `xkbmap` mappings. is it possible to generate these keysims with keyd? perhaps via a macro calling xdotool or something like that?

Thanks.

**Comment by rvaiya** [comment]
The config file does not support unicode so you can't do `u = ü`. Even if this was valid, it would have no meaning since keyd operates at the level of the keycode.  Symbols are handled by the display server (see #31 and #30). My advice would be to use compose key macros to obtain the result you want.

E.G

``` rightalt = layer(dia)

[dia] o = macro(compose o ") e = macro(compose c =) ...  ```

You will have to set the compose key in X for this to work. This can be done with `setxkbmap -option compose:menu` and will need to be done each time you restart keyd (see below).

You can find a list of default compose sequences in `/usr/share/X11/locale/en_US.UTF-8/Compose` (replace en_US-UTF8 with your locale).  '<Multi_key>' corresponds to the compose keycode.

> because keyd resets all the xkbmap mappings.

keyd doesn't reset anything, but it does create and destroy a virtual evdev device each time you restart it. It seems X doesn't preserve mappings when keyboards are unplugged, but this should be less of a problem once you have a config you are happy with. In the meantime you can just do something like `sudo systemctl restart keyd; sleep 2s; setxkbmap -option compose:menu`

**Comment by foolnotion** [comment]
Thank you,  your solution except that I can't produce upper case characters. I tried something like this with no success:
```
[dia]
o = macro(compose o ")

[dia:S]
o = macro(compose O ")
```

**Comment by rvaiya** [comment]
`:S` means that the layer behaves like the supplied modifiers. What you want is a little more involved but can be achieved
by combining the appropriate features like so:

```
rightalt = layer(dia)
shift = layer(shift)
rightshift = layer(shift)

[shift:S]

rightalt = layer(shiftedDia)

[dia]

shift = layer(shiftedDia)
rightshift = layer(shiftedDia)

o = macro(compose o /)
...

[shiftedDia]

o = macro(compose O /)
...
```

This creates a layer called 'shiftedDia' which is accessible by holding down both shift and AltGr (right alt).

**Comment by foolnotion** [comment]
This works perfectly, thanks! May I suggest adding one such example to the man page as it's quite a common use case.

**Comment by rvaiya** [comment]
Thanks for the feedback. Given the recent influx of layout related questions I intend to update the documentation when I have some time.

**Comment by rvaiya** [comment]
There is now first class support for this, so you can do o = ö directly in the config file (provided the xkb option compose:menu is set). See the man page for details.
