### ISSUE TITLE
Dedicated syntax for timeouts

### ISSUE THREAD

**Issue by slakkenhuis** [rvaiya/keyd#333]
Feel free to close this issue without comment if it doesn't feel right --- since it's primarily aesthetic, I don't think it warrants having long back-and-forths ;) That said, this suggestion could inform the decisions in #309 and #320.

@herrsimon's comment about required hold times in #320 gave me an idea: what if `timeout`s were given dedicated syntax in general?

That is, instead of this:

    capslock = timeout(overload(control, esc), 500, overload(control, noop))

... you'd do something like this:

    capslock = overload(control, esc)
    capslock 500ms = overload(control, noop)

The default behaviour would be that intervening events *interrupt* the timeout. *Queueing* behaviour would be achieved with a slight modification, so that you could get the proposed `f = overload2(shift, f, 200)` with something like:

    f = f
    f 200ms queue = overload(shift, f)

In my opinion, this communicates intent rather well and needs minimal reference to the manual. It's succinct and the right-hand side of the configuration stays blissfully low on parentheses and number suffixes and timeout arguments. It has other benefits:

-   Since the second argument of `overload2` will usually just be the 'original' key on that layer, you can often treat the binding for that end of the timeout as optional. So in the above example, you'd really only need `f 200ms queue = overload(shift, f)`, or even just `f 200ms queue = layer(shift)`, which keeps the configuration tidy.

-   As mentioned, it would immediately play well with optional required hold times on combos.

-   Timeouts can only occur as an outer expression anyway, which is a limitation that this syntax would naturally enforce.

-   It skirts the issue of naming ("the real problem is that I made the mistake of naming `timeout`, `timeout`"), and yet it has a fairly obvious (and extensible!) interpretation.

Exact syntax could be different, of course, but I like the general idea.

**Comment by rvaiya** [comment]
I haven't had time to read herrsimon's post yet, but it likely won't alter my position.

> I don't think it warrants having long back-and-forths ;)

Thanks for making this nice and concise :).

> The default behaviour would be that intervening events *interrupt* the timeout. *Queueing* behaviour would be achieved with a slight modification, so that you could get the proposed `f = overload2(shift, f, 200)` with something like:

My problem with this is that it introduces an implicit dependency between different bindings.

Specifically it's not clear how:

> f = f
> f 200ms = overload(shift, f)

differs from:

> f = f
> f 200ms queue = overload(shift, f)

at a glance. 

Assuming the latter is identical to 'overload2', the second binding silently changes the interrupt logic. The behaviour of `f` is now split across multiple statements, the second of which can modify the behaviour of intervening keys in different ways.

This is actually quite unintuitive (imo). I think to those of us that have been steeping in the problem domain, it might at first *appear* simple, but in practice the user is going to have to develop an understanding of several different concepts by reading the man page.

The word `queue` is also a bit of a leaky abstraction, since the queueing is really an implementation detail. A dedicated name like `overload2` (though I agree the name is suboptimal) is more consistent with the existing syntax and better communicates the intended *purpose*. Most users interested in `overload2` will probably have experimented with `overload` and encountered its limitations. `overload2` is the natural progression with a different set of tradeoffs (which can quickly be gleaned from the man page).

> It's succinct and the right-hand side of the configuration stays blissfully low on parentheses and number suffixes and timeout arguments.

The parentheses are a feature, not a bug ;). Nesting is generally a bad sign, but if the user is doing something sufficiently complex, the cost of them is minimal.

> `f 200ms queue = layer(shift)`, 

I'm not convinced this is significantly easier to understand than `overload2(shift, f, 200)`.

> It skirts the issue of naming ("the real problem is that I made the mistake of naming `timeout`, `timeout`"), and yet it has a fairly obvious (and extensible!) interpretation.

I have been meaning to revisit the naming issue, but that should probably be done in another issue.

Feel free to ping me on IRC if you want to iterate in person (or just post here).

**Comment by slakkenhuis** [comment]
The idea of also pulling sequential overloads into the `condition = consequence` paradigm did cross my mind (but surely, `f = overload(shift, f)` would necessitate something more than `f 10s = layer(shift)` unless you want shift activation to take 10 uninterrupted seconds...)  Such things are good to keep in the back of the mind, and the reason I said 'extensible' - but I figured we had better tackle things one at a time. :P

**Comment by slakkenhuis** [comment]
With apologies for the back-and-forth that I promised to save you from! I'll just install IRC on my phone, since we seem to be in different timezones judging by the timestamps ;)

>it introduces an implicit dependency between different bindings

I realize this, and had anticipated that response, were it not for the fact that combos will *also* introduce this dependency. All the user must know is that combos and timeouts create exceptional behaviour. Perhaps `=` could be replaced with `->` or `+=` to emphasize that it mutates another binding. I really feel that the tradeoff is worth it, but see your point.

>in practice the user is going to have to develop an understanding of several different concepts

This is unavoidable once you allow the user access to timeouts. It's better to give it to 'em plain. With my suggestion, the crucial question will at least be confined to a single spot, with only one clear yes-or-no (while you hold this key, would pressing another key cancel the timeout or not?), as opposed to the question being hidden in operators that end up forcing users to either reverse-engineer the question, or blindly try stuff without understanding the manual.

I suppose that you want users to pick an overload based on whether the key is often struck in isolation or in sequence. But it's futile to try to hide from them that the solution is to add a timeout with a queue. After all, they have to provide a timeout value! And where does this latency come from? Best to avoid mysterious primitives and instead provide short but sufficient directions in the manual.

>I'm not convinced this is significantly easier to understand

On its own, I agree that it's not much better. But it should be easier to grok in the context of the whole manual, because it would use the same syntax every time.

Anyway, I just wanted to float the idea. In the end, it's a matter of taste. Let's reopen the issue once you've also seen in your mind's eye all the squeaky clean configs that could have been ;) 

* * *

>Shift triggers as soon as another key is pressed before the timeout

No, the timeout would be cancelled. For the purpose of this issue, `overload` is safe!

>It would be nice if we could all discuss in realtime at some point. 
+1

**Comment by slakkenhuis** [comment]
I know I closed the thread, but on second thought I'd make `queue` the default, so that

    f = overload2(shift, f, 200)

becomes

    f 200ms += layer(shift)

and

    capslock = timeout(overload(control, esc), 500, layer(control))

becomes

    capslock = overload(control, esc)
    capslock 500ms cancel += layer(control)

That should cause less confusion about purpose and implementation details.

**Comment by slakkenhuis** [comment]
Extensions and syntactic variations are possible, but it was an intentional decision not to elaborate on them, because they would at this point distract from the question of whether splitting the timeout into multiple statements is intuitive in the first place.

I strongly feel that it is (primarily because it's consistent with combo notation, with many pleasing side effects), but in the end, such feelings can't really be argued, which led me to close the issue.

> This is true but the problem only occurs on the same layer

That's not necessarily true. You could add a timeout to a key that inherited its mapping from another layer. I don't think that's a problem, but some way of emphasizing the dependency via `+=` or your functional syntax would be a good idea.

> realtime chat 

Yeah, I should finally be in the channel on my phone now, so we can chat there.
