### ISSUE TITLE
How to use a single key as multiple modifier keys in keyd 2?

### ISSUE THREAD

**Issue by contrun** [rvaiya/keyd#334]
I recently migrate keyd 1 to keyd 2.

I previously used left super as super+alt by the configuration
```
capslock = layer(C)
rightalt = layer(A)
leftmeta = layer(M-A)
rightmeta = oneshot(G)
rightcontrol = layer(M)
```

I tried to archive the same in keyd 2.4.2 with the configuation
```
[ids]
*

[main]
capslock = layer(control)
rightalt = layer(alt)
leftmeta = layer(meta+alt)
rightmeta = oneshot(altgr)
rightcontrol = layer(meta)
```

But I have the following error `ERROR parsing /etc/keyd/keyd.conf:7: meta+alt is not a valid layer`. It seems layer `meta` was recognized, while layer `meta+alt` was not recognized.

What is the proper way to map a single key to multiple modifer keys?

**Comment by contrun** [comment]
```
[ids]
*

[main]
capslock = layer(control)
rightalt = layer(alt)
leftmeta = layer(metaalt)
rightmeta = oneshot(altgr)
rightcontrol = layer(meta)

[metaalt:M-A]
```
does what I want. I think being able to specify `leftmeta = layer(meta+alt)` would be better, but feel free to close this issue as what I want is indeed possible.

**Comment by slakkenhuis** [comment]
Glad you found the solution!

> I think being able to specify `leftmeta = layer(meta+alt)` would be better

The reason that doesn't work is that layers are not the same as modifiers. The distinction between them used to be more blurry, so that you could do `layer(M-A)`, but that caused issues.

However, because it has since become possible to compose layers `a+b` by pressing keys for `layer(a)` and `layer(b)` simultaneously, with associated modifiers stacking correctly, I do think it makes sense to allow a single key to activate multiple layers. rvaiya, what do you think?

**Comment by rvaiya** [comment]
> , I do think it makes sense to allow a single key to activate multiple layers. 

This adds a lot of additional complexity for little gain. Simultaneously activating multiple layers usually makes little sense. The reason most people usually want to do it, is to activate multiple modifiers, which is best achieved by creating a dedicated layer with the desired modifiers (which also supplies a natural place to supply overrides).
