### ISSUE TITLE
character wrongly inserted when overloading and holding capslock

### ISSUE THREAD

**Issue by lacygoill** [rvaiya/keyd#351]
**Steps to reproduce**

Write this in `/etc/keyd/default.conf`:

    [ids]
    *
    [main]
    capslock = overload(control, esc)

(Re)start the keyd service:

    $ sudo systemctl restart keyd

Tap `l`, then press `Escape` almost immediately afterward.
As long as `Escape` is held, `l` keeps being inserted.

**Expected behavior**

Nothing is inserted while `Escape` is being held.

**Version of keyd**

`$ keyd --version`: keyd v2.4.2 (8fc5eb9)

**Environment**

Operating system: Ubuntu 20.04.4 LTS

**Additional context**

For the issue to be reproduced, `Escape` must be held very quickly after releasing `l`.

---

The issue is not specific to `l`.  It can be reproduced with other characters, like `m`.

---

I haven't followed the purpose of the latest commits closely enough to be sure that it's a bug.  That said, the new behavior started from [this commit](https://github.com/rvaiya/keyd/commit/f721f1104b8cce5c1642cb9f9b7aea45332b4b83).

**Comment by rvaiya** [comment]
Are you suggesting that `l` *never* gets released if you do

```
l down
capslock down
l up
capslock up
```
?

Or simply that it doesn't get released until you release capslock? If it is the latter, then this is expected behaviour since f721f11. The new behaviour is to use the same queuing logic as `overloadt` which means the overloaded key isn't resolved until key up (`capslock up` in this case). Is this causing a real usability issue?

**Comment by rvaiya** [comment]
`<l down> <l up> <capslock down>` should definitely not produce an extraneous `l`, but `<l down> <capslock down> <l up> <x ms> <capslock up>` will for `x > repeat_interval`, since `<l up>` gets queued after `<capslock down>`. You can verify this using `keyd monitor` while reproducing the behaviour. If the first sequence is producing the behaviour you describe, then it is a bug.

> There have been quite a lot of work in the recent weeks, and I didn't have the time to keep up with all the changes. Maybe I should use a different function than overload().

If you are running from master, things are liable to occasionally break. If you need stability it is better to run the latest release, though I would appreciate your assistance in tracking down the bug (if there is one).

> It's still unexpected. Is there a way to restore the old behavior? Maybe by using a different function than overload()?

Not at the moment. The new behaviour generally shouldn't cause any problems since it requires you to tap and hold the overloaded key before key up of the last key and for a period of time exceeding the repeat interval. Have you changed the default repeat interval?

**Comment by rvaiya** [comment]
> I'm not sure what the "default repeat interval" is.

Sorry, I should have been more explicit. I was indeed referring to the display server repeat delay. I was trying to establish whether or not you had lowered the default X repeat delay (which it appears you have), since that would increase the likelihood of encountering the behaviour your describe. I have not noticed this problem in my personal use.

The justification for the current behaviour is as follows:

```
l down
capslock down
l up
capslock up
```

is inherently ambiguous until `capslock up`, since `capslock` may correspond to either `control` or `esc` depending on whether or not any intervening keys are pressed.

If capslock is interpreted as `control`, then the corresponding output sequence should be:

```
l down
control down
l up
control up
```

if it is `esc`, then the correct sequence is:

```
l down
esc down
l up
esc up
```

Thus producing the correct output sequence requires waiting until `capslock` is resolved, which in this case means waiting until it has been released. A byproduct of this is that the intervening `l up` event gets queued until this happens.

The old behaviour was to eagerly propagate the intervening key up and transpose the output order, producing:

```
l down
l up
esc down
esc up
```

which is less faithful to the original input sequence (and arguably 'less correct'). This might seem like a trivial distinction, but preserving event order has important implications when timeouts are used for resolution (as in `overloadt`).

The old approach had the side effect of eliminating the possibility of the display server generating repeat events in the event that `capslock` was struck before `l` was released but held longer than the repeat delay. 

Having said that, I am not necessarily opposed to reverting to the old behaviour for vanilla `overload` since it appears at least some people were relying on the old behaviour, and I can't think of any real world use cases in which the correct output is objectively better.

**Comment by rvaiya** [comment]
@lacygoill I believe this should be fixed in the latest commit.

**Comment by lacygoill** [comment]
I can confirm that dd53208650ebffcf285984291c49c6cb497eb855 fixes the issue.  It's very much appreciated.  Thank you very much.
