### ISSUE TITLE
does keyd support binding mouse wheel scroll event?

### ISSUE THREAD

**Issue by kyon328** [rvaiya/keyd#377]
I checked with `keyd -l` only find 5 mouse relate keys, `mouse1` and `mouse2` I think represent those 2 addition buttons on my mouse which not really use often
do I miss sth?
or keyd still not support binding mouse wheel?

**Comment by rvaiya** [comment]
Scroll events are not treated as buttons (this is an X notion). Improved mouse support (including support for scrolling) should be introduced soon, though it is currently unsupported.

**Comment by Binly42** [comment]
> Is scroll wheel still unsupported? I saw some references of `REL_WHEEL` in source code, but I'm unable to make it work (like hold left-button and scroll wheel to change audio volume).

seems still not yet. (I just walked through the near commits ~

**Comment by rvaiya** [comment]
Unfortunately this is still unsupported. The code you are seeing relates to propagating scroll events though to higher levels of the input stack when a mouse is managed by keyd (mouse support is itself still experimental).

**Comment by tkna91** [comment]
@pangyulei @rvaiya Please reopen this issue.
keyd's ability to control the mouse wheel has the following possibilities, for example
* Operations in audio and video editors
  - Scrolling on the time axis
  - Adjustment of parameters such as brightness, contrast, volume, left/right balance (pan), etc.
* Manipulation in synthesizers, quick setting of parameters such as track volume, pan, ADSR, etc. through MIDI protocol

This is only part of the story; the ability to handle arbitrary parameters through keys and commands in keyd has great potential to dramatically increase the efficiency of operations to the software.

**Comment by DexGith** [comment]
> [@pangyulei](https://github.com/pangyulei) [@rvaiya](https://github.com/rvaiya) Can you re-open this issue? I feel it would be better if the title was changed to something like “Scroll wheel support”.
> 
> keyd's ability to control the mouse wheel has the following possibilities, for example
> 
>     * Operations in audio and video editors
>       
>       * Scrolling on the time axis
>       * Adjustment of parameters such as brightness, contrast, volume, left/right balance (pan), etc.
> 
>     * Manipulation in synthesizers, quick setting of parameters such as track volume, pan, ADSR, etc. through MIDI protocol
> 
> 
> This is only part of the story; the ability to handle arbitrary parameters through keys and commands in keyd has great potential to dramatically increase the efficiency of operations to the software.

I'm looking for a method to send scroll wheel and mouse movements through the mouse with keyd

Are there any new updates to achieve these results ? [Feature request]: functions or mouse wheels and mouse movements for keyd
[#1070](https://github.com/rvaiya/keyd/issues/1070)

**Comment by pangyulei** [comment]
> [@pangyulei](https://github.com/pangyulei) [@rvaiya](https://github.com/rvaiya) Can you re-open this issue? I feel it would be better if the title was changed to something like “Scroll wheel support”.
> 
> keyd's ability to control the mouse wheel has the following possibilities, for example
> 
> * Operations in audio and video editors
>   
>   * Scrolling on the time axis
>   * Adjustment of parameters such as brightness, contrast, volume, left/right balance (pan), etc.
> * Manipulation in synthesizers, quick setting of parameters such as track volume, pan, ADSR, etc. through MIDI protocol
> 
> This is only part of the story; the ability to handle arbitrary parameters through keys and commands in keyd has great potential to dramatically increase the efficiency of operations to the software.

already re-open this issue, XD

**Comment by tkna91** [comment]
Yes, you can use that method to set the output of Remap to the scroll wheel.
However, if you want to set the input of Remap to the scroll wheel, it will still be a problem.

**Comment by tkna91** [comment]
It seems this is already possible. great.

https://github.com/rvaiya/keyd/blob/master/docs/CHANGELOG.md#v260

- Added support for scroll remapping

Example:
```
scrolldown = a
scrollup = b
a = scrolldown
b = scrollup
```
@pangyulei @rvaiya This issue can probably be closed.

**Comment by AndydeCleyre** [comment]
Maybe I'm not doing this right, but I've not yet successfully mapped `capslock`+`scrollup` and `capslock`+`scrolldown` to `super`+`=` and `super`+`-`. My attempt looks like:

```ini
[ids]
*

[main]
capslock = overloadt(capslock, `, 310)

[capslock]
scrollup = M-=
scrollup = M--
```

Monitoring scroll down (trackpad) looks like (duplicate lines removed):

<details>
<summary>Debug log</summary>

```console
$ KEYD_DEBUG=1 keyd monitor
DEBUG: src/keyd.c:248: Debug mode activated
DEBUG: src/device.c:190: capabilities of /dev/input/event11 (keyd virtual pointer): b
DEBUG: src/device.c:190: capabilities of /dev/input/event10 (keyd virtual keyboard): c
DEBUG: src/device.c:190: capabilities of /dev/input/event9 (HD-Audio Generic Headphone): 0
DEBUG: src/device.c:190: capabilities of /dev/input/event8 (HD-Audio Generic Mic): 0
DEBUG: src/device.c:190: capabilities of /dev/input/event7 (HD-Audio Generic HDMI/DP,pcm=3): 0
DEBUG: src/device.c:190: capabilities of /dev/input/event6 (06CB0001:00 06CB:CE78 Touchpad): b
DEBUG: src/device.c:190: capabilities of /dev/input/event5 (06CB0001:00 06CB:CE78 Mouse): 9
DEBUG: src/device.c:190: capabilities of /dev/input/event4 (Ideapad extra buttons): c
DEBUG: src/device.c:190: capabilities of /dev/input/event3 (Video Bus): c
DEBUG: src/device.c:190: capabilities of /dev/input/event2 (AT Translated Set 2 keyboard): c
DEBUG: src/device.c:190: capabilities of /dev/input/event1 (Lid Switch): 0
DEBUG: src/device.c:190: capabilities of /dev/input/event0 (Power Button): 8
device added: 0fac:1ade:d2b36ae6 keyd virtual pointer (/dev/input/event11)
device added: 0fac:0ade:bea394c0 keyd virtual keyboard (/dev/input/event10)
device added: 06cb:ce78:20ade6e3 06CB0001:00 06CB:CE78 Touchpad (/dev/input/event6)
device added: 06cb:ce78:7a4f004f 06CB0001:00 06CB:CE78 Mouse (/dev/input/event5)
device added: 0000:0000:be30eaf0 Ideapad extra buttons (/dev/input/event4)
device added: 0000:0006:bdb72f48 Video Bus (/dev/input/event3)
device added: 0001:0001:09b4e68d AT Translated Set 2 keyboard (/dev/input/event2)
device added: 0000:0001:48a093aa Power Button (/dev/input/event0)
keyd virtual keyboard 0fac:0ade:bea394c0  enter up
DEBUG: src/device.c:498: Unrecognized EV_ABS code: 2f
DEBUG: src/device.c:498: Unrecognized EV_ABS code: 39
DEBUG: src/device.c:498: Unrecognized EV_ABS code: 35
DEBUG: src/device.c:498: Unrecognized EV_ABS code: 36
DEBUG: src/device.c:607: unsupported evdev code: 0x14a
DEBUG: src/device.c:607: unsupported evdev code: 0x145
DEBUG: src/device.c:607: unsupported evdev code: 0x14d
```

</details>

**Comment by tkna91** [comment]
@AndydeCleyre Is trackpad scrolling represented in `keyd monitor`?
I suspect trackpad scrolling and mouse wheel scrolling are distinct actions.

**Comment by AndydeCleyre** [comment]
@tkna91 With debugging off, no. With debugging on, lots of those `Unrecognized` and `unsupported` lines from the above log sample.

**Comment by tkna91** [comment]
In other words, that's off-topic here.
I apologize if I'm mistaken, but the trackpad should be unsupported.

**Comment by gitdexgit** [comment]
Doesn't work without sending actual commands... 

Send command as in 2 ways, either you map a key like, "Use keyd list to see the list of keys" as in 

This is a clever method that assigns some keyboard keys and use those in xbindkeys. Sadly there is a limited amount of keys and some may not work well.

for example:

```
# xdotool click 4 = scroll up
s = zenkakuhankaku
```

And you map that key in xbindkeys This will make it work in any user who has that binding. 

---

Or you can send the command directly, sadly this is user specific, for example

you can also map it out with ctrl+scrollup or down very useful. As in:

```
r = command(sudo -u <PUT_YOUR_USER_HERE> DISPLAY=:0 xdotool keydown ctrl click 4 keyup ctrl)
t = command(sudo -u <PUT_YOUR_USER_HERE> DISPLAY=:0 xdotool keydown ctrl click 5 keyup ctrl)
```

I don't know how to make it non user specific but I only have 1 user most of the time.

**Comment by ArtskydJ** [comment]
> @AndydeCleyre Maybe I'm not doing this right, but I've not yet successfully mapped `capslock`+`scrollup` and `capslock`+`scrolldown` to `super`+`=` and `super`+`-`.

For what it's worth, this config is working for me for an external mouse (but not the built-in trackpad with two-finger scrolling) to change the volume with capslock/scroll:
```ini
[ids]
*

[main]
capslock = layer(caps_lock_layer)
mouse1 = layer(mouse_side_button_layer)

[caps_lock_layer]
scrollup = volumeup
scrolldown = volumedown

[mouse_side_button_layer]
scrollup = volumeup
scrolldown = volumedown
```

**Comment by gitdexgit** [comment]
**Thank you so much Scroll wheel support is included in keyd. I wonder when? I don't remember it was included before. Please close this feature request.**

**my new one is  thanks to you**

```
s = scrollup
d = scrolldown
f = scrollright
a = scrollleft
```

**My old config was lol** 

```
# d = katakana
# s = katakanahiragana
# a = katakanahiragana
# f = hiragana
```

then those keys are bound in xbindkeys heheheh...

```
# ----- Scroll wheels movements-------

# "xdotool click 5"
# Katakana

# "xdotool click 4"
# XF86TouchpadToggle
#
# "xdotool click 7"
# Hiragana

# "xdotool click 6"
# Hiragana_Katakana
```

# still waiting for next feature request, relative mouse movements

Sadly still waiting for relative mouse movements in keyd For now I'm using keyd extra keys to map those with xbindkeys

```
# ------- relative mouse movements ---------------

# yen 
# yen = m:0x0 + c:132
# capslock + x then + h
"xdotool mousemove_relative -- -20 0"
m:0x0 + c:132

```

**Comment by tkna91** [comment]
> still waiting for next feature request, relative mouse movements

You might want to follow this https://github.com/rvaiya/keyd/issues/317

**Comment by gitdexgit** [comment]
The issue here is the following: 

1) First issue

```
# Doesn't work I have you sudo -u $USER type it manually.
# h = command(xdotool mousemove_relative -- -20 0)
h = command(sudo -u dex DISPLAY=:0 xdotool mousemove_relative -- -20 0)
```

I do only use dex user for stuff like this but I do have other VMs and maybe potentially other users... I would love to be able to have something in github that I can simply git clone and copy. Sadly I would have to make a complementary script that uses `sed` to check if the user is indeed dex if not pick the user name and run it through the /etc/keyd config to change the command(sudo -u dex .... to the current acutal user username... But that's too much trouble.


2) second issue --> even if you do h = command.... and make it relative mouse move... You can't hold h you have to tap tap tap tap... Which is annoying... You don't have that problem if you bound it to japanese keys that you don't use...

---

Regardless of 1 or 2.... I find myself never using those relative mouse moves anyways I'm about to delete them. The user of  `warpd --hint` is the right implementation for sure... 

Sadly warpd needs to get a little bit better and optimized but so far the warpd project solves it better. I only use the warpd --hint.... the normal mode is also a fine issue but I prefer the warpd --hint as I can type on keyboard faster. 


So far I'm using the follwing "xdotool mousemove_relative -- 0 5" with relative 5; because `warpd` hints needs more I'd say an option to increase the precision of --hint. The mouse movement is a bit faster for me in `warpd` but I think you can change the sensetifity and remove momentum in the .config/warpd....

**Comment by D-u-c-k-s-e-l** [comment]
I have ran into a strange bug involving the `scrollup` and `scrolldown` mappings.

I recently obtained a trackball mouse and wanted it to scroll horizontally when holding Super (I use Niri), but vertically in regular use. I tried using this config, but it seems that keyd doesn't support sending modifiers connected to scroll events.

```ini
[ids]
*
-047d:80d7
[meta]
scrollup = macro(M-S-scrollup)
scrolldown = macro(M-S-scrolldown)
[meta+shift]
scrollup = macro(M-S-scrollup)
scrolldown = macro(M-S-scrolldown)
```

Note that this config actually remaps all *but* the device I'm trying to change. This should produce the effect I desire with a few small changes to my Niri config (swapping mod+scroll with mod+shift+scroll there too), however, when I press Super then scroll down, the WM does not receive super+shift+scroll. It seems keyd is not remapping this.

When I try instead with this config:

```ini
[ids]
*
-047d:80d7
[meta]
scrollup = macro(M-k)
scrolldown = macro(M-j)
[meta+shift]
scrollup = macro(M-h)
scrolldown = macro(M-l)
```

This does achieve something near the desired effect (wherein it is now sending keys to the compositor that will walk across the windows), though it is not sending scroll events to my compositor (which would be useful for more extensive keybindings). I suppose I could continue to make my keyd config longer (adding a `[meta+shift+control]` and so forth), but I feel like this is likely an issue with keyd, rather than something that should require extra effort on my part.

Other notes:
- Keyd is version 2.6.0
- I am using my NixOS config's `services.keyd` to configure keyd, however, I am copying the outputted config files into this comment. NixOS is version `26.05.20260306.aca4d95 (Yarara)`.
