### ISSUE TITLE
ThinkPad: Remap TrackPoint mouse buttons, but preserve middlemouse+TrackPoint scrolling?

### ISSUE THREAD

**Issue by humanplayer2** [rvaiya/keyd#383]
For mouse, I mainly use my ThinkPad's TrackPoint. Very handy is the default scrolling by holding `middlemouse` and moving the TrackPoint up and down.

The middle mouse button on a ThinkPad is in a lovely position to be used for overloading into a layer.

Adding my mouse ID to the `[ids]` section of `default.conf` annuls the `middlemouse` scrolling (I suppose as `middlemouse` is no longer registered as a press by `TPPS/2 TrackPoint Elan`, but by `keyd virtual pointer`?).

Is there a way to retain the TrackPoint scrolling while remapping the button?

**Comment by rvaiya** [comment]
> I suppose as middlemouse is no longer registered as a press by TPPS/2 TrackPoint Elan, but by keyd virtual pointer?.

Indeed, this is the crux of the problem.

middle mouse/scroll functionality is handled higher up the input stack by (I believe) libinput which implements makes allowances for specific hardware like the thinkpad trackpoint.


> Is there a way to retain the TrackPoint scrolling while remapping the button?

I've added two experimental actions (subject to change) to the latest commit: `scroll(<sensitivity>)` and `scrollt(<sensitivity>)` which turn the mouse into a dedicated scroll device (the second acting as a toggle). `<sensitivity>` is the number of mouse units which correspond to a scroll unit (a higher value corresponds to a slower scrolling speed), so you can do something like this:


```
[main]

middlemouse = scroll(20)
```

to preserve the old middle mouse behaviour while still remapping the other mouse buttons.

Note: Mouse support in keyd is still experimental and generally advised against (trackpads in particular are unsupported).

**Comment by giddie** [comment]
This seems like a promising approach in terms of configurability. A couple of points for feedback:

* The `scroll` function seems to scroll stepwise (i.e. it jumps up and down by a number of pixels) instead of smooth. When using the built-in libinput scrolling button feature, the scrolling is smooth - you can scroll single pixels if you move slowly enough.

* The built-in libinput feature allows the "scrolling button" to act as a normal button when tapped. To replicate this behaviour, I tried `rightmouse = overload(scroll(20), rightmouse)`, but that didn't work. Maybe the scroll function doesn't count as a layer?

**Comment by rvaiya** [comment]
> I was hoping that I could hold middlemouse to activate a layer, but also use it for scrolling. I can understand why such a mixed button would require a non-experimental mouse support.
> [...]
> The built-in libinput feature allows the "scrolling button" to act as a normal button when tapped. To replicate this behaviour, I tried rightmouse = overload(scroll(20), rightmouse), but that didn't work. 

Indeed, `scroll` is not a layer (or even an official action yet :P).

>The scroll() action results in jaggy scrolling in a few applications (I have been unable to solve this by adjusting the sensitivity). The inbox of Evolution is one, and the text area in LyX is another.
>[....]
>The scroll function seems to scroll stepwise (i.e. it jumps up and down by a number of pixels) instead of smooth.

Implementing smooth scrolling in keyd is non trivial, since it relies on coordination between several different parts of the input stack. The correct solution to this is to propagate the trackpad events and let libinput handle it, but doing this selectively (i.e exclusively capturing button events) will require some changes to the core input handling logic. 

I am currently working on some other changes which should indirectly address both of these problems.

**Comment by giddie** [comment]
I'm curious to know if you think libei will help with some of these complexities?

https://libinput.pages.freedesktop.org/libei/

**Comment by rvaiya** [comment]
@giddie My understanding is that libei is effectively a compositor level uinput replacement. If it is widely adopted it might be useful as an alternative output sink for keyd, but it isn't directly related to the mouse problem. 

The main issue is that libinput does a lot of post processing of kernel events to account for differences in hardware (mice do weird things). Much of the post processing involves special rules ('quirks') for hardware based on product/vendor ids which are not visible to the compositor once keyd grabs them.

**Comment by giddie** [comment]
Yeah, so my understanding is that libei is designed to solve this problem by being a more friendly interface for synthetic input (i.e. no hardware quirks code getting in the way), but the problem is that it requires support from the compositor, as you pointed out.

It seems like libinput wasn't designed with complex filtering / remixing of events in mind, and things could get messy working around its limitations in this regard?

**Comment by rvaiya** [comment]
> Yeah, so my understanding is that libei is designed to solve this problem by being a more friendly interface for synthetic input

The problem isn't event synthesis, but interpreting the original input events, which is what libinput is designed to do. Even if libei were capable of interpreting raw evdev events (I assume it has its own format), it would still need access to the original device properties, which are hidden behind the keyd virtual device.
