### ISSUE TITLE
How to enhance German umlaute?

### ISSUE THREAD

**Issue by Visual-Dawg** [rvaiya/keyd#452]
Hey, first of all thank you for this awesome tool!

I struggle a bit with the setup though:
I want to create four mappings to get easier access to the bracket keys on a German layout:
```
// Just for demonstration
control + ö = [
control + ä = ]

control + alt + ö = {
control + alt + ä = }
```
The key codes for `ö` and `ä` are `;` and `'`respectively. (Derived from `keyd -m`) 

So I tried the following snippet:
```
control + ; = [
control + ' = ]

control + alt + ; = {
control + alt + ' = }
```
But with this nothing gets printed when I press `ö`or `ä`with `control` and *or* `alt`.

Then I tried this:
```
[alt]
; = [    // Turns into `ü`, thus remains unchanged
' = ]    // Turns into `+`

[control+alt]
; = {    // Turns into `Ü`
' = }    // Turns into `*`
```

What am I doing wrong? I read through the docs and both ways should work according to my understanding.

**Comment by slakkenhuis** [comment]
Your first attempt uses chords rather than modifier layers: despite appearances, `control + ;` doesn't make something happen when you press your key while *holding* the control modifier; it makes something happen when you strike the leftcontrol key and the `;` key *simultaneously*.

The second attempt is closer to what you probably want. My guess is that it doesn't work because the names of the keys don't correspond to how your display server interprets those keys. `keyd` operates on the level of keycodes and knows nothing about such things.

Just as `;` on the left-hand side corresponds to your `ö`, `[` on the right-hand side corresponds to `ü`. So, if you press the actual `[` key on your keyboard, what does `keyd -m` tell you it is? That's probably the one you should use on the right-hand side.

**Comment by Visual-Dawg** [comment]
@herrsimon Yes true, I will switch my layout.
