### ISSUE TITLE
overloadt2 -  activate layer also when a chord intervenes 

### ISSUE THREAD

**Issue by matcls** [rvaiya/keyd#468]
overloadt2 activates the layer when a key is tapped while holding the key
for chords the layer is not activated until the timeout exipires
It would be more consistent to activate the layer when a chord intervenes

e.g. to get "test" must press "a" for 500ms until the layer is activated, pressing the chord before the timeout the result is C-c
the expected result would be "test"

```
[main]
w+e = macro(C-c)
a = overloadt2(layer, a, 500)

[layer]
w+e = macro(test)
```

**Comment by rvaiya** [comment]
This works as expected. The problem is that you have the same chord (`w+e`) defined both in `main` and `layer`, so chord resolution happens in the main layer before the `layer` is activated.

That said, mixing timeouts and chord like this is probably a bad idea in the first place. Unless your config is bursting at the seems, it is probably both less ambiguous and more ergonomic to just assign `macro(test)` to a single key in `layer`.

**Comment by matcls** [comment]
> you have the same chord (`w+e`) defined both in `main` and `layer`

oh right , it only occurs if there are overlapping chords 
It seemed counter-intuitive to me because tapping a key activates the layer

Thank you rvaiya
