### ISSUE TITLE
100% CPU usage

### ISSUE THREAD

**Issue by ivan-volnov** [rvaiya/keyd#472]
Hi!

Keyd uses 100% CPU all time.
Although it works.

```
❯ pkg info keyd
keyd-2.4.2_1
Name           : keyd
Version        : 2.4.2_1
Installed on   : Sun Apr  2 15:49:39 2023 CST
Origin         : sysutils/keyd
Architecture   : FreeBSD:13:amd64
Prefix         : /usr/local
Categories     : sysutils
Licenses       : MIT
Maintainer     : jbeich@FreeBSD.org
WWW            : https://github.com/rvaiya/keyd
Comment        : Key remapping daemon for evdev
Options        :
	DOCS           : on
	EXAMPLES       : on
	MANPAGES       : on
Shared Libs required:
	libinotify.so.0
Annotations    :
	FreeBSD_version: 1301000
	repo_type      : binary
	repository     : FreeBSD
```

**Comment by ivan-volnov** [comment]
The issue is config-agnostic but here is my config:

```
[ids]
0c45:1a0a

[main]
leftmeta = layer(meta_mac)
leftcontrol = layer(ctrl_mac)

[meta_mac:M]
c = C-c
v = C-v
x = C-x
left = home
right = end

[ctrl_mac:C]
c = M-c
v = M-v
x = M-x
```

**Comment by ivan-volnov** [comment]
It also loads CPU to 100% on the last master version.

**Comment by ivan-volnov** [comment]
I guess this is why:
https://github.com/rvaiya/keyd/issues/397#issuecomment-1493293182

**Comment by juhaku** [comment]
This happens to me as well. `keyd-application-mapper` is taking 1 cpu core capping 100% all the time. Not sure what has happened but I belive this started within 2 weeks after latest upgrade of the system.
![image](https://user-images.githubusercontent.com/26358664/229587000-05291d12-9d37-4de8-9a2f-3f345e4cc40f.png)

The keymaps work though, but because this is making the computer yell all the time I am considering finding an alternative to the application.

**Comment by rvaiya** [comment]
@ivan-volnov I believe this should be fixed in the latest commit.

@juhaku I believe these are unrealted issues. Can you create a separate issue with the details of your config and your OS/DE?

**Comment by juhaku** [comment]
@rvaiya okay sure,

**Comment by rvaiya** [comment]
I'm assuming this was fixed. Feel free to reopen the issue if not.
