### ISSUE TITLE
max chords exceeded(64)

### ISSUE THREAD

**Issue by dlip** [rvaiya/keyd#536]
I'm impleting an interesting layout called [taipo](https://inkeys.wiki/en/keymaps/taipo) that uses a lot of chords. I noticed you increased the maximum number of chords in #450, is it possible to expose a config for this so we can increase it if necessary? Or otherwise increase it for my usecase (512)?

**Comment by jytou** [comment]
As a side note, it seems to me that the current implementation is not suited for a massive number of chords: https://github.com/rvaiya/keyd/blob/master/src/config.c#L202
There might be some optimization to be done there (using a hash table seems a must if there are a lot of chords), otherwise, it will loop on the chords array at every key press, which could become a problem if there were thousands of chords or more…

**Comment by rvaiya** [comment]
> is it possible to expose a config for this so we can increase it if necessary? Or otherwise increase it for my usecase (512)

At the moment everything is statically allocated for reasons of efficiency. Increasing the default limit to 512 would drastically blow up memory usage. For now I am inclined to suggest just increasing it in your local copy. The next major release should allocate things a bit more intelligently to make these limits more flexible.

> Using a hash table seems a must if there are a lot of chords

The chord limit is already quite high (> 32), the vast majority of people will have between 0 and 10 chords (per layer). In either case, the overhead of a hash table is likely to be more expensive until you get into the 1000s.
