### ISSUE TITLE
`ctrl-backspace` not working after swapping the `fn` and `ctrl` keys

### ISSUE THREAD

**Issue by ElSamhaa** [rvaiya/keyd#549]
Hey, I have an Asahi linux installed on an M1. I am using the below config to swap the `fn` and `ctrl` keys:

```
[ids]
*

[main]
fn = layer(control)
leftcontrol = fn
```

2 observations I had after applying the above config:
1. `ctrl-backspace` no longer deletes one word to the left.
2. In a text field, `ctrl-shift-left` selects all characters until the start of the text field instead of just selecting up to the start of the current line.

I understand that I can play a little with macros, but I'd really like to use the native functionality to preserve the contextual behaviors of these keybindings; i.e. they should natively behave differently in vim than in a Firefox window.

**Comment by luetage** [comment]
Shouldn’t `Ctrl–Shift–Left` select only to the beginning of the current word? Anyway, to me this would indicate your fn key still submits fn, because `fn–Left` submits HOME on some hardware, which goes to the beginning of the line and Shift selects. Use the keyd monitor functionality to find out what the output really is.

**Comment by ElSamhaa** [comment]
@luetage It's swapped already, and `fn` acts as `ctrl`. It's the 2 observations that I'm concerned to report. As for #401, it holds true for certain OEMs like Lenovo. However, for Apple, I think that's not available unfortunately except from within MacOS itself (the first thing I did after getting my M1 😃).

**Comment by rxhfcy** [comment]
> Use the keyd monitor functionality to find out what the output really is.

@ElSamhaa Can you test this too and verify you're seeing what I'm seeing?
- #comment your rules (/etc/keyd/default.conf)
- sudo keyd -m
- press (and hold) the `fn` key
- press `backspace`
- press `left`
- release `fn`

I get the following output ("delete" instead of "backspace", "home" instead of "left"), which would indicate that the macbook is not sending the original keys for backspace and arrow keys when `fn` is held down (I'm using Fedora Asahi Remix on an M1 MacBook Air)
```
keyd virtual keyboard   0fac:0ade       fn down
keyd virtual keyboard   0fac:0ade       delete down
keyd virtual keyboard   0fac:0ade       delete up
keyd virtual keyboard   0fac:0ade       home down
keyd virtual keyboard   0fac:0ade       home up
keyd virtual keyboard   0fac:0ade       fn up
```

**Comment by ElSamhaa** [comment]
@rxhfcy yep, exactly the same with me. I'm on the fedora Asahi remix too btw.

**Comment by rxhfcy** [comment]
@ElSamhaa great, so this issue can be closed then (not a keyd bug but a feature of the Asahi Linux kernel)

PS. About your earlier comment:
> However, for Apple, I think that's not available unfortunately except from within MacOS itself

Luckily, that's not true. Here's a pretty easy way to swap `fn` and `control` in Fedora Asahi Remix (permanently, you can later undo this by using `hid_apple.swap_fn_leftctrl=0` instead of `hid_apple.swap_fn_leftctrl=1` if you want):
```shell
sudo grubby --update-kernel=ALL --args="hid_apple.swap_fn_leftctrl=1"
```

...and then reboot. Or if you want to see the effect immediately, you can do this too (not permanent):
```shell
echo 0 | sudo tee /sys/module/hid_apple/parameters/swap_fn_leftctrl
```

**Comment by ElSamhaa** [comment]
Thank you. I'll try that soon. Closing this issue now.
