### ISSUE TITLE
Implementing layered tap dance

### ISSUE THREAD

**Issue by joihn** [rvaiya/keyd#566]
Hi,
thanks for this tool,
I encountered a bug with `oneshotm` and inherited modifer

**reproduction:**
1)  set this config
```
[ids]
*

[main]
capslock = layer(capslock)
[capslock:C]
semicolon = oneshotm(tap1, a)

[tap1]
semicolon = macro(b)
````
2) hold `capslock` + 2 tap on `semicolon`

**expected behavior**
Should ouput `ab`  

**encoutered  behavior**
Ouputs `a ctrl+b` (sometimes also written: `a^B`)    

 **my usecase**
 I'm trying to configure tapdance (multitap)  on `capslock + semicolon`
https://github.com/rvaiya/keyd/issues/473

**Comment by joihn** [comment]
clumsy workaround 
instead of 
_hold capslock + 2 tap on semicolon_

user has to 
_hold capslock + 1 tap on semicolon_, release capslock, 1 more tap on semicolon

**Comment by rvaiya** [comment]
This is by design. `capslock` behaved like a control key, when you activate the `semicolon` binding in `tap1`, the capslock key is still depressed, and hence `control` is activated. If you want `capslock + ;` to produce `a` and `capslock + ; + ;`  to produce `b`, you probably want something like this

```
[capslock:C]

; = swapm(capslock_semicolon, a)

[capslock_semicolon]

; = macro(backspace b)
```

**Comment by joihn** [comment]
it indeed works,
thank you for your quick and very educative answer @rvaiya :smiley:
