### ISSUE TITLE
Map key with and without layer

### ISSUE THREAD

**Issue by Subbeh** [rvaiya/keyd#580]
Firstly, very much appreciate this project and the developers. It's working perfectly so far, with the following exception.

I have capslock+[left, up, down, right] mapped successfully as shown below. However, I would like to map capslock by itself without any additional keys to the _right_ arrow key.

This is what I have tried, but it does not seem to register a single capslock press:

```
[ids]

*

[main]

capslock = layer(fn)

[fn:right]

h = left
k = up
j = down
l = right
```

**Comment by nsbgn** [comment]
Try `capslock = overload(fn, right)`. 

However, presumably you want the key to repeat if you hold `capslock` alone for some time?

In that case, try `capslock = timeout(overload(fn, right), 200, right)`. 

Also, the `:...` notation in `[fn:right]` is used for modifiers and layouts. Since `right` is neither a modifier set nor a `layout`, simply `[fn]` will do. (For example, if you had put `[fn:C]`, the `fn` layer would also activate the Ctrl modifier for any keys that aren't explicitly mapped.)

**Comment by Subbeh** [comment]
> In that case, try `capslock = timeout(overload(fn, right), 200, right)`.

Works great, thank you!
