### ISSUE TITLE
`swap`/`swapm` for composite layers

### ISSUE THREAD

**Issue by Nimmidev** [rvaiya/keyd#588]
I am currently banging my head against the wall to get the following working:

Given this very basic example:
```ini
[hyper]
v = toggle(layera)

[layera]
...

[layerb]
...
```

While `layera` is toggled, the key `A` i.e. `S-a` should swap out `layera` with `layerb` and execut the macro `end`.

```ini
# Option 1
[layera:S]
a = swapm(layerb, macro(end))

# Option 2
[layera+shift]
a = swapm(layerb, macro(end))
```

**Option 1** does correctly swap the layers and runs the macro. The issue is, that during the macro, `shift` is still "pressed" which interferes with the macro. Normally the cursor in a text field would jump to the end but here, because shift is active, the text from the cursors current position to the end is selected i.e. `S-end`.

**Option 2** does correctly execute the macro but the layer is not swapped. This is probably because the composite layer is a layer itself and its not clear which of the two layers to swap out (maybe both/all of them?).

Is there any way to accomplish this? Or perhaps its possible somehow to execute the macro in **Option 1** without the modifier?

Thanks in advance.

**Comment by nsbgn** [comment]
I don't think that your option 1 works, or rather, it works but it isn't dependent on `shift` being also held. That is, in `layera`, pressing `a` (without `shift`) will produce `end`. So it makes sense that also pressing `shift` stacks that `S-` on top of the `a`.

The easiest solution for now might be to just toggle (instead of swap) the `layerb` on top of your `layera`, and make sure that `layera` can't interfere (by defining all keys in `layerb`). That may or may not be acceptable for your use case.

```
[layera+shift]
a = togglem(layerb, macro(end))
```

You could also avoid the composite layer mechanism entirely, but the effect would be more or less the same since you'd be swapping a new `layerc` for `layerb` (and so `layera` will remain active):

```
[hyper]
v = toggle(layera)

[layera]
shift = layer(layerc)

[layerc:S]
a = swapm(layerb, end)

[layerb]
...
```

I can't quickly think of other ways to address this except ones that aren't currently supported (like executing multiple actions or swapping arbitrary layers rather than just the active one). What's your use case?

**Comment by Nimmidev** [comment]
Thanks for the quick response. Oh, you are right i didn't notice. So the first option is also incorrect.

My use case is that i am extending my basic vim bindings to actually support an insert and normal mode. For this to work, the insert and normal layers have to be mutually exclusive i.e. `swap`. The issue arises when trying to implement various normal mode bindings like `A` i.e. `S-a`.

```ini
[vim_insert_mode]
capslock = swap(vim_normal_mode)

[vim_normal_mode]
...

[vim_normal_mode+shift]
a = swapm(vim_insert_mode, macro(end))
```

But as it seem this is currently not possible.

I also though about implementing the actual vim bindings logic in python and listen to key presses (`keyd monitor`) and layer changes (`keyd listen`) but unfortunatly the counterpart of these ipc methods is missing (executing actions in keyd i.e. `keyd action` or something).

**Comment by nsbgn** [comment]
Hmm. If normal and insert mode are the only two modes, you could just `togglem(vim_normal_mode, end)` (that is, toggle normal mode *off*, rather than turning insert mode *on*, to get to insert mode). Otherwise --- there's many design changes I can think of to make this work, but I'll spare everyone the wall of text and wait for rvaiya's thoughts first :P

**Comment by Nimmidev** [comment]
Unfortunately its not that simple. There are also many additional "operator pending" modes when multiple keys are required. For example `dd`, `diw`, `cW` etc in normal mode.

**Comment by nsbgn** [comment]
That is not necessarily an objection though. You can still toggle multiple layers while switching modes in that way. For example:

```
[insert]
d = d
a = a
esc = toggle(normal)

[normal]
d = toggle(delete)
a = toggle(normal)
esc = esc

[normal+shift]
a = togglem(normal, end)

[normal+delete]
d = macro(home S-end del)
```

... etcetera.

**Comment by Nimmidev** [comment]
I tried many combinations for an hour or so but in the end it always comes down to some layer being active when it shouldn't be. In your example the normal mode is toggled leaving all the insert mode bindings active. I am pretty sure its not doable with the current feature set. But i am always happy to be proven wrong.

**Comment by rvaiya** [comment]
If I understand you correctly, I believe what you want should be fairly straightforward to achieve.

The key is to swap between layers using `swap(m)`, so only one layer is active at any given time. Toggle should only be used within a layer to disable it, as using it to activate successtive layers will leave the layer stack is a potentially unknown state.

E.g

```
[main]

capslock = toggle(vim-normal)

[vim-normal]

c = swap(vim-change)
d = swap(vim-delete)
i = toggle(vim-normal)

j = down
k = up
l = right
h = left
b = C-left
w = C-right
/ = C-s
0 = C-a
x = delete

control = layer(vim-control)
shift = layer(vim-shift)

[vim-shift]
6 = C-a
4 = C-e

[vim-control]
f = pagedown
b = pageup

[vim-delete]
w = swapm(vim-normal, macro(C-right C-backspace))
i = swap(vim-delete-in)

[vim-change]
w = togglem(vim-change, macro(C-right C-backspace))
i = swap(vim-change-in)

[vim-change-in]
w = togglem(vim-change-in, macro(C-right C-backspace))
#p = swapm(vim-normal, ???)

[vim-delete-in]
w = swapm(vim-normal, macro(C-right C-backspace))
#p = swapm(vim-normal, ???)
```

should get you reasonably close bearing in the mind the natural limitations of whatever text processing software you are using (some of these won't work in vim). Supporting numerical prefixes will require a dedicated feature, which will likely make it into the next version of keyd.

**Comment by Nimmidev** [comment]
That is pretty close to what i have at the moment. But if you add an insert mode now, things start to get complicated.

1. Insert mode and normal mode have to be mutually exclusive (`swap`)
2. The `shift` layer in normal mode needs to be able to switch to insert mode and execute an action e.g. `S-a`

I didn't find a solution that satisfies both of these requirements. In my example **1.** is satisfied but **2.** doesn't work. In yours its the other way around.

It seems like the underlying issue is, that there is no way to swap out the current layer, lets say `vim-normal` from another layer. In this case the `shift` layer.

```ini
[vim-normal]
shift = layer(vim-normal-shift)

# Option 1: Switches out `vim-normal-shift` for `vim-insert` which leaves `vim-normal` active
[vim-normal-shift]
a = swapm(vim-insert, macro(end))

# Option 2: Also doesn't work
[vim-normal+shift]
a = swapm(vim-insert, macro(end))

# Option 3: Same
[vim-normal:S]
a = swapm(vim-insert, macro(end))
```

An action that would set another layer active while deactivating everything else would solve the issue. Basically a `clear` followed by a `toggle`. But that is probably way to specific to be actually useful to implement.

I think the only two ways that actually make sense are:
1. Based on other issues i have read it may make sense to implement an action that allows to execute multiple actions. As this would solve many past, current and possible future issues. But this may not be feasible to implement, i am not sure.
2. Implement the vim mode externally (e.g. python script) as soon as the IPC is extended to trigger actions `keyd action` or something like that. Probably the better solution.

**Comment by rvaiya** [comment]
> It seems like the underlying issue is, that there is no way to swap out the current layer, lets say vim-normal from another layer. 

In this case it seems by 'current layer', you mean the nesting layer. `swap` will deliberately swap out the mostly recently activated layer by design (`vim-normal-shift`). This is why I used `toggle` in my example to deactivate the normal layer inside the change layers, but that is predicated on the assumption that you want your layout to serve as the `insert` layer. 

If you *really* want a dedicated insert layer which differs from your layout, you can do something like this:

```
[main]
capslock = setlayout(vim)

[vim]

capslock = setlayout(main)
h = left
# normal mode bindings...

i = toggle(vim-insert)

[vim+shift]

a = togglem(vim-insert, end)

[vim-insert]

escape = clear()
a = a
b = b
# etc...
```

The trick being to define `vim-insert` as an occluding layer that is capable of normal text input.

> Based on other issues i have read it may make sense to implement an action that allows to execute multiple actions

This is actually quite tricky to implement properly as there is presently a lot of hand coded logic to account for pathological action/key combinations. Having said that, a more flexible design is in the pipeline for the next major version (which will probably break backward compatibility).

**Comment by Nimmidev** [comment]
So i have played a little bit more with this config and while it works to a certain degree with the `setlayout` it interferes with other non vim bindings in keyd. I think i am just gonna wait until the IPC update. That will make it much simpler if the vim modes can be implemented in code. Nevertheless thanks for your help.

**Comment by rvaiya** [comment]
>  it interferes with other non vim bindings in keyd. 

Can you elaborate on this? The example I provided shouldn't cause any interference.

> I think i am just gonna wait until the IPC update. 

The IPC layer isn't really intended for implementing keymaps (it would be quite slow anyway), it is mostly intended to expose useful information to userspace programs. This sort of modal approach is within the purview of the config file. If it can't be realized then I am inclined to regard it as a bug.

**Comment by Nimmidev** [comment]
Sorry for the late reply i was busy last week.

It seems like i misunderstood your answer. You meant to redefine all keys for the `vim-insert` layer. Yeah, that would work and then using `oneshot` for "nested" modes like for `cc` bindings etc.
```
[vim:layout]
capslock = setlayout(main)
c = oneshot(vim-change)

[vim-insert]
...

[vim-change]
c = togglem(vim-insert, ...)
```

This seems like a good solution. Redefining all keys though is a bit inconvenient. Its a lot of keys and they also have to be redefined for every single modifier. Well, thats a low price to pay for a nice vim mode everywhere. Thanks for you help. The combination of `setlayout` with `clear` and `oneshot` open up a lot of possibilities i haven't thought of.
