### ISSUE TITLE
Use \t to separate monitor output?

### ISSUE THREAD

**Issue by canadaduane** [rvaiya/keyd#60]
I know you just said that hopefully the output format wouldn't change, but ... since it's so fresh, perhaps I can suggest this?

What if we use tab ("\t") to separate the three fields? I think it would be easier to parse.

So this:
```
AT Translated Set 2 keyboard(0001:0001): a down
AT Translated Set 2 keyboard(0001:0001): a up
```

Would become:
```
AT Translated Set 2 keyboard     0001:0001       a down
AT Translated Set 2 keyboard     0001:0001       a up
```

This solves several potential problems:
1. It's possible to have parens in keyboard names
2. The `:` (colon) separator is no longer ambiguous
3. "\t" should be a "safe" separator character
4. It's easier to use a separator than create a regex to pull info out of a line

**Comment by rvaiya** [comment]
A tab can technically appear in a device name since the kernel drivers don't explicitly forbid the character, but it is likely exceedingly rare. I agree with the rest of your points, though I still think relying on the output of `-m` is not ideal. I have switched to tab delimited output in the latest commit (which also disabled echoing).

**Comment by canadaduane** [comment]
Thanks!
