### ISSUE TITLE
Remap Esc to Zero on a non-english keyboard

### ISSUE THREAD

**Issue by hrvthzslt** [rvaiya/keyd#606]
I'm struggling with one remap, I try to map zero to esc on a hungarian keyboard when using a hungarian layout.

```
[main]

esc = 0
```

This produces the character `ö`. 

I tried to figure out the solution from the man page, but it is not clear to me if I can map purely to a unicode code.
Sorry if this problem does not have an appropriate place among the issues and thanks for any help.

**Comment by nsbgn** [comment]
>if I can map purely to a unicode code

You can, if you set an appropriate `.Xcompose` file. But since you're already using a Hungarian layout (separately from keyd, I assume), what you want is likely to just send the keycode that corresponds to `0` in your layout. To find out what keyd's name for that keycode is, you can run `keyd monitor` and press the `0` on your keyboard.
