### ISSUE TITLE
Capslock as compose key

### ISSUE THREAD

**Issue by hinricht** [rvaiya/keyd#614]
I searched issues and read the documentation but I still have not found how to simply map `capslock` to the compose key.
I just want a working compose key to compose international characters like `à` (pressing `capslock` \` and `a`).

Before using keyd in sway I activated the `xkb_options compose:caps` [input config](https://man.archlinux.org/man/sway-input.5)  option, i.e.:

```
 input "1:1:AT_Translated_Set_2_keyboard" {
  xkb_layout de
  xkb_options compose:caps
  xkb_variant nodeadkeys
}
```

But with keyd without any further config the capslock key behaves strange: I can compose characters, but it now *also* toggles caps.
How do I properly configure it in keyd ?

**Comment by nsbgn** [comment]
My guess is that you also need to add keyd's virtual keyboard to your input config (or use a catch-all `*`): `1:1:AT_Translated_Set_2_keyboard` matches the original but not the virtual keyboard.

(That said, it's surprising to me that you can compose characters at all in that configuration!)

**Comment by nsbgn** [comment]
Afaik `setxkbmap` is X11 only. Should probably be changed in the manpage if that's what it says - for Sway, using the `input` config (or the `XKB_DEFAULT_OPTIONS` environment variable) is indeed correct.

The compose sequence is a display server concept; the key that keyd calls `compose` corresponds to the menu key, which is why `compose:menu` is the recommended XKB option, but provided you don't have any further configuration in keyd, `compose:caps` should make the display server interpret CapsLock as the compose prefix just fine. If not, I'd consider that a bug.

**Comment by rvaiya** [comment]
To summarize, if you aren't making use of keyd's unicode/compose support then you probably just need to set `compose:caps` or else `compose:menu` in combination with:

```
[main]
capslock = menu
```

which can be achieved using `setxkbmap` on X or else whatever mechanism your wayland compositor provides to set XKB options.
