### ISSUE TITLE
Override "ć" with "ç"

### ISSUE THREAD

**Issue by gsevla** [rvaiya/keyd#650]
Hey guys, I'm having some trouble to achieve the title behavior.
If it matter, I'm using Arch Linux with Gnome(wayland). My keyboard is a MX Mechanical Mini(internacional) but I'm a brazilian guy and here we use some dead keys like `ç`.

Actual behavior:
1. `´` then `c` = `ć`
2. `rightalt` + `,` = `ç`

I want to override the 1 behavior with 2. 

I have tried many action/layer combinations but none has did it for me. Can anyone help me to achieve this behavior?

**[edit]**
For the record:
![image](https://github.com/rvaiya/keyd/assets/36795971/8829d419-dd9c-45a8-a19f-9ec39b348e83)
`keyd monitor` undestands `´` press as `'`(which is equal to `´`  then `space` press)

**Comment by nsbgn** [comment]
I'm going to assume that by 'override' you mean you want to turn the sequence `' c` into ç?

The reason that this is so confusing is that there are two concepts here that are conflicting. First there's the keycodes sent by your keyboard and second is the way your computer interprets those keycodes.

Keyd works on the first level, but your Brazilian layout with dead keys happens on the second level. The fact that `keyd monitor` says you've pressed `'` doesn't mean that it understands it as `' space` --- `'` is just the name it gives to that key, it doesn't know how it will later appear as a symbol on your screen.

So there's a few things you can do to still get the behaviour you want.

One, if this is the only change you want to make, you can skip keyd altogether and edit your layout to change the deadkey behaviour there.

Two, you can switch to a US layout so that the names of the keys are less confusing, and use the compose mechanism to regain the behaviour of Brazil keyboards.

Three, you keep your current layout and use some trickery to get the behavior you want anyway. This is probably the least involved (as long as you keep in mind what's happening). It could look like this:

```
' = oneshot(apostrophe)

[apostrophe]
c = G-,
space = macro(' space)
a = macro(' a)
# etcetera
```

**Comment by gsevla** [comment]
@nsbgn your assumption is right. But clarifying some things: I'm already using a US layout. And I want to use keyd because I have other use cases to cover(like mouse buttons behaving in a custom way).

I have tried your configuration(have tried some thing very similar before), but it not worked as I expect.

If I touch `´` once I get it:
![image](https://github.com/rvaiya/keyd/assets/36795971/fb666f98-4820-49da-8909-a73979250282)
which is a preview.
And then if I touch some other key the magic happens like:
touching `´` again:
![image](https://github.com/rvaiya/keyd/assets/36795971/53ba49f8-40ab-4d25-bd7c-0d60ede3d841)
touching `e`:
![image](https://github.com/rvaiya/keyd/assets/36795971/d7625fbc-715f-4790-b8c2-9fd78ddd0592)
touching `c`:
![image](https://github.com/rvaiya/keyd/assets/36795971/7600b94b-ffe1-4140-a0e4-213395191431)

I want to keep this preview and keep other compositions working too. 
With your configuration when I press `´` then `c` it works and I get `ç`, but I loose the preview and other compositions like `é` do not work anymore.

I was figuring out if its possible to do something like
```
' = overload(oneshot(apostrophe), ')

[apostrophe]
c = G-,
space = macro(' space)
```
but not worked.

**Comment by nsbgn** [comment]
Ah, US layout with dead keys - I forgot that's a thing too :P

If you want to keep the preview (which keyd has no control over), I would suggest some trickery by just backspacing if you encounter a `c`:

```
' = oneshotm(apostrophe, ')

[apostrophe]
c = macro(space backspace G-,)
```

**Comment by gsevla** [comment]
> Ah, US layout with dead keys - I forgot that's a thing too :P
> 
> If you want to keep the preview (which keyd has no control over), I would suggest some trickery by just backspacing if you encounter a `c`:
> 
> ```
> ' = oneshotm(apostrophe, ')
> 
> [apostrophe]
> c = macro(space backspace G-,)
> ```

It worked! Thanks mate!

Before I close this issue, where can I find these "different" kind of actions/commands like `oneshotm`. I've read https://github.com/rvaiya/keyd/blob/6dc2d5c4ea76802fd192b143bdd53b1787fd6deb/docs/keyd.scdoc but it's not there.

**Comment by nsbgn** [comment]
Good to hear :)

You linked to an old version --- it is in the latest one at https://github.com/rvaiya/keyd/blob/dcbb68b12f71245121035b730b50872802a259b4/docs/keyd.scdoc#L668

The above file is just the source for the page that's pulled up when you execute `man keyd`, which will correspond to the keyd version that you actually have installed ;)

**Comment by gsevla** [comment]
@nsbgn 
Oh, my bad :/. Thanks for the link and the tip!
