### ISSUE TITLE
Option to exclude touchpad/pointer devices

### ISSUE THREAD

**Issue by diamondburned** [rvaiya/keyd#676]
Currently, keyd breaks the touchpad on Asahi Linux. This Reddit post describes it quite well: [Debugging touchpad issues with keyd remapper](https://www.reddit.com/r/linux4noobs/comments/17yct4p/debugging_touchpad_issues_with_keyd_remapper/).

Rather than figuring out a fix on either the kernel or libinput, since I'm not using keyd for any touchpad handling, is there a way (perhaps a flag?) for keyd to disable handling touchpad/pointer devices entirely?

**Comment by diamondburned** [comment]
It seems like `*` excludes mice already.

**Comment by rvaiya** [comment]
Yes, mouse support is experimental (and usually breaks on touchpads), which is why it is disabled by default. However, laptops will often group other keys into the touchpad device which can cause keyd to misidentify them as keyboards. If this happens (which can be verified by inspecting the daemon output) you can explicitly exclude them by adding `-<id>` to your `ids` section.

**Comment by diamondburned** [comment]
Should this behavior be documented somewhere in the README?

**Comment by rvaiya** [comment]
Indeed, I've added a note to the man page.
