### ISSUE TITLE
Layers on non-modifier keys

### ISSUE THREAD

**Issue by dwrz** [rvaiya/keyd#678]
Would it be possible to trigger a layer with a regular, non-modifier key?

```
[main]
a = layer(nav)

[nav]
k = left
l = down
o = up
; = right
```

I'm trying to implement something like what I had with QMK.

![keymap](https://github.com/rvaiya/keyd/assets/21134999/eec897d6-3e98-42d4-9852-be4e1ea213dd)

**Comment by motato1** [comment]
You can use `a = overload(nav, a)` use the `nav` layer by holding the A key  and type `a` by tapping it.

**Comment by dwrz** [comment]
Thank you! That doesn't seem to work for me. It's as if the layer isn't activated.

**Comment by motato1** [comment]
Have you reloaded the config? Have you tried seeing what's happening with `keyd monitor` or `keyd listen`?

Here's the config I've tested which works for me. 
 
```
[ids]
*

[main]
a = overload(nav, a)

[nav]
k = left
l = down
o = up
; = right
```

**Comment by dwrz** [comment]
Thank you! Your config seems to work for me.

I'm not sure what it is about mine that's not working. 

```
include layouts/dvorak

[ids]
*

[global]
default_layout = dvorak
layer_indicator = 1

[main]
a = overload(nav, a)
capslock = layer(nav)
rightalt = layer(control)
leftalt = layer(meta)
meta = layer(alt)

[nav]
k = left
l = down
o = up
; = right
i = home
p = end
```

I've tried removing the `capslock = layer(nav)` line, but it  seems to make no difference.

Here's a `keyd monitor` session:

```
  C-c C-c23:17:20 dwrz@main.dwrz.net 2 ✗ (30.9s) ~ $ doas keyd monitor
device added: 0001:0001 AT Translated Set 2 keyboard (/dev/input/event3)
device added: 0002:000a TPPS/2 JYT_Synaptics TrackPoint (/dev/input/event12)
device added: 04f3:3150 ELAN0670:00 04F3:3150 Mouse (/dev/input/event6)
device added: 04f3:3150 ELAN0670:00 04F3:3150 Touchpad (/dev/input/event7)
device added: 04f3:2bb5 ELAN901C:00 04F3:2BB5 (/dev/input/event8)
AT Translated Set 2 keyboard	0001:0001	enter up
AT Translated Set 2 keyboard	0001:0001	a down
AT Translated Set 2 keyboard	0001:0001	k down
AT Translated Set 2 keyboard	0001:0001	k up
AT Translated Set 2 keyboard	0001:0001	k down
AT Translated Set 2 keyboard	0001:0001	k up
AT Translated Set 2 keyboard	0001:0001	k down
AT Translated Set 2 keyboard	0001:0001	k up
AT Translated Set 2 keyboard	0001:0001	k down
AT Translated Set 2 keyboard	0001:0001	k up
AT Translated Set 2 keyboard	0001:0001	k down
AT Translated Set 2 keyboard	0001:0001	k up
AT Translated Set 2 keyboard	0001:0001	a up
AT Translated Set 2 keyboard	0001:0001	rightalt down
AT Translated Set 2 keyboard	0001:0001	i down
AT Translated Set 2 keyboard	0001:0001	i up
AT Translated Set 2 keyboard	0001:0001	i down
aaaaaaaaaaaaaaaaaaaaaaaaaaaattttt  C-c C-c23:17:41 dwrz@main.dwrz.net 2 ✗ (17.5s) ~ $ 
```

**Comment by motato1** [comment]
The problem is `default_layout = dvorak`. If you comment that out, your config file works.

I don't know if there is something missing in the config file or if this is a bug. What I've found is, that any key that is mapped in a layout cannot be remapped in your main config.

As a workaround, you could remove the line `a = a` in the dvorak layout file.

Maybe someone with a deeper understanding of the code base can explain if this behavior is intentional or not.

**Comment by dwrz** [comment]
Thank you. I also realized that my config does not conform to the following:

`All include statements should appear after the [ids] section in the including file.`
https://github.com/rvaiya/keyd/blob/master/docs/keyd.scdoc#L532

However, fixing that does not resolve the behavior.

```
[ids]
*
include layouts/dvorak

[global]
default_layout = dvorak
layer_indicator = 1

[main]
a = overload(nav, a)
capslock = layer(nav)
rightalt = layer(control)
leftalt = layer(meta)
meta = layer(alt)

[nav]
k = left
l = down
o = up
; = right
i = home
p = end
```

There's also this:
```
A layout is a special kind of layer intended for modifying alpha keys. Unlike
layers, layouts cannot have any associated modifiers, and only one layout may
be active at a given time. The current layout can be set using the _setlayout_
action.
```
https://github.com/rvaiya/keyd/blob/master/docs/keyd.scdoc#L338C1-L341C8

So perhaps what I'm trying to do, while importing the layout, is not possible. 

The other workaround that I found is to not use the layout at all, but copy its contents into my config. That seems to be working well enough for my needs now.

I really appreciate all your time and help!

**Comment by rvaiya** [comment]
> I don't know if there is something missing in the config file or if this is a bug. What I've found is, that any key that is mapped in a layout cannot be remapped in your main config.
> ...
> Maybe someone with a deeper understanding of the code base can explain if this behavior is intentional or not.

This is indeed intentional. Bindings defined in a layout take precedence over the main layer because the layout is considered the principal mechanism for symbol input, and it is rarely desirable to have bindings like `a = overload(nav, a)` apply globally. The correct place to define such bindings is in the layout itself. 

For example, imagine the binding at issue was `s = overload(nav, s)`. This would work as expected in a qwerty layout, but if you switched the layout to dvorak, `o` would now produce `s` when tapped. The correct binding is `o = overload(nav, o)`. To avoid issues like this, the user is forced to confine such bindings to the layout. `main` can still be used to bind shared keys like `insert` or `delete`, which are truly shared and not usually defined in layout files.

The non-english layouts make use of this feature to define their shift layers, so switching between imported layouts automatically does the correct thing.

> The other workaround that I found is to not use the layout at all, but copy its contents into my config. That seems to be working well enough for my needs now.

The intended way to achive this is like so:

```
include layouts/dvorak
# ...
[dvorak]
a = overload(nav, a)
```

**Comment by dwrz** [comment]
Thank you!
