### ISSUE TITLE
How to 'unmap' rightshift for use only as a modifier key with keyd?

### ISSUE THREAD

**Issue by sedrosken** [rvaiya/keyd#682]
I'm trying to set rightshift as a modifier to make my arrow keys Home/End/PgUp/PgDn and I've gotten keyd to pick up rightshift but it still functions as a shift key. Possibly out of scope for keyd as a whole, but I'm trying to unmap rightshift as a shift, if I can -- setting it to iso-level3-shift doesn't seem to do it.

I'm using KDE 5.27 under Wayland on Debian 12.5.

**Comment by nsbgn** [comment]
I'm not exactly sure what you mean by 'unmapping' or 'setting up as a modifier', because rightshift is already a modifier by default (namely, shift) and I understand unmapping it as `rightshift = noop`. 

Could you elaborate? Also, what configuration have you tried? Going by "rightshift [...] to make my arrow keys Home/End/PgUp/PgDn", I would suggest:

```
[ids]
*

[main]
rightshift = layer(something)

[something]
up = pageup
down = pagedown
left = home
right = end
```

**Comment by sedrosken** [comment]
That did the trick right there, actually, and is exactly what I was after. I wanted that key to ONLY be the layer modifier, not and not be taken as shift or anything else.
