### ISSUE TITLE
keyd remaps right-side modifier keys to left-side by default

### ISSUE THREAD

**Issue by thekpaul** [rvaiya/keyd#697]
Using the 2.4.3 version from pacman, on an Intel Mac running Arch Linux (custom kernel for T2 Macs based on 6.7.6).
running the keyd service on systemd changes my `rightmeta` (`Super_R` on wev) to `leftmeta` (`Super_L`).
Apparently this behaviour was previously found as well (#632).

No keyd (`systemctl stop keyd`):
![image](https://github.com/rvaiya/keyd/assets/44695374/29615ee8-3300-4f0d-af92-2d6e42a8fa4e)

keyd (`systemctl restart keyd`):
![image](https://github.com/rvaiya/keyd/assets/44695374/d27c52a9-4940-4340-a5f9-d1e8a5b990a6)

Although this can be solved by `rightmeta = rightmeta`, I'd appreciate it if anyone could provide an insight as to why this problem happens in the first place...

**Comment by rvaiya** [comment]
Yes, this has been discussed many times before. It is a feature, not a bug. Is this causing a specific problem in your case? Applications should not generally care about the specific modifier that is pressed.

**Comment by nsbgn** [comment]
> if anyone could provide an insight as to why this problem happens in 
> the first place

You might be interested in this comment: https://github.com/rvaiya/keyd/issues/209#issuecomment-1131037991 

(... and just to keep track of previous discussions: #114 #180 #185 #369 #406 #624)

**Comment by thekpaul** [comment]
No specific problems, I was just wondering why this would be happening by default. Thank you for your replies!

**Comment by lelgenio** [comment]
Things that get broken by this:

1. xkeyboard-config's `grp:shifts_toggle` [option](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/087df87a7c9c55092e7116c91028df504217d072/symbols/group#L67)
2. Mangohud's [default keybindings](https://github.com/flightlessmango/MangoHud/blob/422663d0b2516857da31090024da20b35142426b/data/MangoHud.conf#L333)
3. Virtuabox's [Host Key](https://www.virtualbox.org/manual/UserManual.html#specialcharacters)

It took months to figure out `keyd` was the source of these problems, since I only use keyd for `capslock=backspace`. Maybe this behavior should get some more visibility in the FAQ?

**Comment by iostapyshyn** [comment]
@nsbgn Adding to the list of right shift use cases:

I use `grp:shifts_toggle` in xkb options, which switches keyboard layouts when pressing both shifts
