### ISSUE TITLE
Can't Use Certain Keys With Overload

### ISSUE THREAD

**Issue by KineticAeon** [rvaiya/keyd#713]
The following mapping does not work.
```
capslock = overload(rightcontrol, capslock)
```
`capslock = overload(control, capslock)` works fine, but trying to specify which direction mod key to use does not. It does not work with any of the mod keys as far as I can tell, however without direction labels (`meta`, `control`, etc.) it works fine. I have tested `leftmeta`, `rightmeta`, `leftcontrol`, and `rightcontrol` so far. Defining `rightcontrol = rightcontrol` or anything similar with the other mod keys changes nothing.

**Comment by KineticAeon** [comment]
That partially gets at the issue, but I'm getting problems with overloading keys in general. An example is `capslock = overload(control, esc)`, `capslock = numlock`, and `capslock = (numlock, capslock)`. The first two of these work, but the last doesn't. I just don't really understand why I can map capslock to numlock (or for that matter, leftmeta and rightmeta when not using overload), but attempting to map it with overload fails. I don't mind that they're unbound by default, it's the inconsistencies that are driving me mad. I'm going to change the title of the issue to reflect the above concerns. It's not causing issues with any applications, my issue is in fact quite the opposite: I have programs that will allow me to treat the buttons as different, and I want to be able to use them separately.

**Comment by nsbgn** [comment]
Ah, I see, that makes sense. They're not inconsistensies --- the idea is that overload switches to a *layer* if held but emits a key if tapped.

It's not obvious what overload should do when the hold action is a key rather than a layer. Should it press the hold key immediately and then release it if the tap action is selected (consistent with layer behaviour)? Should the hold key only be activated once it overlaps with a subsequent keypress (feels less surprising)?

A layer can have a modifier key attached, and I suppose there is a case to be made for being able to attach any key *as if* it were a modifier (instead of just `M` / `leftmeta`, `C` / `leftcontrol` et al, as is the case now), or to set a default action for a layer (see relevant discussions at #651, #681, #705). The latter has been floated as a candidate for the next major version, and it would address your use case nicely.

To hold you over until such a feature is accepted, you could do this:

```
[main]
capslock = overload(numlock, capslock)

[numlock]
a = numlock+a
b = numlock+b
# etcetera
```

Verbose, yes, but at least it should work for now.

**Comment by rvaiya** [comment]
Closing this, since I am trying to prune the issue tree and nsbgn has given a characteristically obliging response :).

**Comment by Davi-S** [comment]
> Should the hold key only be activated once it overlaps with a subsequent keypress

That is the exact behavior i was looking for. It is very useful for using with a custom modifier key.

The "x = y+x" does not work for me because my keyboard layout is a more complex.
I'm using "z = timeout(x, y, z)" for now, but it is not perfect because 'if another key is struck before <timeout> ms expires, execute the first action'.
If this were changed to 'if another key is struck before <timeout> ms expires, execute the _second_ action' it would work very nice for me. How can i change this in the files and recompile? seems an easy fix...
