### ISSUE TITLE
Release layer before executing action

### ISSUE THREAD

**Issue by musjj** [rvaiya/keyd#732]
I have a simple mapping like this:

```ini
[main]
capslock=overload(control, esc)
enter=overload(alt, enter)
```

The mapping works, but it misbehaves in some applications. In [PICO-8](https://pico-8.com), my <kbd>Enter</kbd> key is registered as <kbd>Alt+Enter</kbd> (which fullscreens the window), while my <kbd>Esc</kbd> key fails to work in most contexts. 

You can reproduce the <kbd>Esc</kbd> issue yourself via the web version: https://www.pico-8-edu.com. But the <kbd>Enter</kbd> issue only exists on the desktop version, because there's no fullscreen shortcut on the web version.

I think the problem is that `keyd` presses the `<action>` (`esc`, `enter` here) before releasing the `<layer>` (`control`, `alt` here). This is just my guess from trying to reproduce the issue with `keyd` disabled.

Is there a way to make it so that the layer is released first?

**Comment by musjj** [comment]
Another easy-to-test example that I've found: https://deepnight.net/games/game-feel
In here, <kbd>Enter</kbd> is supposed to bring up the menu, but with `overload(alt, enter)`, it does nothing :confused:.

**Comment by nsbgn** [comment]
Thanks for the reproduction steps!

I see the same issues (at least on the web version), but I don't think this is due to keyd not releasing the layer before emitting the tap action. You can confirm that it already does with `keyd monitor`.

In fact, I don't think it has anything to do with overloading at all. I suspect that the issue is that keyd presses and releases the key immediately, in too short a timeframe for the game loop to register it. It also occurs when you have simply:

```
enter = macro(enter)
```

I don't think it is currently possible to set a delay between the activation and release of keys in a macro, but imo it would make sense to have a global option for that.

**Comment by rvaiya** [comment]
This sounds like a bug in the loop. You can verify keyd is emitting the correct output using `keyd monitor`. You should be able to work around it using something like `enter=overload(alt, macro(10ms enter))`. Modify the timeout to taste.

**Comment by musjj** [comment]
> `enter=overload(alt, macro(10ms enter))`

This causes <kbd>Enter</kbd> to be repeated endlessly until I press <kbd>Enter</kbd> again. This seems like a recursion bug.

**Comment by rvaiya** [comment]
Can you post the output of keyd monitor when pressing enter?
