### ISSUE TITLE
Feature request: device fallback/config import for code reuse

### ISSUE THREAD

**Issue by poscat0x04** [rvaiya/keyd#747]
Currently, the behavior of keyd is to read all the config file and select the most specific one (ids are more specific than wildcards) to apply (Also this isn't documented anywhere and I had to dig through the code. It would be nice if this behavior is documented). This means if I want some specific tweaks on a specific keyboard then I have to repeat all the tweaks in a new file, which isn't very ideal. It would be nice if keyd can have a config fallback mechanism like sysctl or fontconfig where the program traverses through all the config files in a directory in lexicographical order and accumulates configs relevant to that specific device. Alternatively a config import mechanism would also be sufficient.

**Comment by rvaiya** [comment]
> It would be nice if keyd can have a config fallback mechanism like sysctl or fontconfig where the program traverses through all the config files in a directory in lexicographical order and accumulates configs relevant to that specific device.

I am opposed to this, since it makes it unclear which file(s) correspond to a given device. Associating each device with a single config also has other advantages, like facilitating shared modifier state between listed devices (e.g a foot pedal and a keyboard). Having said that, the next major release will probably include a special file which maps ids to configs to eliminate any ambiguity.

> Alternatively a config import mechanism would also be sufficient.

As @nsbgn mentioned this is what include is for:

/etc/keyd/nav
```
[main]
capslock = overload(nav, esc)

[nav:C]
h = left
j = down
k = up
l = right
```

/etc/keyd/kinesis.conf:
```
[ids]

1234:4567

include caps

[main]
# ...
```

> I agree that adding a note that configs are not otherwise cumulative is probably a good idea

I've added a note about this to the man page.
