### ISSUE TITLE
Add support for config file in $HOME/.config

### ISSUE THREAD

**Issue by marcinjahn** [rvaiya/keyd#767]
Currently, you have to store the config file somewhere in `/etc`, which is non-ideal, because:

- it's a restricted directory
- it's a system-wide configuration place
- it doesn't play well with dotfiles managers like chezmoi

It'd be much more convenient if keyd could have a config file somewhere within `$HOME`.

**Comment by nsbgn** [comment]
This is intentional --- keyd requires system-level access by nature. Even if you did put it in `$HOME` (which you can do by linking), it would need to be an access-restricted file. See #45.

For dotfile management, you could make a hook that asks for root access to copy your config to `/etc`?

That said, it has been mentioned that some sort of per-user config is not off the table; see #692.

**Comment by marcinjahn** [comment]
Got it, thanks!
