### ISSUE TITLE
Mappings with modifiers lose modifier status on key repeat when switching pressed key to another mapping with a modifier

### ISSUE THREAD

**Issue by Compile-Time** [rvaiya/keyd#80]
The problem can be reproduced with the following config:

```
[ids]
<device>

[main]
i = S-i
o = S-o
```

Press the 'i' key until key repeat starts. You should see capitalized i's. Then switch to the 'o' key and hold it down. 
The firs key press should output an 'O' and once key repeat starts the key should output 'o'.

![image](https://user-images.githubusercontent.com/18414241/147856800-a60fc4ca-1498-479f-ba96-374c1979899f.png)

It might take a few attempts to get this right. Constantly switching between 'i' and 'o' should guarantee to trigger the 
described behavior.

In my use case I have the following mappings:

```
# Output '{' on ö
; = G-7
# Output '}' on ä
' = G-0
```

This somewhat emulates the default position of '{' and '}' on an English keyboard. I haven't been able to notice any 
problems when navigating with these keys in Neovim and in normal every day usage of the keyboard I have not encountered this problem so far. Therefore, it is rather unlikely for someone to encounter this issue by accident.

![image](https://user-images.githubusercontent.com/18414241/147856834-7258f0a9-84a7-49c8-ad36-3c462801cacb.png)

**Comment by rvaiya** [comment]
Thanks for the detailed reproduction steps. Is this a regression? The reason this happens is because the modifier is tied to the key down event in the case of a key sequence. Thus if you have two key sequences with the same modifier and release one of them while they are simultaneously depressed it will trigger the behaviour you describe. 

As you've observed this almost never happens in practice. If this is causing you a real problem I am willing to change the behaviour, but otherwise I am inclined to treat it as a feature not a bug ;).

**Comment by Compile-Time** [comment]
> Is this a regression from v1?

Just tested this. It is not.
![image](https://user-images.githubusercontent.com/18414241/147860362-d4b2489d-0436-4370-8cbd-cd229a4d1e08.png)

Personally, I am fine with keeping this as a "feature", considering that this has to be triggered intentionally and keyd behaves like this in V1 as well where I never noticed it.

Feel free to close this issue.

**Comment by lemnos** [comment]
Thanks. 

As a final note, it is worth noting that macros don't behave like this since they generate synthetic self contained repeat events.

E.G

```
i = macro(shift+i)
o = macro(shift+o)
```

 This also results in more noise (more key up/down pairs) and can cause unintuitive side effects in certain cases but solves the problem described above.
