### ISSUE TITLE
Is it possible to remap keys with multiple modifiers from the cli?

### ISSUE THREAD

**Issue by Vosjedev** [rvaiya/keyd#808]
I am trying to bind `ctrl`+`alt`+`shift`+`f1` up to `ctrl`+`alt`+`shift`+`f9` to new bindings using keyd-application-mapper. Because my mappings did not work, I started trying to do it manually from the cli, with the following results:
```
$ keyd bind control.alt.shift.f1=kp1
alt.shift.f1 is not a valid key or alias
```
So I tried something else, but without success:
```
$ keyd bind control+alt+shift.f1=kp1
control+alt+shift is not a valid layer
```

Would something like this (basically remapping keys with multiple modifiers using `keyd bind`) be possible?

**Comment by Vosjedev** [comment]
Thanks, but I don't really understand how you would trigger that layer... Also, I guess `capslock` is also a layer, and this part shows two layers with a `+`:
```
# New private window
capslock+shift.n = C-S-p
```
Isn't that what I am searching for? How does that work?

**Comment by tkna91** [comment]
@Vosjedev Layers must be defined in `/etc/keyd/*.conf`.
If you do the following, you can use it in `~/.config/keyd/app.conf` like `HYPER.a = b`.
```
# /etc/keyd/keyd.conf
[HYPER:S-C-A-M]
esc = clear()
```

**Comment by Vosjedev** [comment]
Sorry for the very late response. I eventually solved it using a device-specific remap and some aliases. Thanks for the help, this information could be usefull in the future.

**Comment by rvaiya** [comment]
The correct way to solve this is to use composite layers.

That is:

```
[control+alt+shift]

f1 = <action>
```

Please see the man page for more details.

**Comment by rdiaz02** [comment]
I'd like to confirm this is correct; as well, this might help others searching for similar setups.

I wanted to bind `Ctrl+Alt+y` to a particular action -- "Show in Library", in Zotero. But I also use Emacs heavily, so I have tons of `Ctrl+Alt+a_bunch_of_other_things` in Emacs.

What I did was:
- in the `/etc/keyd/` conf file add an empty `[control+alt]` (e.g., place it at the end of the file).
- in `~/.confif/keyd/app.conf` add `control+alt.y = macro(A-f 50ms s 5ms enter)` in the `[zotero]` section.

This seems to work just fine, and none of Emacs' `Ctrl+Alt+*` bindings seem to be caught, which I understand is what should happen, since unless explicitly bound, they will just go through.

Is this the correct way of doing this? Any caveats?

If this is one correct way, maybe it would be worth adding a short section to https://github.com/rvaiya/keyd/blob/master/docs/keyd-application-mapper.scdoc? (I can make a PR).
