### ISSUE TITLE
[DRAFT] ERROR: Failed to connect to "/var/run/keyd.socket" (No such file or directory) keyd -m works

### ISSUE THREAD

**Issue by jirafey** [rvaiya/keyd#812]
ERROR: Failed to connect to "/var/run/keyd.socket", make sure the daemon is running and you have permission to access the socket.

Gnome Wayland Fedora 40

https://github.com/rvaiya/keyd/issues/743

```console
$ cat /var/run/keyd.socket
cat: /var/run/keyd.socket: No such file or directory
```

```conf
[ids]

*

[main]

leftshift = oneshot(shift)
```

**Comment by jirafey** [comment]
Closed: fixed by reading the README again. 
```console
$ sudo systemctl restart keyd
$ sudo reload keyd
```

**Comment by serif** [comment]
Thank you, this just solved my problem too! Btw, the second command is `sudo keyd reload`, not reload keyd.

Also, to leave a potentially time-saving search result and help for others in my circumstance, I'm used to modifying `/usr/share/X11/xkb/symbols/us` and `/usr/share/X11/xkb/rules/evdev.xml` to add my own keyboard layout, but that doesn't work in Bazzite, which is immutable/atomic and based on Fedora Ublue, similar to Silverblue and Kinoite.

Keyd does work, and to make installing it easier, since on these distros dnf is just an alias to rpm-ostree which doesn't on its own support copr, I used rpm-copr:

https://github.com/34N0/rpm-copr

After curling the install command on that repo,

```bash
sudo rpm-copr enable alternateved/keyd
sudo rpm-ostree install keyd
```

Then restart so ostree can layer the package, and follow the config steps from this repo.

```bash
sudo mkdir /etc/keyd
sudoedit /etc/keyd/default.conf
sudo systemctl restart keyd
sudo reload keyd
```
