### ISSUE TITLE
How do I set the default layout?

### ISSUE THREAD

**Issue by adamstuck** [rvaiya/keyd#82]
My conf file can be found [here](https://github.com/adamstuck/dotfiles/blob/805d908105645e255533954626be37fdae9f3e09/.config/keyd/default.conf).
Is it possible to start in my colemak-dh layout on startup so I don't have to switch from qwerty everytime?

**Comment by lemnos** [comment]
The way to achieve this with the new config format is to define your default layout under main. If you want to be able to switch back to the default layout you will have to create a new layout. E.G

```
# Default layout is colemark
[main]
s = r
d = s

[qwerty:layout]

[switch]
q = layout(qwerty)
w = layout(main)
```

It's also worth noting that the default names for the modifier layers changed in 2.1. So `[S]` should be `[shift]`, etc.

**Comment by adamstuck** [comment]
> It's also worth noting that the default names for the modifier layers changed in 2.1. So [S] should be [shift], etc.

Does [M-S] stay the same or become [meta-shift]?

**Comment by rvaiya** [comment]
> Does [M-S] stay the same or become [meta-shift]?

`[M-S]` is defined and mapped by you, so you may call it whatever you want. Note that if you change the name you will have to explcitly specify the modifer set, e.g `mymetashift:M-S`. `M-S` is actually just syntactic sugar for `[M-S:M-S]`. 

The only thing that has changed is the default mapping of `leftshift` which is now `layer(shift)` instead of `layer(S)`. You can even retain `[S]` and `[M]` provided you explicitly remap `leftshift` to `layer(S)` in the main layout.

> . edit: I think I found a bug in 2.1.0-beta. After renaming my layers [S] -> [shift], [M] -> [meta], the layers only worked correctly when in main layout.

This is indeed a bug. Thanks for bringing it to my attention, I believe it should be fixed in the latest commit.
