### ISSUE TITLE
swap leftcontrol and leftmeta

### ISSUE THREAD

**Issue by hillyu** [rvaiya/keyd#83]
I want to simply switch leftcontrol and leftmeta on my keyboard.

in my key mapping section I have:
```
leftcontrol=leftmeta
leftmeta=leftcontrol

```
keyd -m shows that if I hold leftcontrol/leftmeta and press another key, the leftcontrol will be release first and then the press event of the key pressed. This will render all leftcontrol+key combination useless. Wonder what is wrong or did I miss somthing in the configuration file?

**Comment by hillyu** [comment]
nvm solved, the right hand side should be a layer:
leftcontrol=layer(leftmeta)

**Comment by rvaiya** [comment]
Yes. In general you should avoid mapping to/from modifier keycodes explicitly since they don't play well with layers. You want `leftcontrol = layer(meta)` and `leftmeta = layer(control)`. You can also use `control = layer(meta)` to remap both `rightcontrol` and `leftcontrol`. I should probably add some kind of warning about this in the documentation.
