### ISSUE TITLE
iso_level3_shift

### ISSUE THREAD

**Issue by hillyu** [rvaiya/keyd#84]
in evdev keycode:
	<LVL3> =   92;
can't seem to find any documentation of this key's name in keyd.

**Comment by rvaiya** [comment]
What shows up when you use `-m`?

**Comment by hillyu** [comment]
Thanks for reply, sorry I may not be clear, I want to map one of my current key, say, `rightalt` to `iso_level3_shift` which has keycode 92 from `evdev`. Tried to get the name from -l and could't find anything with that name (iso_level3_shift) or similar. Hence my original question.

**Comment by rvaiya** [comment]
If you run keyd with `-m` and then press the button of interest it should print the internal name of the key.

**Comment by rvaiya** [comment]
I believe code 92 is called `henkan`, but I encourage you to use the flag to verify this on your own machine.

**Comment by slakkenhuis** [comment]
I believe that the key is one that is not originally present on the keyboard in question.

**Comment by rvaiya** [comment]
Ah, that would make sense :P. I'm not sure about wayland but on X you can assign modifiers to any key code, so you don't have to confine yourself to code 92.

**Comment by hillyu** [comment]
yeah, tried `hekan`, I think it is not `iso_level3_shift` in edev it is called `<LVL3>`, do you have any idea what that key correspond to in `keyd`'s name. I can do this swap using following xkb options. Would be great if I don't set any XKB default at all but do everything on keyd. 
XKB_DEFAULT_OPTIONS="lv3:ralt_switch,lv3:rwin_switch,lv3:menu_switch"

**Comment by rvaiya** [comment]
> yeah, tried hekan, I think it is not iso_level3_shift; in edev it is called <LVL3>, do you have any idea what that key correspond to in keyd's name. I can do this swap using following xkb options. Would be great if I don't set any XKB default at all but do everything on keyd.
> XKB_DEFAULT_OPTIONS="lv3:ralt_switch,lv3:rwin_switch,lv3:menu_switch"
> essentially all right hand side modifiers are mapped to lvl3.

I think you are confusing evdev key codes with X11 key codes and/or keysyms. My understanding is that evdev key codes get translated into X key codes before ultimately getting translated into X keysyms based on the currently active keymap. `ISO_LEVEL3_SHIFT` seems to be the keysym associated with the altgr key found on most keyboards which itself corresponds to the rightalt keyd/evdev keycode.

The problem is that unless you are using a layout which support altgr by default then the righalt key will be mapped to the `Alt_R` keysym instead of the `ISO_LEVEL3_SHIFT` (altgr) keysym by default. The purpose of the `lv3:ralt_switch` option seems to be to explicitly associate the `ISO_LEVEL3_SHIFT` keysym with rightalt.

After digging around the X sources for a bit I was able to discover that the `ISO_LEVEL3_SHIFT` keysym is mapped to evdev keycode 84 by default (at least on the english keymap on *my* machine). Curiously, it seems that code 84 is absent from linux/input-event-codes.h suggesting that (for whatever reason) this key is never actually emitted by real devices. I'm not sure why X seems to map this phantom code to `ISO_LEVEL3_SHIFT`, or even if it does so uniformly, but I have tentatively given it the name `iso-level3-shift` in the latest keyd sources. 

Thus you have two options:


use `XKB_DEFAULT_OPTIONS="lv3:ralt_switch"` and then put `menu = layer(altgr)` and `rightmeta = layer(altgr)` in your keyd config 

or

(requires the latest commit)
```
menu = iso-level3-shift
rightmeta = iso-level3-shift
rightalt = iso-level3-shift
```

Though I'm not entirely sure the latter will work (feedback would be appreciated).

**Comment by hillyu** [comment]
Thanks for the fast patch, this worked like charm! 
menu = iso-level3-shift
rightmeta = iso-level3-shift
rightalt = iso-level3-shift
```

**Comment by slakkenhuis** [comment]
Given issues like this, and the more general issue that international layouts might emit different codes, would it not be useful (and less confusing) to have a method to also capture and emit keycodes by their numeric value? (Prefixed by `0x` or some such.) I'm sure there's some reason for not doing that, but I have to ask :P

**Comment by rvaiya** [comment]
The main reason for this is that key codes are supposed to be internal. Evdev is just one of potentially many output sinks (see for example #72). The initial set of codes were nicked from evdev, so all valid evdev codes are indeed valid keyd codes (whose name are discoverable with -m), but this is technically an implementation detail.

In this particular instance it wouldn't have helped anyway, since X was using a mystery key code (which would not have been possible to discover by normal means) for ISO_LEVEL3_SHIFT.
