### ISSUE TITLE
Can't overload backspace and enter

### ISSUE THREAD

**Issue by aramacs** [rvaiya/keyd#868]
Hey @rvaiya,  first things first, thanks a lot I use this all day. 

Second, I'm facing the situation that I can't overload both enter and backspace but they work well when I overlap behavior on a swap. Don't know if it is a bug or so. 
![image](https://github.com/user-attachments/assets/30927d35-ad9f-453e-b729-4a655d737025)

**Comment by nsbgn** [comment]
I assume you mean you can't press `d` and `e` at the same time, which you have overloaded to `backspace` and `enter` respectively. I suspect that this is due to key rollover, which is a hardware problem: not all keyboards can register any arbitrary key combination. To confirm, try pressing `d` and `e` at the same time without keyd running.

**Comment by aramacs** [comment]
Nope. I'm saying that the behavior assigned in the "d" works but on the overload one does not. The first case is on a swap layer. This is what is tricking me. All of the others homerow overloads are working completely fine except those two.

**Comment by nsbgn** [comment]
Then I do not understand what you mean. I still suspect this is a hardware problem. Could you give example outputs of `keyd monitor`, being:

1. Pressing the keys you want to press without keyd running.
2. The same with keyd running, showing what goes wrong.
3. Edited version of the output so that it shows what you would have expected to happen.

**Comment by aramacs** [comment]
Okay. I made some adjustments in my config. But doing as you asked:

1- with or without keyd running both my keys enter and backspace are working fine. 
2- The output I get when I press enter is that blank line after the "aaaaaa"
![image](https://github.com/user-attachments/assets/bfb10eac-49b3-481a-abec-675a816a53c0)

3- Look, this is what I saying. The macro x doesn't overload x in order to behave like backspace, but below the chords "f+d" works just fine. 
![image](https://github.com/user-attachments/assets/cce969d8-3e32-4dba-aebc-105ed16b63fc)


4 - This is the output of keyd monitor 
![image](https://github.com/user-attachments/assets/d5e08253-c426-409f-8eff-0044b193b1c9)


To me the chords solve my problem cuz now I have both backspace and enter on my homerow. But as you said I do believe that could be some hardware problem too.

**Comment by nsbgn** [comment]
I hadn't looked at your config closely before - the issue is that `enter` and `backspace` are not layers, but keys. `overload()`s first argument must be a layer, because it is based on overlapping keys. If you want an overload based on hold time, you are looking for `timeout()`. See also https://github.com/rvaiya/keyd/issues/713#issuecomment-2044532113

Side note - `keyd monitor` and `keyd listen` are not the same thing ;)

But yes, chords are probably a better way to approach this.

**Comment by aramacs** [comment]
My bad so! Thanks for the advices. The lettermod macro is working fine along the chords.
