### ISSUE TITLE
Add tag for v2.1.0-beta

### ISSUE THREAD

**Issue by eNV25** [rvaiya/keyd#88]
Currently the AUR key-git package gets its version from the latest git tag.

```
pkgver() {
	cd "$srcdir/${pkgname%-git}"
	git describe --long --tags | sed -E '
		s/([^-]*-)g/r\1/
		s/-/./g
		s/^v//
	'
}
```

The version is Makefile is currently v2.1.0-beta, but there is no tag for it in the repo. So the package's version and keyd's compiled version differ.

As a solution I think you should add the v2.1.0-beta tag.

Please suggest an alternative solution if you have one.

**Comment by rvaiya** [comment]
Done.

**Comment by rvaiya** [comment]
In general it might be a better idea to pull the version from the Makefile to avoid this problem

E.G

`echo $(awk -F= '/^VERSION=/ {print $2}' Makefile)-$(git rev-parse --short HEAD)|tr '-' '_'`

since I only consciously tag major commits.

**Comment by eNV25** [comment]
I think it's better if you use git tags. You could also get the Makefile's version from git. This is similar to how you currently get your commit hash.

```
VERSION := $(shell git describe --tags | cut -d- -f1)
```

**Comment by rvaiya** [comment]
The project version belongs in the Makefile since it is a property of the project. 

The git hash is just an additional sub-identifier to help disambiguate members of the same version for those compiling from source. There isn't always a version bump for every commit to master and I am liable to forget creating a dedicated one for minor releases. 

At some point I may even release versioned tarballs.
