### ISSUE TITLE
setxkbmap not working after 1.3.1

### ISSUE THREAD

**Issue by valacar** [rvaiya/keyd#92]
I recently upgraded to 2.2.0 beta and noticed `setxkbmap -option "shift:both_capslock"` (ran after keyd) no longer allows me to tap both shift keys to turn on capslock. So I decided to compile a few different versions to see where it broke, and I found that setxkbmap stopped functioning with 2.2.0 beta commit ad6d734d51a3e1ce1b693518af76b0bd35e7cd32. Currently I'm using v1.3.1 (9a424b4ad512804bce198af1281b01fb3a701030) where it works properly.

If this can be fixed, I'd appreciate it, otherwise I guess I will have to find another way using only keyd (if it's possible).

For 1.3.1, default.cfg is just:

`capslock = overload(C, esc)`

For new versions, I use default.conf which is:
```
[ids]
*

[main]
capslock = overload(C, esc)
```
I don't know if it matters, but I'm on Manjaro, XFCE, Linux kernel 5.15. Tested on a Logitech K845 and a Microsoft Wired Keyboard 600. Also I compiled keyd manually myself (not using AUR).

**Comment by rvaiya** [comment]
Thanks for putting in the effort to find the problematic commit. 

This is not surprising given that 2.0 internally simplifies modifier handling.

In general my advice would be to avoid mixing `keyd` and `setxkbmap` (with the possible exception of setting your letter layout) since the two have different internal notions of keycodes. Anything that can be done with `setxkbmap` should be achievable with `keyd`.

In this particular case I believe you want:

```
[shift]
rightshift = capslock
leftshift = capslock
```

`shift` should just be treated like another layer (with some exceptions) so this should naturally read as:

`modify the rightshift and leftshift keycodes within the shift layer`. The first `rightshift` or `leftshift` will thus activate the `shift` layer to which these bindings will then apply. The end result is that simultaneously holding both shift keys will activate  capslock.

**Comment by valacar** [comment]
> In this particular case I believe you want

Yep, this seems to work the same as the "shift:both_capslock" option. Thanks for the config snippet and explanation, I really appreciate it!
