### ISSUE TITLE
Terminate keybind isn't possible on UK Layout

### ISSUE THREAD

**Issue by Jacksaur** [rvaiya/keyd#94]
Found this out the hard way whilst experimenting with Layouts.  
The Backslash+Backspace+Enter keybind to force-terminate Keyd isn't possible on UK/ISO layout keyboards, as there is no Backslash key to use. The ISO version of backslash is instead reported to keyd as "102nd", would it be possible to add this as an alternate binding to terminate Keyd?

**Comment by Compile-Time** [comment]
Not the developer, but I decided to experiment with this since I use a German layout.

Keyd is only aware of the US English keyboard layout. So keyd interprets your key presses as if they were done on that layout.

Therefore, I ran `keyd -m` to see which key outputs a backslash. On the German layout this is the pound 
key ('#'). When I press #+backspace+enter keyd terminates as intended.

So you probably can also terminate keyd with your layout if you know which key corresponds to backslash.

**Comment by Compile-Time** [comment]
It might be a good idea to add some form of information or disclaimer about this to the terminate key binding documentation.

**Comment by rvaiya** [comment]
Thanks for making me aware of this. I've changed the sequence to `enter+backspace+escape` to (hopefully) minimize this problem for non-english users.

**Comment by Jacksaur** [comment]
Thank you for the fast action :)
