### ISSUE TITLE
Systemd indepentent

### ISSUE THREAD

**Issue by sarmong** [rvaiya/keyd#98]
I just found this tool and it seems really simple and may be exactly what I need, however, I don't really like that it requires systemd.

It would  be really nice to make it independent and have config inside the user home directory and just start it up as a shell command. Is it possible to do?

**Comment by rvaiya** [comment]
> I just found this tool and it seems really simple and may be exactly what I need, however, I don't really like that it requires systemd.

systemd is not strictly required. You can run it as a standalone daemon with `-d`. You will need udev for device detection, but most systems which don't use systemd ship with eudev as an alternative.

> It would be really nice to make it independent and have config inside the user home directory and just start it up as a shell command. Is it possible to do?

This is not as simple as it seems since the user would require system wide access to the input devices and only one instance of the program may be running at a time. See #7 and #45.

**Comment by rvaiya** [comment]
It's worth noting that a user with access to the keyd socket (i.e is in group `keyd`) can modify the keymap at runtime using `-e`. So you could put something like `keyd -e "capslock = overload(control, escape)"` your `~/.xinitrc`, though these changes will be system wide, so you may want to do a `keyd -e reset` on logout.

**Comment by rvaiya** [comment]
I am closing this for now. Feedback is appreciated from non systemd users, so if you stumble across this don't hesitate to open another issue.

**Comment by explosion-mental** [comment]
Hey @rvaiya, I would suggest to remove creating sytemd directories on `make install` and maybe have it as `make install-systemd` or just have some variable flag in the makefile.

**Comment by rvaiya** [comment]
I've added some logic to conditionally install the systemd files if it is present.

@sarmong It's worth noting that udev has been removed as a dependency since the original post. keyd is now fully systemd independent. However I may make logind an optional dependency for multi user support at some point since there isn't a good cross platform way to do session tracking.
